fabric8-ui/fabric8-planner

src/app/work-item/work-item.service.ts

In https://github.com/almighty/almighty-core/issues/97 we've changed the core to list workitems under `/api/workitems` (notice the "s" at the end). The docker container of almighty-core is not using this at the moment but we try to get it in there as quick as possible.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/almighty/almighty-ui/12)

Fix REST path to workitems

---

src/app/work-item/work-item-list/work-item-list.component.css
src/app/work-item/work-item-list/work-item-list.component.html

https://github.com/almighty/almighty-ui/issues/2
Add default styling for the work item list view like status, type, description text
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/almighty/almighty-ui/28)

Add default styling for the work item list view (https://github.com/almighty/almighty-ui/issues/2)

---

Dockerfile.centos

This might no longer be needed, but as a data point, the npm install was failing unable to unpact a bzip2 archieve.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/almighty/almighty-ui/38)

the nmp install barfs over a missing bzip2

---

src/app/app.module.ts
src/app/shared-component/status-drawer.component.css
src/app/shared-component/status-drawer.component.html
src/app/shared-component/status-drawer.component.ts
src/app/work-item/work-item-list/work-item-list.component.css
src/app/work-item/work-item-list/work-item-list.component.html

Why?
- There is a status label on every work list item.
- Clicking on that label should give a drawer to select and change status.
What?
- This is a component which can be used in various places for a work item.
- It takes workItem as a parameter.
- Currently it's built based on some static data.
- The backend is not prepared for showing and changing status yet.
Future planning:
- We can fetch different types of status and their colors from a backend endpoint.
- Based on the statusCode from a workItem we show it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/almighty/almighty-ui/33)

A drawer for change status added

---

src/app/work-item/work-item-detail/work-item-detail.component.html

Work item's view details will be able to display the work item title in the details page.

Fix for #111 - display work item's title on the detail's page

---

src/app/work-item/work-item-detail/work-item-detail.component.html

Fix #110.
Previous behaviour - User could click on Save after clearing the title.
Updated behaviour - If the title is cleared:
- Save gets disabled
- An error message is displayed below the Title text field.

Fix for #110 - Save works with a blank title on the work item's detailed view page

---

config/webpack.test.js

Fixes #162 - provide context for webpack to allow Angular's use of system.import.

Fixes #162 - provide context for webpack to allow system.js

---

README.adoc
package.json
run_unit_tests.sh

Fixes #134 - Make it easier to run the test. Update the README with instructions.
Now "npm test" will run every check we have. There are separate commands for each check and they are now explained in the README.

Fixes #134 - Make it easier to run the test.

---

src/app/work-item/work-item-detail/work-item-detail.component.html
src/app/work-item/work-item-detail/work-item-detail.component.spec.ts
src/app/work-item/work-item-detail/work-item-detail.component.ts

PR #186 needs to be merged first.
Task reference - #126 
Add a confirmation dialog on the work item's view/edit page which gets displayed if a user makes changes and clicks on back without saving the changes.

Add a confirmation dialog box to the work item veiw/detail page (#126)

---

src/app/auth/authentication.service.ts
src/app/header/header.component.ts
src/app/work-item/work-item-detail/work-item-detail.component.spec.ts
src/app/work-item/work-item-detail/work-item-detail.component.ts
src/app/work-item/work-item-list-entry/work-item-list-entry.component.ts
src/app/work-item/work-item-list/work-item-list.component.ts

- An event is broadcasted over logout
- Listened through out the comonents
- Update components accordingly on logout
- Also removing token from the URL after login
- Need to find a better way to do it, other than just
reloading the app to the base url.

Logout event listener to avoid page reloading

---

src/app/work-item/work-item-list/work-item-detail/work-item-detail.component.html
src/app/work-item/work-item-list/work-item-detail/work-item-detail.component.scss
src/app/work-item/work-item-list/work-item-detail/work-item-detail.component.ts

- User hovers over the description.
- A border with that edit icon appears.
- Clicking on the box or the edit icon would make the border highlighted
with light blue.
- And user can edit.
- User can press ESC while editing to cancel or Enter to save.
- Pressing ESC twice will close the panel.

Outline around description field is take care of. (fixes #278)

---

src/app/work-item/work-item-list/work-item-detail/work-item-detail.component.ts
src/app/work-item/work-item.service.ts

Fix for WorkItemTypes API being called twice during first detail view (#276)

Fix for WorkItemTypes API being called twice during first detail view (#276)

---

src/app/work-item/work-item-quick-add/work-item-quick-add.component.scss

Fix quick-add's description box's height on Firefox (#261).

Fix quick add's description box's height on Firefox (#261)

---

src/app/work-item/work-item-list/work-item-list-entry/work-item-list-entry.component.html
src/app/work-item/work-item-list/work-item-list-entry/work-item-list-entry.component.ts
src/app/work-item/work-item-list/work-item-list.component.html
src/app/work-item/work-item-list/work-item-list.component.ts
src/app/work-item/work-item.service.ts

Implement Move Top/Move Down options under the kabob menu, for a work item (#171). 
This is a UI implementation only as ordering has not been setup, the location cannot be persisted.
If we add a new item or refresh the page the ordering is lost.

Implement Move Top/Move Down options under the kabob menu, for a work item(#171).

---

src/tests/work-item/work-item-list/displayAndUpdateWorkItemDetails.spec.js
src/tests/work-item/work-item-list/displayWorkItemList.spec.js
src/tests/work-item/work-item-list/quickadd-workitem.spec.js
src/tests/work-item/work-item-list/test-template.spec.js
src/tests/work-item/work-item-list/unauthorizeduser.spec.js
src/tests/work-item/work-item-list/work-item-detail.page.js
src/tests/work-item/work-item-list/work-item-list.page.js
src/tests/work-item/work-item-list/work-item-list.spec.js

The major change in most of the files is due to change in structure of this workitem-list-page 
var WorkItemListPage = function () { 
var WorkItemListPage = function (login) {  Added one argument for authorized and non-authorized user , its basically a Boolean value , which accept "true" for Authorized.
Test coverage:
-    Test if user is not authenticated can view almighty in read only
-     Test Quick add work item should not be visible
-     Test user should not be able update the work item type
-     Test user should not be able to update the work item state
-     Test user should not be able to Delete any work item

Funtional Tests for unauthorized user

---

src/assets/stylesheets/dropdowns.scss
src/assets/stylesheets/variables.scss

Make font awesome work on demo.almighty.io
Renamed the icon-font-name-fa, in https://github.com/nimishamukherjee/almighty-ui/blob/alm-ui-353/src/assets/stylesheets/variables.scss, to FontAwesome.
This is in line with https://github.com/patternfly/patternfly/blob/master/src/less/variables.less

Make font awesome work on demo.almighty.io

---

README.adoc

This adds two click-able badges to the README to show the current build status and coverage at a glance.

Add coverage and build badge to README

---

src/app/work-item/work-item-list/work-item-detail/work-item-link/work-item-link.component.html
src/app/work-item/work-item-list/work-item-detail/work-item-link/work-item-link.component.ts

Changes to prevent freezing of the screen if the target Workitem is not found while displaying the workitem links

Prevent freezing if the target Workitem is not found

---

src/app/work-item/work-item-list/work-item-detail/work-item-detail.component.html

Fix hover behaviour of the title's edit icon, during dialogue based work item creation - the edit icon will not be shown on hover over the title input field (#540).

Fix hover behaviour of the title's edit icon, during dialogue based work item creation.

---

src/app/work-item/work-item-list/work-item-detail/work-item-detail.component.html
src/app/work-item/work-item-quick-add/work-item-quick-add.component.ts

- Makes the template display blank text for falsy values of `description`
- Avoids creating WI with `null` type descriptions form quick-add
- Updated the validator for both title and descriptions
- Reassign description as "" if no value was provided (i.e. null)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/almighty/almighty-ui/591)

Validates WI title/desc datatypes and values, fixes #530

---

src/app/work-item/work-item-list/work-item-list-entry/work-item-list-entry.component.html
src/app/work-item/work-item-list/work-item-list-entry/work-item-list-entry.component.scss
src/app/work-item/work-item-list/work-item-list-entry/work-item-list-entry.component.ts
src/app/work-item/work-item-list/work-item-list.component.html
src/app/work-item/work-item-list/work-item-list.component.scss
src/app/work-item/work-item-list/work-item-list.component.ts
src/app/work-item/work-item.service.ts

This PR will add the UI behaviour only, for moving a work item up or down.
UI Task - #557.
Note: There are two experiences - selecting a work item and checking a work item to move it.
1. Selecting a work item will highlight the work item and open the detailed view.
2. Selecting the checkbox will display the move options menu
3. A work item whose checkbox is selected can be moved up or down
4. If a work item is selected with it's detailed view open, select the checkbox on another work item and move it up or down. The selected work item remains selected and the detailed view remains open.

Move a work item up and down for order of execution (#557)

---

src/app/work-item/work-item-list/work-item-list.component.html
src/app/work-item/work-item-list/work-item-list.component.ts
src/app/work-item/work-item.service.ts

This PR will add the UI behaviour only, for moving a work item to either the top or bottom of the visible screen.
UI Task - #558
Note: Current implementation of Move to Bottom will take the user to the end of the loaded list.

Move work items top and bottom for order of execution  (#558)

---

cico_build_deploy.sh
cico_run_tests.sh
tsconfig.json

This ensures that failed tests are detected by exiting the cico_*.sh scripts as soon as an error occured. I've added the `set -e` switch to exit on error and that allowed me to remove all the check for the last error code.

Make tests actually fail

---

src/app/work-item/work-item.component.html

As of https://github.com/almighty/almighty-core/commit/7a5b4fd32588eb7304bea7a72746f0894bae1cf5 we no longer store WIT names with the `"system."` prefix. Hence, we must not strip-off 7 characters in  front of WIT names when displaying.
When you click this button in the top right corner 
you get this without this change:
Quite obviously somebody removed the first 7 characters and not just left trims any occurence of "system.".

Fix display of names in work item create dialog

---

src/app/login/login.component.html

We switched to keycloak authentication instead of github in almighty-core. Our keycloak uses developers.redhat.com as Identity Provider. So we change the sign in button.
Fixes #780

Change "Sign in with GitHub" button to "Sign in with Red Hat Developers

---

src/app/shared/mock-data.service.ts
src/app/shared/mock-data/work-item-mock-generator.ts
src/app/shared/mock-http.ts

Fixes a problem with the mock of links. Extends the functionality following the core api to retrieve single sets of links connected to a work item.

Fixed link mocks.

---

src/app/work-item/work-item-detail/work-item-comment/work-item-comment.component.html
src/app/work-item/work-item.service.ts

Comments from backend are now in correct order and paginated.
Related to fabric8io/fabric8-planner#729

Remove reordering of comments in UI

---

src/app/work-item/work-item-quick-add/work-item-quick-add.component.ts

Remove 'system.' prefix from the quick add work item form (#783).
Note that this is a temporary fix to enable quick add.
We can use 798 to track the discussion and implementation of dynamic setting of the quick add work item type.

Remove 'system.' prefix from the quick add work item form (#783).

---

src/app/work-item/work-item-detail/work-item-comment/work-item-comment.component.html
src/app/work-item/work-item-detail/work-item-comment/work-item-comment.component.scss
src/app/work-item/work-item-detail/work-item-comment/work-item-comment.component.ts
src/app/work-item/work-item.service.ts

- Replaces textarea with contenteditable div, by almEditable directive
- Fixes an index counter issue introduced by #731, that was breaking tests
- Workflow fixes for the new element (content reset on various actions)
- Optimized the way insertion into comment collection for a WI was being handled

Comment input field as almEditable element, fixes #722

---

src/app/iteration/iteration-modal/iteration-modal.component.html
src/tests/work-item/work-item-list/page-objects/work-item-list.page.js

The warning
`Started
...........................................[09:46:23] W/element - more than one element found for locator By(css selector, .help-block) - the first result will be used
....................................`
Use to show up for iterations , fixed in this PR

Fix multiple element detection warning in iteration help-block

---

src/app/work-item/work-item-detail/work-item-detail.component.html
src/app/work-item/work-item-detail/work-item-detail.component.scss

Update UI for Title Add/Edit on WI Detail Page as per Visuals
#875

fix: Update Visuals for Title Add/Edit on WI Detail

---

cico_build_deploy.sh
cico_run_tests.sh
src/app/iteration/iteration.service.ts
src/app/iteration/iterations.service.spec.ts
src/app/shared/mock-http.ts

We have introduced a temporary space service, but we didn't have any mock service for that. Inside the docker container, being unable to reach the space endpoint, pages were failed to be loaded thus the tests were failing. 
I just have added the space endpoint to the mock service and used the mock service in iteration service (this is something that I missed while creating the service). Now the functional tests inside docker run fine.

Added space API to mock http API list

---

src/app/shared-component/editable/almeditable.directive.ts
src/app/work-item/work-item-detail/work-item-detail.component.html
src/app/work-item/work-item-detail/work-item-detail.component.ts

Disabled almEditable automatically setting focus (often leading to weird interactions). With this patch, setting focus on the editable element is part of the interaction-flow implementation, and not default to almEditable.
This also fixes the existing cases affecting the changes in detail-view (title and descriptions - for general view as well as creating new WI).

Fixes the curious case of almEditable (on-demand) element focus

---

src/app/iteration/iteration.component.html

Just noticed that in the sidebar on the left side it says `Future Iteration` and `Past Iteration` but if you expand those menus multiple iterations are shown.

Make future and past iterations plural forms in the UI

---

package.json
src/app/work-item/work-item-list/work-item-list-entry/work-item-list-entry.component.html
src/app/work-item/work-item-list/work-item-list-entry/work-item-list-entry.component.ts
src/app/work-item/work-item-list/work-item-list.component.html
src/app/work-item/work-item-list/work-item-list.component.ts
src/app/work-item/work-item.module.ts

Tree nodes are not displayed by default. To enable the toggle, the WorkItem object must have a "children" array. Alternatively, the components getChildren function may be used to fetch children as needed. In this scenario, a "hasChildren" boolean property can be added to the WorkItem object to enable the toggle.
Note that this was tested in the master branch first, then ported to the ngx-widgets branch -- screen shots were taken from the master branch -- see PR #949.
Dragging is enabled, but can be restricted using the allowDrop function.
See below for documentation regarding available options.
https://angular2-tree.readme.io/docs/options
See below for full documentation.
https://angular2-tree.readme.io/docs
Tree list with toggle
Tree list without toggle (default)

Added treelist component

---

CONTRIBUTING.adoc
README.adoc

Updated the README.adoc and created CONTRIBUTING.adoc
- Better asciidoc formatting
- Rephrasing and cleaning up of contents
- Contribution and commit related doc moved into new contribution guide (to be expanded)

docs(README): Format main readme and split apart contributing.adoc

---

package.json
src/app/work-item/work-item-list/work-item-list-entry/work-item-list-entry.component.html
src/app/work-item/work-item-list/work-item-list-entry/work-item-list-entry.component.scss
src/app/work-item/work-item-list/work-item-list.component.html
src/app/work-item/work-item-list/work-item-list.component.scss
src/app/work-item/work-item-list/work-item-list.component.ts

Moved a couple Patternfly styles (list-view-pf, list-group & list-group-item) from the planner UI to the tree list component.
We will want to use these Patternfly styles in other places with the tree list. This means there are far less tree list styles to override in planner and/or elsewhere.

Moved Patternfly styles to tree list component

---

package.json
src/app/app.module.ts
src/app/iteration/iteration.component.html
src/app/iteration/iteration.module.ts
src/app/toolbar-panel/toolbar-panel.component.html
src/app/toolbar-panel/toolbar-panel.module.ts
src/app/type/type.component.html
src/app/type/type.module.ts
src/app/work-item/work-item-board/planner-board.module.ts
src/app/work-item/work-item-detail/work-item-comment/work-item-comment.component.html
src/app/work-item/work-item-detail/work-item-comment/work-item-comment.component.spec.ts
src/app/work-item/work-item-detail/work-item-detail.component.html
src/app/work-item/work-item-detail/work-item-detail.component.spec.ts
src/app/work-item/work-item-detail/work-item-detail.module.ts
src/app/work-item/work-item-list/planner-list.module.ts
src/app/work-item/work-item-list/work-item-list-entry/work-item-list-entry.component.html
src/app/work-item/work-item-list/work-item-list.component.spec.ts
src/app/work-item/work-item.component.html
src/app/work-item/work-item.module.ts

Bumping ng2-bootstrap version to be compatible with ngx-widgets. Also renaming deprecated 'tooltipPlacement' attributes as 'placement'.
Note that ngx-widgets is currently generating deprecation warnings for 'tooltipPlacement'. This repo is using the latest version of ng2-bootstrap 1.3.3. In order to fix these deprecations, planner also needs to use the same version. If not, planner's pages will not render when ngx-widgets uses the new placement attribute name.

Bumped ng2-boostrap version

---

src/app/work-item/work-item-board/planner-board.module.ts
src/app/work-item/work-item-list/planner-list.module.ts
src/app/work-item/work-item.module.ts

This keeps UserService as a singleton only defined at the application level

fix(providers): remove extra UserService providers

---

src/app/area/area.service.ts
src/app/models/area.model.ts
src/app/shared/mock-data.service.ts
src/app/shared/mock-data/area-mock-generator.ts
src/app/shared/mock-http.ts

Added areas as mock data and service.
@sanbornsen @naina-verma 
The area drop down still does not work inmemory mode
Check the file area.service.ts - line 56 
https://github.com/nimishamukherjee/fabric8-planner/blob/c07a18dc0e306e083c2a5cd2cd350d3d894c2cb1/src/app/area/area.service.ts#L56

fix(inmemory): Adds areas mock data and service.

---

src/app/toolbar-panel/toolbar-panel.component.ts

Areas are now available filter-options
- going with current implementation of Users-filter, this is hard-coded as well
- relies on Area service to provide the list of all areas for dropdown
Closes #1147

feat(filters): add areas to available filters

---

src/app/toolbar-panel/toolbar-panel.component.scss
src/app/work-item/work-item-board/work-item-board.component.html
src/app/work-item/work-item-board/work-item-board.component.scss
src/app/work-item/work-item-detail/work-item-detail.component.scss
src/app/work-item/work-item-list/work-item-list.component.html
src/assets/stylesheets/shared/main.scss

Fix the position of Detail page relative to the content
Closes: #1156

refactor(detail-page): align detail page to the content

---

src/app/work-item/work-item-board/planner-board.module.ts

Lazy loaded modules can’t access overridden modules provided to the main app module. 
- For example, board module is lazy loaded 
- We had `{ provide: Http, useClass: MockHttp }` in-app module 
- Board module could not find it and be using the regular Http

fix(mock): Added MockHttp to board module's provider list

---

package.json

We don't rely on versions brought in through ngx-login-client
or ngx-fabric8-wit.

fix(version): ngx-base as direct dependency

---

src/app/work-item/work-item-detail-add-type-selector/work-item-detail-add-type-selector.component.ts
src/app/work-item/work-item-detail/work-item-detail.component.ts

Fixes creation of work item when using the detail panel. Uses type ID instead of the string 'new' when creating a new work item object.

fix(detail panel): Fixes creation of work item when using the detail panel

---

src/app/work-item/work-item-detail/work-item-comment/work-item-comment.component.scss

fix long words in comments field
closes: #1324

fix(comments-wrapping): fix word-wrapping in comments

---

src/app/work-item/work-item-detail/work-item-detail.component.ts

Fixes fabric8io/fabric8-ui#393 on platform:
space can be null when going back home and 
registered listeners need to account for this

fix(nullref): make sure space is not null

---

src/app/iteration/iteration-modal/iteration-modal.component.html
src/app/iteration/iteration-modal/iteration-modal.component.scss
src/app/iteration/iteration-modal/iteration-modal.component.ts
src/app/iteration/iteration.component.html

- Fix issue - #1501 
- match search parent iteration field UX with [wireframe](https://redhat.invisionapp.com/share/YPB0J2NGB#/screens/225825534).
- Prefilled the parent iteration field if user select create child option from kebob menu of existing iteration.

fix(iteration): issue in nested iteration

---

src/app/iteration/iteration.component.html
src/app/iteration/iteration.component.scss
src/app/side-panel/side-panel.component.scss
src/app/work-item/work-item-board/work-item-board.component.html
src/app/work-item/work-item-board/work-item-board.component.scss
src/app/work-item/work-item-list/work-item-list.component.html
src/app/work-item/work-item-list/work-item-list.component.scss
src/assets/stylesheets/shared/_overrides-for-patternfly.scss

Update the side panel to match the new visual design scheme. This is one part of the overall design upgrade. There will be additional PRs for the navigation (in fabric8-ui), Detail Panel and primary buttons.
**NOTE: The 'Collapse Panel' in the visual designs is not, and should not be, implemented**
visual design here: [Planner-HolisticView](https://redhat.invisionapp.com/share/N7B74T4MH#/226261730_A-0400)
screenshots:

feat(sidepanel): update for visual designs of side panel

---

src/app/work-item/work-item-quick-add/work-item-quick-add.component.ts

Remove `renderer.invokeElementMethod` as this method has been removed from Angular2.

fix(quickAddComponent): remove renderer.invokeElementMethod (fix #1418)

---

src/app/work-item/work-item-board/work-item-board.component.html
src/app/work-item/work-item-board/work-item-board.component.scss
src/app/work-item/work-item-board/work-item-board.component.ts

Fixes #1303  #1271 
@nimishamukherjee @sanbornsen @vikram-raj I have added css property for `selected item` in board view.
I would like to confirm the `color=#bee1f4` and `border width=3px`. (Hence WIP :smile: )
Also, when I close the item detail pop over, the WI box still remains selected. I found this same in list view too.
[Issue](https://github.com/fabric8io/fabric8-planner/issues/1554) created for de-selection on close of deatil-box.

Show "selection" for selected board-view item.

---

src/app/work-item/work-item-detail/work-item-detail.component.scss

the z-index of the detail panel needed to be brought down due to it being higher than the dropdowns. this caused the user dropdown to appear behind the detail panel when it was open.
fixes https://github.com/fabric8io/fabric8-ui/issues/595

fix(DetailPanel): fix z-index of detail panel

---

package.json
src/app/app.module.ts
src/app/iteration/iteration-modal/iteration-modal.component.ts
src/app/iteration/iteration.component.html
src/app/iteration/iteration.component.scss
src/app/iteration/iteration.component.ts
src/app/iteration/iteration.service.ts
src/app/iteration/iterations.service.spec.ts
src/app/models/iteration.model.ts
src/app/shared/mock-data.service.ts
src/app/shared/mock-data/iteration-mock-generator.ts
src/app/shared/mock-data/work-item-mock-generator.ts
src/app/shared/mock-http.ts
src/app/side-panel/side-panel.component.ts
src/app/work-item/work-item-board/planner-board.module.ts
src/app/work-item/work-item-detail/work-item-detail.component.ts
src/app/work-item/work-item-detail/work-item-detail.module.ts
src/app/work-item/work-item-list/planner-list.module.ts
src/app/work-item/work-item-list/work-item-list.component.ts
src/app/work-item/work-item.service.ts

Fixes several more issues in the iterations panel:
- when the iteration on a work item changes, the counts on the iteration panel are updated.
- the root iteration is no longer displayed in the iteration list.
- several severe bug fixes in the mock data service(s).
- the date display is not visible when no dates are set (no lone "-" display on the current iteration in that case).
This also fixes some other things:
- the list is now updated correctly when selecting a new iteration (only in list view, in board view, this is still broken).
- fixes some other mock related problems.

Fix iterations, Part 2

---

package.json
src/app/work-item/work-item-board/planner-board.module.ts
src/app/work-item/work-item-list/planner-list.module.ts
src/app/work-item/work-item-list/work-item-list.component.ts

Downgrading angular-tree-component to 2.7.0 to avoid recent issues with the Angular 4 upgrade.
PRs for platform and runtime:
https://github.com/fabric8io/fabric8-ui/pull/675
https://github.com/fabric8-ui/fabric8-runtime-console/pull/274

fix(treelist): Downgraded angular-tree-component for stability

---

src/app/iteration/iteration.component.scss
src/app/side-panel/side-panel.component.scss

add a hover state to the sidepanel headers to signify that they are clickable
resolves https://github.com/fabric8io/fabric8-ux/issues/389
All tests run locally and passed

fix(sidepanel): add hover state to sidepanel headers

---

src/app/shared/http-service.ts
src/app/work-item/work-item.service.ts

fixes #1604 
Earlier we used to search across spaces but now selected space will be considered for searching.
New URL will look like - `http://localhost:8080/api/search?spaceID=52e7929d-879c-4936-974f-0cd7cc0aa5cc&q=log%20type:86af5178-9b41-469b-9096-57e5155c3f31` 
note the `spaceID` in the query params.
Backend still support searching across all spaces. Do not pass `spaceID` to search across all spaces.
Backend related [task](https://github.com/almighty/almighty-core/pull/1184) is already merged in master.

Search WI within selected space (while linking the item).

---

src/app/toolbar-panel/toolbar-panel.component.scss

fix the alignment of the type selector dropdown to justify to the right of the button

fix(board): fix alignment of type selector

---

src/app/work-item/work-item-detail/work-item-detail.component.ts

After creating new item with details page, navigating to any iteration from back log is making the new created item's details page blank.
* Stay on backlog
* Detail add an item
* Wait for opening the details page of newly created item
* Switch to an iteration
* URL looks good but the details page is going blank as it is for creating a new item.
* Remove incorrect use of **route.queryParams** observable and use **route.snapshot** instead.
* Use the advantage of **switchMap** to queue up the to observable i.e. **currentSpace** and then **route.params**

fix(detail): Detail page bug fixed

---

src/app/app.component.ts
src/app/app.module.ts
src/app/work-item/work-item-board/work-item-board.component.ts
src/app/work-item/work-item-list/work-item-list-entry/work-item-list-entry.component.ts

Enable Move to Backlog option on list view and backlog view
Add toast notification for Move to Backlog success and failure
This fixes #1499.
Existing issue:
Update of count in backlog (+1) and selected iteration (-1) does not happen
Update of list does not happen

fix(kebab menu): Enable Move to Backlog functionality. Fixes #1499

---

src/app/shared/mock-data.service.ts
src/app/shared/mock-data/schema-mock-generator.ts
src/app/shared/mock-http.ts
src/app/toolbar-panel/toolbar-panel.component.html
src/app/toolbar-panel/toolbar-panel.component.ts
src/app/work-item/work-item-list/work-item-list.component.html
src/app/work-item/work-item-list/work-item-list.component.scss
src/app/work-item/work-item-list/work-item-list.component.ts

The tree now displays a "proper" tree without obvious dupes. Also added a toggle that enables switching between the tree and a flat list. 
KNOWN ISSUE: if the tree is expanded when switching the mode, the user will experience some weird issues. Problem is there seems to be no way of force-collapsing the tree yet. We will fix that in a later PR.

Tree only displays no-parent items now; with toggle between that and flat mode

---

src/app/collaborator/collaborator.service.ts
src/app/shared/filter.service.ts

Fixes a crash when de-selecting the space. This was for example happening when switching back from the Planner to the spaces list in Platform.

fix(spaces): fix crash on deselecting space.

---

runtime/src/app/components/header/header.component.ts
runtime/src/index.html
runtime/src/tests/work-item/work-item-list/EXCLUDED/basicAssignFilter.spec.js
runtime/src/tests/work-item/work-item-list/EXCLUDED/basicDragAndDrop.spec.js
runtime/src/tests/work-item/work-item-list/EXCLUDED/orderOfExecution.spec.js
runtime/src/tests/work-item/work-item-list/EXCLUDED/unauthorizeduser.spec.js
runtime/src/tests/work-item/work-item-list/EXCLUDED/work-item-timeStamp.spec.js
runtime/src/tests/work-item/work-item-list/assign.spec.js
runtime/src/tests/work-item/work-item-list/constants.js
runtime/src/tests/work-item/work-item-list/displayAndUpdateWorkItemDetails.spec.js
runtime/src/tests/work-item/work-item-list/displayWorkItemList.spec.js
runtime/src/tests/work-item/work-item-list/linkItem.spec.js
runtime/src/tests/work-item/work-item-list/page-objects/common.page.js
runtime/src/tests/work-item/work-item-list/page-objects/template.page.js
runtime/src/tests/work-item/work-item-list/page-objects/work-item-board.page.js
runtime/src/tests/work-item/work-item-list/page-objects/work-item-detail.page.js
runtime/src/tests/work-item/work-item-list/page-objects/work-item-list.page.js
runtime/src/tests/work-item/work-item-list/quickadd-workitem.spec.js
runtime/src/tests/work-item/work-item-list/smokeTest.spec.js
runtime/src/tests/work-item/work-item-list/startcoding.spec.js
runtime/src/tests/work-item/work-item-list/test-template.spec.js
runtime/src/tests/work-item/work-item-list/testHelpers.js
runtime/src/tests/work-item/work-item-list/testSupport.js
runtime/src/tests/work-item/work-item-list/work-item-detailed-dialog.spec.js
runtime/src/tests/work-item/work-item-list/work-item-dynamic-fields.spec.js
runtime/src/tests/work-item/work-item-list/work-item-list.spec.js
runtime/src/tests/work-item/work-item-list/workitem-naughty-string.spec.js
runtime/tests/local_run_functional_tests.sh
runtime/tests/run_functional_tests.sh

closes #1891 
That was lingering for quite a while, without any apparent purpose or use.

chore(planner): remove traces of "almighty" string and replace them with "planner"

---

README.adoc

@michaelkleinhenz As discussed here: https://stackoverflow.com/questions/402377/using-getopts-in-bash-shell-script-to-get-long-and-short-command-line-options search for "# NOTE: This requires GNU getopt.  On Mac OS X and FreeBSD, you have to install this
I've added it as a pre-requisites for macOS

Run planner.on.mac os

---

src/app/components/work-item-list-entry/work-item-list-entry.component.html

This reverts commit 8cd9115b50dbd2e3e019e2ecdd0845cf0b1a852d.
Sorry, I've used the Github UI to create this wrong commit. Will never do it again!

Revert "fix(frontend): show work item type name in list"

---

src/app/components/work-item-detail/work-item-detail.component.ts

When we add a work item using the detail panel the work item gets saved but the panel does not get the newly created work item. This happens as un-subscribe gets called and the GET on the work item gets cancelled so the panel remains as is.

fix(detail panel): Fix duplication of work item

---

README.adoc

The section on CI scripts is no longer valid since #1978

fix(doc): removed README section on CI scripts

---

src/app/components/work-item-link/work-item-link.component.ts
src/app/mock/mock-data.service.ts
src/app/mock/mock-data/schema-mock-generator.ts
src/app/mock/mock-data/work-item-mock-generator.ts
src/app/mock/mock-http.ts
src/app/models/link-type.ts
src/app/models/work-item.ts
src/app/services/work-item.service.ts

Once https://github.com/almighty/almighty-core/pull/1444 is merged, we need to adopt the UI as well.
This is my attempt to do so but I haven't tested it, just went over the code and did the follwing:
1. Remove the source and target type fields from the work item link type
2. Don't filter by type when searching doing the type-ahead.
I would love to get some feedback on this because most of what I did was assisted guessing ;)

Refactor link creation

---

deploy/release.groovy

@michaelkleinhenz and @nimishamukherjee found that github releases were out-of-date. The ci build master job was failing due to the functional stage.
I also realized that functional tests and unit tests are validated twice in this CI jobs, as shown in the following picture:

(fix): ci job that creates github releases

---

README.adoc
docs/building_planner.adoc

This PR fixes the links in the Readme and Building Planner Docs.

fix(readme): Correct urls for links in Readme and Building Planner docs.

---

package.json
runtime/package.json

Updated the Typescript version in the package.json files (runtime also). This is a temporary fix. This will allow us to continue merging PRs.

fix(package): Update Typescript version to 2.3

---

package.json
runtime/src/app/app.module.ts
src/app/components/card/card.component.html
src/app/components/iterations-panel/iterations-panel.component.html
src/app/components/iterations-panel/iterations-panel.module.ts
src/app/components/planner-board/planner-board.module.ts
src/app/components/planner-list/planner-list.module.ts
src/app/components/toolbar-panel/toolbar-panel.component.html
src/app/components/toolbar-panel/toolbar-panel.component.ts
src/app/components/toolbar-panel/toolbar-panel.module.ts
src/app/components/work-item-comment/work-item-comment.component.html
src/app/components/work-item-create/work-item-create.module.ts
src/app/components/work-item-detail/work-item-detail.component.html
src/app/components/work-item-detail/work-item-detail.module.ts
src/app/components/work-item-iteration-modal/work-item-iteration-modal.module.ts
src/app/components/work-item-link/work-item-link.component.html
src/app/components/work-item-list-entry/work-item-list-entry.component.html
src/app/components/work-item-quick-add/work-item-quick-add.component.html
src/app/components/work-item-quick-add/work-item-quick-add.module.ts

This replaces components from ngx-widgets with patternfly-ng, including:
- The tooblar component
- The filter/sort components used by toolbar.
This also introduces the latest dropdown from ngx-bootstrap for compatibility with patternfly-ng.
See: https://github.com/fabric8-ui/fabric8-ui/pull/1738

Introducing patternfly-ng

---

src/app/components/work-item-quick-add/work-item-quick-add.component.html

Fixed the type selection drop-up menu in quick add section of the planner list page. In order for the menu to open, additional 'drop-up' formatting is needed with ngx-bootstrap.
Note the [dropup]="true" statement. We cannot simply add the style class ourselves.

Fix drop-up menu

---

runtime/tests/docker-entrypoint.sh
runtime/tests/run_functional_tests.sh

As you can see in the job activity of planner PRs, all are failing in the funciontal tests cause a new version of the chrome driver is used 2.31. This version is most certainly the cause of this problem, so we'll stick to 2.30 version as done in the past.

fix(functests) stick to chrome driver 2.30 version

---

runtime/src/tests/work-item/work-item-list/page-objects/work-item-list.page.js

Added page objects 'clickPortfolio' and 'clickRequirements' to click on category tabs in the planner left panel.

feat(test): add page objects to detect category tabs

---

runtime/package.json

The ngx-version needs to be updated under the runtime folder. The root package.json and runtime's package.json need to have the same ngx-widgets version.

fix(runtime): Update ngx-widget version under runtime.

---

package.json

Set karma typescript version to 3.0.5 which works with Typescript 2.3.
Planner unit tests were failing as we had set "karma-typescript": "^3.0.2". This would install 3.0.6 and this version uses the latest Typescript version (2.5.2).
3.0.3, 3.0.4 and 3.0.5 work with Typescript 2.3

fix(unit tests): Set karma typescript version to 3.0.5

---

runtime/package.json
runtime/tests/protractor.config.js

This PR improves the verbosity of test results using the `jasmine-spec-reporter`[1] module.
**Before**
**Now**
[1] - https://github.com/bcaudan/jasmine-spec-reporter

fix(test): Make test results more verbose

---

docker-compose.yml

This PR changes the orchestration of the Docker Compose stack to match the new auth strategy introduced in fabric8-services/fabric8-wit#1668. Going forward it'll be rather easier to use KC auth on `fabric8-test` realm using this strategy for testing and development.
**TL;DR:** If wit/core fails to start with `$ docker-compose up`, just force a `$ docker-compose start core` on another terminal. This will continue the `stdout` on the former terminal and the later terminal can be closed after invoking the command.
**Longer version:** `core` image may fail to start most of the time because it expects the `auth` service to be already up and running. This can be somewhat handled with netcat polling scripts or various third-party tools like `wait-for-it` or `dockerize` etc. and even with …

refactor(deploy): auth-strat parity with fabric8-services/fabric8-wit#1668

---

src/app/components/work-item-list-entry/work-item-list-entry.component.html
src/app/components/work-item-list-entry/work-item-list-entry.component.less

Add Tooltips in list entry to
OSIO Issue: https://openshift.io/openshiftio/openshiftio/plan/detail/1571

fix(list-entry): add tooltips in list view

---

runtime/src/tests/work-item/work-item-list/area.spec.js
runtime/src/tests/work-item/work-item-list/assign.spec.js
runtime/src/tests/work-item/work-item-list/basicAssignFilter.spec.js
runtime/src/tests/work-item/work-item-list/comments.spec.js
runtime/src/tests/work-item/work-item-list/displayAndUpdateWorkItemDetails.spec.js
runtime/src/tests/work-item/work-item-list/iteration.spec.js
runtime/src/tests/work-item/work-item-list/labels.spec.js
runtime/src/tests/work-item/work-item-list/linkItem.spec.js
runtime/src/tests/work-item/work-item-list/page-objects/work-item-detail.page.js
runtime/src/tests/work-item/work-item-list/page-objects/work-item-list.page.js
runtime/src/tests/work-item/work-item-list/smokeTest.spec.js
runtime/src/tests/work-item/work-item-list/startcoding.spec.js
runtime/src/tests/work-item/work-item-list/testHelpers.js
runtime/src/tests/work-item/work-item-list/work-item-dynamic-fields.spec.js
runtime/src/tests/work-item/work-item-list/work-item-list.spec.js
src/app/components/work-item-link/work-item-link.component.html

This PR updates the `clickWorkitemTitle` method and depends on https://github.com/fabric8-ui/fabric8-planner/pull/2306.
All the tests (which are modified in this PR) passed when I ran the PR locally.

fix(test): Refactor clickWorkitemTitle method

---

src/app/components/group-types-panel/group-types-panel.component.ts
src/app/components/iteration-list-entry/iteration-list-entry.component.ts
src/app/components/iterations-panel/iterations-panel.component.ts
src/app/components/planner-board/planner-board.component.ts
src/app/components/planner-list/planner-list.component.less
src/app/components/planner-list/planner-list.component.ts
src/app/components/work-item-list-entry/work-item-list-entry.component.html
src/app/components/work-item-list-entry/work-item-list-entry.component.less
src/app/components/work-item-list-entry/work-item-list-entry.component.ts
src/app/models/work-item.ts
src/app/services/group-types.service.ts
src/app/services/work-item.service.ts

Introduce parent information on the list view.
Visual design - https://redhat.invisionapp.com/share/YZDOM6S2R#/screens
Visual design with specs - https://redhat.invisionapp.com/share/YZDOM6S2R#/screens/255484840
Visual design for indentation - https://redhat.invisionapp.com/share/XQDLTAHCY#/screens/260232204

fix(list view): Introduce parent details in the list view.

---

src/app/components/iterations-panel/iterations-panel.component.html
src/app/components/iterations-panel/iterations-panel.component.ts

Display Close option in the iteration's kebab menu, only if the iteration is an active one. Fixes [OSIO-1615](https://openshift.io/openshiftio/openshiftio/plan/detail/1615)

fix(iteration panel): display close option in kebab menu only for active iterations

---

src/app/components/planner-list/planner-list.component.ts

Issue:
- Whenever a new label is applied to a workitem it's parent information disappears
- on Workitem update workitems child information disappears
This PR resolves these two issues

Resolves: Parent information for a work item disappears

---

docker-compose.f8ui.yml
scripts/bootstrap.sh

Integration build with upstream source(s):
```bash
cd /path/to/planner/repo
./scripts/bootstrap.sh
```
Integration build with local source(s):
```bash
bootstrap.sh --planner=/full/path/to/planner --platform=/full/path/to/platform
```
To ignore builds and dry-run the orchestration, use `--dryrun` flag:
```bash
bootstrap.sh --dryrun
```
N.B: depends on fabric8-ui/fabric8-ui#2178 to function.

feat(deploy): run f8ui integrated planner on docker compose stack

---

src/app/components/iteration-list-entry/iteration-list-entry.component.ts
src/app/components/planner-list/planner-list.component.ts

Fixes 
1. [OSIO 1698](https://openshift.io/openshiftio/openshiftio/plan/detail/1698) - Remove duplicate child work items returned as part of root response
2. [OSIO 1699](https://openshift.io/openshiftio/openshiftio/plan/detail/1699) - Remove work item type filtering for iterations
Change in behaviour introduced by this PR
1. All work item types can now be seen under an iteration. We don't have to use iteration labels.
2. Duplicate responses have been removed from the tree. A child appeared at the root level and the expanded table. The child appears only under the parent.

fix(iterations): Display all work item types for an iteration without duplicates. 

---

src/app/components/planner-list/planner-list.component.less

This PR allow drag and drop to change order of execution at the root level only.
Does not address drag and drop within the tree.

fix(tree-view): Fix drag and drop for re-ordering work items in the list vew.

---

src/app/components/work-item-link/work-item-link.component.ts

Display toast notification to indicate that a work item can have a single parent.
Fixes [1609](https://openshift.io/openshiftio/openshiftio/plan/detail/1609)

fix(work-item-links): Display toast notification to indicate that a work item can have a single parent.

---

src/app/components/planner-board/planner-board.module.ts
src/app/components/planner-list/planner-list.module.ts

This is breaking notifications on the platform because it's created a second service (and events can't be delivered to any  listening component once these modules have been loaded).

fix(broadcaster): remove broadcaster from provider list

---

.gitignore
Dockerfile
deploy/release.groovy
docs/technology_stack.adoc
runtime/package.json
runtime/src/tests/work-item/work-item-list/page-objects/work-item-list.page.js
runtime/tests/docker-entrypoint.sh
runtime/tests/lib/common.inc.sh
runtime/tests/protractor.config.js
runtime/tests/run_functional_tests.sh
scripts/run-functests.sh

We can now run tests against chrome in headless mode. We no longer need to install xvfb and start a virtual display to run the tests.
This PR depends on https://github.com/fabric8-ui/fabric8-planner/pull/2369

fix(CI/CD): Run functional tests in chrome headless mode instead of using xvfb

---

deploy/release.groovy

This reverts commit 6add572a0028c0a964d0ac17f0977708bd20f915.
We no longer require this commit and so the revert.

Revert "fix(CI/CD): Include tests/*.log files in jenkins artifacts"

---

runtime/src/tests/work-item/work-item-list/page-objects/work-item-list.page.js
runtime/src/tests/work-item/work-item-list/smokeTest.spec.js
src/app/components/labels/labels.component.html
src/app/components/planner-list/planner-list.component.html
src/app/components/planner-list/planner-list.component.less
src/app/components/planner-list/planner-list.component.ts
src/app/components/work-item-cell/work-item-cell.component.html
src/app/components/work-item-quick-add/work-item-quick-add.component.html
src/app/components/work-item-quick-add/work-item-quick-add.component.ts

This PR introduces these Changes
- Move bottom QuickAdd to Top
- fix: opens two quickAdd simultaneously
- fix CSS for labels and each row-cell

Planner-datatable:  move bottom quickAdd to top

---

src/app/components/work-item-quick-add/work-item-quick-add.component.html

OSIO issue [1808](https://openshift.io/openshiftio/openshiftio/plan/detail/1808)
fix:
Dropdown items in quick add are visible now

fix(quickAdd): dropdown items are visible

---

src/app/components/planner-board/planner-board.component.ts
src/app/components/planner-list/planner-list.component.ts
src/app/components/toolbar-panel/toolbar-panel.component.ts
src/app/services/filter.service.ts

Consistent URL patterns for queries [OSIO-1780](https://openshift.io/openshiftio/openshiftio/plan/detail/1780)
On the current UI, when we apply filters via the drop down menu, the URL looks like https://openshift.io/openshiftio/openshiftio/plan?q=(space:020f756e-b51a-4b43-b113-45cec16b9ce9%20$AND%20$WITGROUP:Scenarios)&assignee=nmukherj%20(me)
assignee is appended outside the ().
With this story, we would get something like https://openshift.io/openshiftio/openshiftio/plan?q=(space:020f756e-b51a-4b43-b113-45cec16b9ce9%20$AND%20$WITGROUP:Scenarios%20$AND%20assignee=nmukherj)

fix(url-pattern): Introduces consistent url patterns for queries (OSIO-1780)

---

src/app/components/planner-list/planner-list.component.ts

Remove the Empty State icon from the Planner list, per https://github.com/fabric8-ui/fabric8-ux/issues/849

fix(emptystate): remove Empty State icon

---

gulpfile.js
package.json

Closes #2460 
Assuming, the issue was being persistent because of npm force cleaning up `dist` if the `release` subtask was part of `build` task. So, moved `release` out to it's own task. Hopefully this resolves the issue.

fix(CI/CD): separate out release from build step

---

runtime/src/tests/work-item/work-item-list/workItemTypeGroup.spec.js
src/app/components/group-types-panel/group-types-panel.component.ts
src/app/components/iteration-list-entry/iteration-list-entry.component.ts
src/app/components/iterations-panel/iterations-panel.component.ts
src/app/components/planner-list/planner-list.component.ts
src/app/components/toolbar-panel/toolbar-panel.component.ts
src/app/components_ngrx/group-types-panel/group-types-panel.component.ts
src/app/components_ngrx/iteration-list-entry/iteration-list-entry.component.ts
src/app/components_ngrx/iterations-panel/iterations-panel.component.ts
src/app/components_ngrx/planner-list/planner-list.component.ts
src/app/services/filter.service.ts
src/app/services/work-item.service.ts

Once the backend merges this PR: https://github.com/fabric8-services/fabric8-wit/pull/1929, the correct field to ask for when searching for type groups is `typegroup.name` and not `$WITGROUP`.

fix(search): replace with typegroup.name

---

src/app/components_ngrx/toolbar-panel/toolbar-panel.component.html
src/app/components_ngrx/toolbar-panel/toolbar-panel.component.less
src/app/components_ngrx/toolbar-panel/toolbar-panel.component.ts

This PR fixes following issue 
https://github.com/openshiftio/openshift.io/issues/2450
**Feature:** After adding more than one filter it shows an option to clear all filters together.

fix(filter): clear all filter option added to the active filter toolbar

---

.github/pull_request_template.md

Added a new PR template that reminds the PR author to provide minimum information required from documentation and review perspective.

feat(docs):add PR template

---

package.json
runtime/package.json
runtime/src/vendor.ts
src/app/components/iterations-panel/iterations-panel.module.ts
src/app/components/planner-list/planner-list.component.ts
src/app/components/planner-list/planner-list.module.ts
src/app/components/toolbar-panel/toolbar-panel.component.ts
src/app/components/toolbar-panel/toolbar-panel.module.ts
src/app/components_ngrx/iterations-panel/iterations-panel.component.ts
src/app/components_ngrx/iterations-panel/iterations-panel.module.ts
src/app/components_ngrx/planner-list/planner-list.component.ts
src/app/components_ngrx/planner-list/planner-list.module.ts
src/app/components_ngrx/toolbar-panel/toolbar-panel.component.ts
src/app/components_ngrx/toolbar-panel/toolbar-panel.module.ts

- This change takes advantage of patternfly-ng's individual modules so fabric8-planner imports only what’s used in the UI.
- Removes unused patternfly-ng imports referencing ListModule and ActionModule
- Updates patternfly-ng to the latest version, matching the version used by fabric8-ui
https://github.com/openshiftio/openshift.io/issues/2704

patternfly-ng: import individual modules

---

Jenkinsfile

Revert "fix(cicd): Use a development branch from pipeline library (#2513)"
This reverts commit 0abb8469ae114b4c08eec91ce7405f7ad5060aa4.
There is no need to use the branch anymore since we fixed in on master. 
Ref: https://github.com/fabric8io/fabric8-pipeline-library/pull/395

fix(cicd): Use the master version of pipeline library

---

cico_run_tests.sh

This PR fixed the snapshot image tag.
Since there are limitations to what we can show via CICO success comment[0], we need to remove the commit hash from the image tag.
[0] - https://github.com/openshiftio/openshiftio-cico-jobs/blob/master/devtools-ci-index.yaml#L335

CICO: Remove commit hash from snapshot image tag

---

Dockerfile

Chrome installation on CentOS based containers is failing with
```
Package: google-chrome-stable-66.0.3359.117-1.x86_64 (google-chrome)
Requires: libappindicator3.so.1()(64bit)
```
This PR adds `epel-release` and `libappindicator` packages which will fix the error.

fix(CI/CD): Fix failing chrome installation on CentOS

---

src/app/components_ngrx/work-item-detail/work-item-detail.component.ts

fixes: https://github.com/openshiftio/openshift.io/issues/3104
This PR removes the `style="overflow: hidden` from the `<body>` when destroying the work-item-detail.component. 
I have included a more lengthy discussion in the referenced issue, with images and gifs.
There are several components in f8-planner that when activated add a style attribute to the <body> in order to hide the scrollbars ([0] for example). In all [1][2][3] but this one case [4] , this is accompanied by a line of code that changes the overflow value from hidden to auto. However, from some basic logging I've found that these ngOnDestroy() methods aren't hit when leaving the planner page, but the …

fix(work-item-detail): remove overflow style on component destroy

---

package.json
runtime/config/webpack.dev.js
runtime/package.json
scripts/run-planner.sh

This PR fixes
https://openshift.io/openshiftio/openshiftio/plan/detail/2277
https://openshift.io/openshiftio/openshiftio/plan/detail/2278
**How to test -**
The runner scipt supports following flags
1. `-r` - This would reinstall everything
2. `-s` - This would start planner in standalone mode (using the runtime)
3. `-p` - Set path to planner directory (requires path argument)
4. `-f` - Set path to platform directory (requires path argument)
**Run the script as**
- `scripts/run-planner.sh -r -s` - if you wish to reinstall planner and run planner in standalone mode
- `scripts/run-planner.sh -r -f /home/User/fabric8-ui` - if you wish to set the platform path. By default, the platform path is assumed to me `Planner_Path/..`
**NOTE** - Integrated mode is the default mode for running planner …

fix(script): Update scripts used to run planner

---

package.json
src/app/effects/infotip.effects.spec.ts

This PR adds the unit tests for infotip effects
https://openshift.io/openshiftio/openshiftio/plan/detail/2331
Yes
**NOTE:** 
jasmine-marbles: https://github.com/synapse-wireless-labs/jasmine-marbles
RxJs testing using marbles: https://github.com/ReactiveX/rxjs/blob/master/doc/marble-testing.md
___

fix(unit-tests): add unit tests for infotip effects

---

src/app/components_ngrx/planner-list/planner-list.component.html
src/app/components_ngrx/planner-list/planner-list.component.ts
src/app/components_ngrx/planner-list/planner-list.module.ts
src/app/widgets/clickout/clickout.directive.ts
src/app/widgets/clickout/clickout.module.ts
src/app/widgets/select-dropdown/select-dropdown.component.html
src/app/widgets/select-dropdown/select-dropdown.component.ts
src/app/widgets/select-dropdown/select-dropdown.module.ts

- added a directive to check for outside click
- use the directive in select-dropdown
- datatable-config dropdown and quick-preview doesn't open simultaneously
https://github.com/openshiftio/openshift.io/issues/3211
Tests  #2596 
___

fix(dropdown): add directive for clicking outside of an element 

---

src/app/actions/user.actions.ts
src/app/components_ngrx/planner-list/planner-list.module.ts
src/app/components_ngrx/work-item-comment-wrapper/work-item-comment-wrapper.component.html
src/app/components_ngrx/work-item-comment-wrapper/work-item-comment-wrapper.component.ts
src/app/components_ngrx/work-item-comment/work-item-comment.component.html
src/app/components_ngrx/work-item-detail/work-item-detail.module.ts
src/app/effects/comment.effects.ts
src/app/effects/index.effects.ts
src/app/effects/user.effects.ts
src/app/models/comment.spec.ts
src/app/models/comment.ts
src/app/models/common.model.spec.ts
src/app/models/common.model.ts
src/app/models/user.ts
src/app/models/work-item.ts
src/app/reducers/index.reducer.ts
src/app/reducers/user.reducer.spec.ts
src/app/reducers/user.reducer.ts
src/app/states/app.state.ts
src/app/states/index.state.ts
src/app/states/user.state.ts

In this PR we have normalized the user data. Now we have a state called `users` under `listPage` which holds the data **not** in a form of an array but a form of a normalized object. 
For example, if previously the data used to look like - 
```
const users = [{
id: '1',
name: 'Sudipta',
add: 'Alpine Eco'
}, {
id: '2',
name: 'Ibrahim',
add: 'Brigade'
}]
```
Now they look like 
```
const users = {
'1': {
id: '1',
name: 'Sudipta',
add: 'Alpine Eco'
},
'2': {
id: '2',
name: 'Ibrahim',
add: 'Brigade'
}
}
```
**What does it solve?**
Now we don't copy the data to resolve it for some other attribute. For example consider `comment`, where `creator` is a relationship that relates to `user`. Previously, after fetching the `comment` we used to resolve the `creator` from the list of `users` and simply …

Data normalisation initial work / demonstration 

---

src/app/components_ngrx/iteration-list-entry/iteration-list-entry.component.html
src/app/components_ngrx/iteration-list-entry/iteration-list-entry.component.less
src/app/components_ngrx/iterations-panel/iterations-panel.component.html
src/app/components_ngrx/iterations-panel/iterations-panel.component.less
src/app/components_ngrx/planner-list/planner-list.module.ts
src/app/components_ngrx/work-item-cell/work-item-cell.component.html

Fixes https://github.com/openshiftio/openshift.io/issues/3613
- Now in the work item list only first 18 characters of the iteration name are displayed and the rest gets 
truncated and the full name is displayed on hover
- Active Iteration name does not break the UI for iteration panel now.

fix(work-item-cell):  Iteration name issue fixed

---

src/app/effects/label.effects.ts
src/app/services/label.service.ts

In this PR the label service does not depend on any space-related data anymore. 
https://github.com/openshiftio/openshift.io/issues/3028
No, this change doesn't require any test at this moment. Tests will be written for the entire service in coming updates.
___

fix(label): createLabel service method is changed to use the URL as arg

---

src/app/components_ngrx/toolbar-panel/toolbar-panel.component.html
src/app/components_ngrx/toolbar-panel/toolbar-panel.component.ts

Fixes https://github.com/openshiftio/openshift.io/issues/3741
Input for custom-query name gets cleared once the query is saved and doesn't show up in the input field of the save custom-query drop-down the next time the save custom-query drop-down is opened.

fix(custom-query) : Input gets cleared after saving custom-query

---

src/app/components_ngrx/planner-list/planner-list.component.ts

Prevent query params after clicking on backlog or plan tab.
https://github.com/openshiftio/openshift.io/issues/3762
No

fix(list): prevent query params after clicking on backlog

---

src/app/components_ngrx/assignee/assignee.component.ts
src/app/components_ngrx/labels/labels.component.ts
src/app/models/label.model.ts
src/app/models/user.ts

We never faced a scenario where the creator won't be a collaborator. Thus there was a slight glitch in the way we handled data for a list of item. If one of the item in the list doesn't resolve the combined observable used to return null or undefined for its nature. Now we are handling this for both users and labels in this PR.
- https://github.com/openshiftio/openshift.io/issues/3822
- https://github.com/openshiftio/openshift.io/issues/3834
This fix should have a test but we can't write tests at this moment because we haven't figured how to write tests for our Query classes (and other ngrx modules) yet. This is a big task pending and we'll be working on it soon. …

Data non-existence in state issue is handled

---

src/app/effects/custom-query.effects.ts
src/app/effects/iteration.effects.ts
src/app/effects/label.effects.ts
src/app/effects/work-item.effects.ts
src/tests/page_objects/planner/planner.page.ts
src/tests/specs/detailPage.spec.ts
src/tests/specs/iteration.spec.ts
src/tests/specs/quickPreview.spec.ts
src/tests/specs/smoke/smokeTest.spec.ts
src/tests/specs/workItemTableTest.spec.ts
src/tests/ui/planner/iteration.ts
src/tests/ui/planner/sidepanel.ts
src/tests/ui/planner/toolbarHeader.ts
src/tests/ui/planner/workitem-quickadd.ts
src/tests/ui/planner/workitem-quickpreview.ts

Suppresses the create and update toast notifications.
Now only error notifications will be shown
https://github.com/openshiftio/openshift.io/issues/1554
___

 fix(toast-notifications): Suppress create and update notifications

---

src/app/models/work-item-type.ts
src/tests/specs/agileTemplate.spec.ts

- Fix: The order of Work Item child-types in the inline Quick Add 
https://openshift.io/openshiftio/Openshift_io/plan/detail/41
YES
___

fix(inlineQuickAdd): Order of Child-Types in WorkItemType Dropown

---

Dockerfile
tests/run_e2e_tests.sh

All builds related to planner are failing.
This PR updates the version of pip used in the containers for API tests and also install the python-devel package.

Fix failing builds

---

.csscomb.json
src/app/components_ngrx/planner-list/datatable-config.ts
src/app/components_ngrx/planner-list/planner-list.component.html
src/app/components_ngrx/planner-list/planner-list.component.less
src/app/components_ngrx/work-item-cell/work-item-cell.component.html
src/app/components_ngrx/work-item-cell/work-item-cell.component.less
src/app/components_ngrx/work-item-detail/work-item-detail.component.less
src/app/components_ngrx/work-item-event/work-item-event.component.html
src/app/components_ngrx/work-item-event/work-item-event.component.less
src/app/services/cookie.service.ts
src/app/widgets/comment-module/comment.component.html
src/tests/specs/iteration.spec.ts
src/tests/specs/workItemTableTest.spec.ts

fix alignments of work item cells
https://github.com/fabric8-ui/fabric8-planner/issues/2522
NA
@rgarg1 @sanbornsen

fix(list-view): fix alignment of work item cells

---

tests/protractor.conf.ts

60 mins is too much for each spec. 
I have reduced the timeout from 60 mins to 3 mins

fix(test): Change spec timeout from 60 mins to 3 mins

---

src/app/components_ngrx/planner-query/planner-query.module.ts
src/app/shared/toggles-api.provider.ts

- Due to some npm dependency issue in `npm link` feature-flag was not working locally when linking fabric8-planner with fabric8-ui, but it was working fine for prod builds on centOS as well as local fabric8-ui with the latest planner@0.53.2. 
- So in this PR fixes this issue by providing `FeatureFlagResolver`and other FeatureFlag related dependencies explicitly. 
- It also provides `FABRIC8_FEATURE_TOGGLES_API_URL` explicitly by using `process.env.FABRIC8_WIT_API_URL` as a factory since toggle service uses `WIT_API_URL` as a proxy. 
- This patch works both locally and with prod builds.
___

fix(query): fix provider dependencies for local env using feature-flag

---

cico_setup.sh
src/app/reducers/iteration-reducer.ts
src/app/services/work-item.service.ts
src/app/services/work-item.snapshot.ts

fabric8-ui contains a postinstall.sh script which will not work inside a container that is running with super user privileges. The postinstall script in fabric8-ui fails with
```
npm WARN lifecycle fabric8-ui@0.0.0-development~postinstall: cannot run in wd %s %s (wd=%s) fabric8-ui@0.0.0-development ./post-install.sh /home/fabric8/fabric8-planner/fabric8-ui
``` 
on cico (docker container).  
Example failure: https://ci.centos.org/view/Devtools/job/devtools-fabric8-planner-f8planner/2065/consoleFull
https://github.com/fabric8-ui/fabric8-ui/pull/3283/ updated fabric8-ui and caused all builds on fabric8-planner to fail.
More information on https://stackoverflow.com/questions/18136746/npm-install-failed-with-cannot-run-in-wd
Also Fixes the Sev-1: …

fix(builds): Add unsafe-perm flag to npm install 

---

src/app/components_ngrx/dynamic-field/dynamic-field.component.html
src/app/components_ngrx/dynamic-field/dynamic-field.component.ts

Fixes https://github.com/openshiftio/openshift.io/issues/3831 and https://github.com/openshiftio/openshift.io/issues/3832#issuecomment-433874194
This PR removes the unnecessary `None` field in the dropdown for enum types. The backend would always send a default value for enum fields.
**Before**
>![](https://user-images.githubusercontent.com/193408/47646579-a1150a00-db74-11e8-8a70-d11de0455014.png)
**Now**
>    ![screenshot from 2018-11-01 17-26-20](https://user-images.githubusercontent.com/12949454/47850477-5a851100-ddfb-11e8-8f82-46d3b47003e5.png)

fix(dynamic-component): Remove None from Enum field values

---

src/app/components_ngrx/toolbar-panel/toolbar-panel.component.ts

A typo was introduced via https://github.com/fabric8-ui/fabric8-planner/pull/2672.
This PR fixes the minor typo.

fix(assignee): Fix typo me1

---

src/app/widgets/inlineinput/inlineinput.component.ts
src/app/widgets/inlineinput/inlineinput.spec.ts

Validate float type input field value
Fixes #4047
https://github.com/openshiftio/openshift.io/issues/4047
test case included
___

fix(inlineinput): float value validation for user input
