public/css/styles.css
src/app/app.module.ts
src/app/in-memory-data.service.ts
src/app/login/login-item.ts
src/app/login/login.component.css
src/app/login/login.component.html
src/app/login/login.component.ts
src/app/login/login.service.ts

Added a login service - #8
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/almighty/almighty-ui/14)

Added login service

---

README.adoc

- updated the section about first time startup.
- fixed formatting.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/almighty/almighty-ui/20)

fixed typos and formatting

---

src/app/work-item/work-item-list/work-item-list.component.css
src/app/work-item/work-item-list/work-item-list.component.html
src/app/work-item/work-item-list/work-item-list.component.ts
src/app/work-item/work-item-quick-add/work-item-quick-add.component.css
src/app/work-item/work-item-quick-add/work-item-quick-add.component.html
src/app/work-item/work-item-quick-add/work-item-quick-add.component.ts

When viewing a list of work items, the top row will be used to quickly add a work item.
When the item name is entered the add button (+) gets enabled. After adding, the list of work items are displayed in reversed order so that the item that was added is displayed at the top.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/almighty/almighty-ui/23)

Quick add a Work Item Type(almighty/almighty-core#99 UI Issue 3).

---

src/app/login/login.component.ts
src/app/login/login.service.ts

Updated port to 8080.
Login validation using token.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/almighty/almighty-ui/26)

Updated Login Service

---

src/app/work-item/work-item-detail/work-item-detail.component.css
src/app/work-item/work-item-detail/work-item-detail.component.html

https://github.com/almighty/almighty-ui/issues/4 - Updated the styling for the work item detail screen
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/almighty/almighty-ui/27)

Updated the styling for the work item detail screen

---

cico_run_tests.sh

In the absence of any tests as such ( ref: https://github.com/almighty/almighty-ui/issues/35 ) this is just a placeholder that can be expanded on down the road. Getting this in allows us to get started on the deploy pipeline.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/almighty/almighty-ui/36)

stub out a ci worker, so we can get started on the deploy pipeline

---

Dockerfile
Dockerfile.centos
docker-compose.yaml
package.json

I will add a description later
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/almighty/almighty-ui/32)

Stuff that needs to be in master for the demo on sept 6th

---

config/webpack.dev.js
config/webpack.prod.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/almighty/almighty-ui/39)

Default to http://demo.api.almighty.io/api/

---

Dockerfile.centos

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/almighty/almighty-ui/54)

drop unneeded commands causing build time issues

---

src/app/board/board.component.html
src/app/shared-component/status-drawer.component.html
src/app/shared-component/status-drawer.component.ts
src/app/work-item/work-item-detail/work-item-detail.component.html
src/app/work-item/work-item-detail/work-item-detail.component.ts
src/app/work-item/work-item-list/work-item-list.component.html
src/app/work-item/work-item-quick-add/work-item-quick-add.component.html
src/app/work-item/work-item-quick-add/work-item-quick-add.component.ts
src/app/work-item/work-item.ts

Updates UI to work with new WorkItem backend API
* Support for quick add title & description
* Support for editing of all fields, assignee, creator, type, title, description, state
* Support for 'fa' badges pr type in list
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/almighty/almighty-ui/60)

Update ui workitem api

---

src/app/work-item/work-item-detail/work-item-detail.component.css
src/app/work-item/work-item-detail/work-item-detail.component.html

#6 - trimmed type drop-down text to display Experience, Feature, Userstory, and Bug
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/almighty/almighty-ui/63)

Trimmed type drop-down text to display Experience, Feature, Userstory, and Bug

---

src/app/work-item/work-item-quick-add/work-item-quick-add.component.html
src/app/work-item/work-item-quick-add/work-item-quick-add.component.ts

#16 - Quick add a new work item by entering the name and hitting the enter key.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/almighty/almighty-ui/64)

Quick add a new work item by entering the name and hitting the enter key.

---

src/app/work-item/work-item-detail/work-item-detail.component.ts
src/app/work-item/work-item-list/work-item-list.component.html

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/almighty/almighty-ui/79)

Add ValueProposition & Fundamental WIT support

---

src/app/board/board.component.html
src/app/footer/footer.component.html
src/app/header/header.component.html
src/app/login/login.component.html
src/app/shared-component/status-drawer.component.html
src/app/work-item/work-item-detail/work-item-detail.component.html
src/app/work-item/work-item-list/work-item-list.component.html
src/app/work-item/work-item-quick-add/work-item-quick-add.component.html
src/app/work-item/work-item-search/work-item-search.component.html

Implement Unique ID values for UI Elements
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/almighty/almighty-ui/78)

Implement Unique ID values for UI Elements

---

config/karma-test-shim.js
config/karma.config.js
config/webpack.test.js
karma.conf.js
karma.config.js
package.json

#35 - Unit test framework ready.
* Configurations and dev dependencies added.
* Note: mocha is needed for reporting.
* Note: istanbul is needed for supporting karma-coverage
* Note: Please do not update the version of istanbul-instrumenter-loader (0.2.0)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/almighty/almighty-ui/81)

#35 - Jasmine and Karma UI testing framework. 

---

.gitignore
Dockerfile.builder
README.adoc
cico_build_deploy.sh
cico_run_tests.sh
package.json
protractor.config.js
run_functional_tests.sh
src/tests/work-item/work-item-list/work-item-list.spec.js

Adds the framework for functional tests using Protractor and PhantomJS.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/almighty/almighty-ui/92)

Functional tests using Protractor and PhantomJS

---

src/app/work-item/work-item-list/work-item-list.component.html
src/tests/app.component.spec.js
src/tests/work-item/work-item-list/work-item-list.page.js
src/tests/work-item/work-item-list/work-item-list.spec.js

Added page spec and tests for work list component and app component.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/almighty/almighty-ui/102)

Functional test specs

---

src/app/work-item/work-item.service.spec.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/almighty/almighty-ui/97)

Unit test for Work Item Service added.

---

src/app/work-item/work-item-quick-add/work-item-quick-add.component.html
src/app/work-item/work-item-quick-add/work-item-quick-add.component.spec.ts
src/app/work-item/work-item-quick-add/work-item-quick-add.component.ts

* Neccessary changes made to the template and component as well.
* These changes are related to test, because without this updated
the test wouldn't go well.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/almighty/almighty-ui/98)

Unit testing on Quick Add Component.

---

src/app/work-item/work-item-quick-add/work-item-quick-add.component.html
src/app/work-item/work-item-quick-add/work-item-quick-add.component.ts

* Had to bring back the checkTitle function and the flag
* Angular's default keyupevent handler has slight delay and
that was making the add button visible for a moment.
* This solution works good.

Check title for only white space in quick add component

---

.gitignore
README.adoc
cico_build_deploy.sh
cico_run_tests.sh
run_unit_tests.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/almighty/almighty-ui/106)

Unit test cico builder

---

Dockerfile.builder

Fixed #136, unreliable keyserver.

---

config/karma.config.js
src/app/work-item/work-item-detail/work-item-detail.component.html
src/app/work-item/work-item-detail/work-item-detail.component.spec.ts

Reference #35  - Add test cases for viewing a work item's details.
PR https://github.com/almighty/almighty-ui/pull/143 needs to be merged before this PR as it fixes a bug.

Add test cases for the work item's view details component

---

src/app/app.module.ts
src/app/shared-component/dialog/dialog.component.html
src/app/shared-component/dialog/dialog.component.scss
src/app/shared-component/dialog/dialog.component.spec.ts
src/app/shared-component/dialog/dialog.component.ts
src/app/shared-component/dialog/dialog.ts
src/app/work-item/work-item-list/work-item-list.component.html
src/app/work-item/work-item-list/work-item-list.component.ts

Common dialogue component which can be used across various screen.
The dialog component needs to be supplied with: title, message, and actionButtons
**Sample**
this.dialog = {
"title":"Confirm deletetion of Work Item",
"message":"Are you sure you want to delete Work Item - " + workItem.fields["system.title"] + " ?",
"actionButtons" : [
{'title':"Delete","value":1},
{'title':"Don't Delete","value":0}]
};

Add a common dialog component (#127)

---

src/app/footer/footer.component.html
src/app/header/header.component.html
src/app/work-item/work-item-list/work-item-list.component.html
src/app/work-item/work-item-list/work-item-list.component.scss
src/app/work-item/work-item-quick-add/work-item-quick-add.component.html
src/app/work-item/work-item-quick-add/work-item-quick-add.component.scss
src/app/work-item/work-item-quick-add/work-item-quick-add.component.spec.ts
src/assets/stylesheets/custom.scss
src/assets/stylesheets/navbar.scss

Make List View Responsive

---

src/app/app.module.ts
src/app/work-item/work-item-list-entry/work-item-list-entry.component.html
src/app/work-item/work-item-list-entry/work-item-list-entry.component.scss
src/app/work-item/work-item-list-entry/work-item-list-entry.component.ts
src/app/work-item/work-item-list/work-item-list.component.html
src/app/work-item/work-item-list/work-item-list.component.ts
src/app/work-item/work-item-quick-add/work-item-quick-add.component.ts
src/app/work-item/work-item.service.ts

Externalizes the entry from the wi list. Fixes some wi service issues to get that running.

Listentry as component

---

Dockerfile.deploy

Based on nginx image for Openshift by KB:
https://github.com/kbsingh/openshift-nginx

Move deploy image to nginx

---

.gitignore

Ignores vscode settings for git. Makes it possible to add taskrunner configs locally.

Added ignoring vscode configs to gitignore.

---

src/app/app.module.ts
src/app/pipes/alm-trim.ts
src/app/work-item/work-item-detail/work-item-detail.component.html
src/app/work-item/work-item-detail/work-item-detail.component.scss
src/app/work-item/work-item-detail/work-item-detail.component.spec.ts
src/app/work-item/work-item-detail/work-item-detail.component.ts

Issue reference #140 - Introduce Angular2 forms for work item's view/edit details screen.
Note: 
* On save the form submits
* Introduced a trim pipe
* Updated tests

Introduce Angular2 forms for work item's view/edit details screen (#140)

---

src/app/header/header.component.html
src/app/header/header.component.scss
src/app/header/header.component.ts

Reference issue #120.
Display the logged in user's full name and Avatar as obtained from GitHub.
Note:
We call api/user with the token and receive
{"fullName":"User name","imageURL":"https://avatars.githubusercontent.com/u/xxxxxxx?v=x"}

Display the logged in user's full name and Avatar (image)

---

src/app/footer/footer.component.html
src/app/footer/footer.component.scss
src/app/work-item/work-item-list/work-item-list.component.html
src/app/work-item/work-item-list/work-item-list.component.scss
src/app/work-item/work-item-list/work-item-list.component.ts
src/app/work-item/work-item-quick-add/work-item-quick-add.component.html
src/app/work-item/work-item-quick-add/work-item-quick-add.component.scss
src/app/work-item/work-item-quick-add/work-item-quick-add.component.spec.ts
src/app/work-item/work-item-quick-add/work-item-quick-add.component.ts
src/assets/stylesheets/custom.scss
src/assets/stylesheets/fa-icons.scss
src/assets/stylesheets/variables.scss
src/tests/work-item/work-item-list/work-item-list.page.js
src/tests/work-item/work-item-list/work-item-list.spec.js

Quick Add WorkItem At Bottom

---

src/app/auth/authentication.service.ts
src/app/work-item/work-item.service.ts

* Call all API's with Authorization header

Only set Authorization header if Token exist

---

run_functional_tests.sh

Fix for time-out during functional test execution (#214)

Fix for time-out during functional test execution (#214)

---

src/app/app.component.ts
src/app/app.module.ts
src/app/auth/authentication.service.ts
src/app/header/header.component.html
src/app/header/header.component.scss
src/app/header/header.component.ts
src/app/in-memory-data.service.ts
src/app/login/login.component.html
src/app/login/login.component.ts
src/app/login/login.service.ts
src/app/shared-component/dropdown/dropdown.component.html
src/app/shared-component/dropdown/dropdown.component.ts
src/app/shared/broadcaster.service.ts
src/app/user/user.service.ts
src/app/user/user.ts
src/app/work-item/work-item-detail/work-item-detail.component.html
src/app/work-item/work-item-detail/work-item-detail.component.spec.ts
src/app/work-item/work-item-detail/work-item-detail.component.ts
src/app/work-item/work-item-list-entry/work-item-list-entry.component.html
src/app/work-item/work-item-list-entry/work-item-list-entry.component.ts
src/app/work-item/work-item-list/work-item-list.component.html
src/app/work-item/work-item-list/work-item-list.component.ts
src/app/work-item/work-item.service.spec.ts
src/app/work-item/work-item.service.ts
src/tests/work-item/work-item-list/work-item-list.page.js

Issue reference: #8, #121, #120, and #123 
**Add the Login with GitHub feature.**
* A user can view pages. To add, edit, or delete work items, the user needs to login.
* On login, the user name, as obtained from GitHub will be displayed in the header.
* The user can log out using the Logout option available in the header.

Add the Login with GitHub feature

---

src/tests/work-item/work-item-list/quickadd-workitem.spec.js
src/tests/work-item/work-item-list/work-item-list.page.js

Added Handles for Confirm delete/cancel button
Click on "Add quick workitem" as per new layout
New spec file to test quick add related tests (quickadd-workitem.spec.js)

Added page object functions for new quick add layout

---

package.json
src/app/app.module.ts
src/app/header/header.component.html
src/app/header/header.component.scss

- Added a new dropdown library
- Added a dropdown with a user icon on header fro mobile view
This PR will need a package reinstall. 
```
npm run reinstall
```

Logout and login option in mobile view

---

src/app/in-memory-data.service.ts
src/app/work-item/work-item-detail/work-item-detail.component.html
src/app/work-item/work-item-detail/work-item-detail.component.spec.ts
src/app/work-item/work-item-detail/work-item-detail.component.ts
src/app/work-item/work-item-list/work-item-list.component.ts
src/app/work-item/work-item-type.ts
src/app/work-item/work-item.service.ts

Git Issue Reference : #124 
Add fetching of work item types from core.
We use GET on api/workitemtypes

Add fetching of work item types from core (#124)

---

src/app/work-item/work-item-list/work-item-detail/work-item-detail.component.html

Add IDs to the HTML elements for assignee (281)

Add IDs to the HTML elements for assignee (281)

---

src/app/work-item/work-item-list/work-item-list.component.html
src/app/work-item/work-item-list/work-item-list.component.scss

The list page is non-scrollable if the detail page active in mobile

---

package.json
src/app/board/board.component.html
src/app/board/board.component.scss
src/app/board/board.component.ts
src/app/board/board.module.ts

Implemented Initial version of board

---

src/app/work-item/work-item-list/work-item-detail/work-item-detail.component.html
src/app/work-item/work-item-list/work-item-detail/work-item-detail.component.scss
src/tests/work-item/work-item-list/displayAndUpdateWorkItemDetails.spec.js
src/tests/work-item/work-item-list/work-item-detail.page.js

Fix title edit icon persistence (#311)

Fix title edit icon persistence (#311)

---

protractor.config.js
src/tests/work-item/work-item-list/displayAndUpdateWorkItemDetails.spec.js
src/tests/work-item/work-item-list/quickadd-workitem.spec.js
src/tests/work-item/work-item-list/work-item-detail.page.js

-Verify how many work item type exists in drop down phone/desktop
-Verify the name display of workitem types are correct
-Verfify on selecting workitem it should display in list and detail view both pages phone/desktop

Functional tests WI-Type for details page dropdown

---

src/tests/work-item/work-item-list/displayAndUpdateWorkItemDetails.spec.js
src/tests/work-item/work-item-list/work-item-detail.page.js

Added test cases For detail page  …
- Edit with blank title - Mobile/Desktop Should show validation message
- Edit title and description by hitting Enter key Mobile/Desktop

Updating detail viewcases

---

src/app/work-item/work-item-list/work-item-detail/work-item-detail.component.scss

User assignee css issues fixed

---

src/tests/work-item/work-item-list/displayAndUpdateWorkItemDetails.spec.js
src/tests/work-item/work-item-list/work-item-detail.page.js

Functional tests for WI States dropdown UI
- Verify how many state changes exists in drop down Mobile/Desktop
- Verify the name display of workitem state are correct Mobile/Desktop
- Verfify on selecting workitem state it should display in list and detail view both pages Mobile/Desktop

Functional tests for WI states.

---

src/app/work-item/work-item-list/work-item-detail/work-item-detail.component.html

- This is specifically for the details page
- Added ID to the dropdown <ul> sectoin for test
- (fixes-#329)

All the dropdowns in readonly if not logged in

---

src/app/work-item/work-item-list/work-item-detail/work-item-detail.component.html

Html tag in title description bug fixed

---

src/app/work-item/work-item-list/work-item-list-entry/work-item-list-entry.component.html
src/app/work-item/work-item-list/work-item-list-entry/work-item-list-entry.component.scss
src/tests/work-item/work-item-list/displayAndUpdateWorkItemDetails.spec.js
src/tests/work-item/work-item-list/displayWorkItemList.spec.js
src/tests/work-item/work-item-list/work-item-list.spec.js

Hide description field from list entry in desktop view too

Hide description field from list entry in desktop view

---

src/app/work-item/work-item-list/work-item-detail/work-item-link/search-data.ts
src/app/work-item/work-item-list/work-item-detail/work-item-link/work-item-link.component.ts

Fixes https://github.com/almighty/almighty-ui/issues/394

Added workitemtype to search api

---

src/app/work-item/work-item-quick-add/work-item-quick-add.component.ts

Adding event to focus on quick add title on open

---

src/app/app.component.html
src/app/app.component.scss
src/app/board/board.component.html
src/app/board/board.component.scss
src/app/header/header.component.html
src/app/header/header.component.scss
src/app/login/login.component.scss
src/app/notifications/notifications.component.html
src/app/shared-component/dropdown/dropdown.component.scss
src/app/work-item/work-item-list/work-item-detail/work-item-detail.component.html
src/app/work-item/work-item-list/work-item-detail/work-item-detail.component.scss
src/app/work-item/work-item-list/work-item-detail/work-item-link/work-item-link.component.scss
src/app/work-item/work-item-list/work-item-list-entry/work-item-list-entry.component.html
src/app/work-item/work-item-list/work-item-list-entry/work-item-list-entry.component.scss
src/app/work-item/work-item-list/work-item-list.component.scss
src/app/work-item/work-item-quick-add/work-item-quick-add.component.scss
src/app/work-item/work-item-search/work-item-search.component.scss
src/assets/stylesheets/custom.scss

Created function which calculate em/rem from px unit.

Convert px unit to rem/em units

---

src/app/work-item/work-item-list/work-item-list-entry/work-item-list-entry.component.html

Removed 'Change status' from list kebab menu

---

src/app/work-item/work-item-list/work-item-detail/work-item-link/work-item-link.component.ts

Hide link group title, if the workitems is not present

Hide Link group title, if there are no links

---

src/app/models/comment.ts
src/app/pipes/alm-avatar-size.pipe.ts
src/app/work-item/work-item-list/work-item-detail/work-item-comment/work-item-comment.component.html
src/app/work-item/work-item-list/work-item-detail/work-item-comment/work-item-comment.component.scss
src/app/work-item/work-item-list/work-item-detail/work-item-comment/work-item-comment.component.ts
src/app/work-item/work-item-list/work-item-detail/work-item-comment/work-item-comment.service.ts
src/app/work-item/work-item-list/work-item-detail/work-item-detail.component.html
src/app/work-item/work-item-list/work-item-detail/work-item-detail.component.spec.ts
src/app/work-item/work-item-list/work-item-detail/work-item-detail.module.ts
src/app/work-item/work-item.service.ts

Create(secured) and List supported.
Attributes: body, created-at, created-by
almighty/almighty-core#348
almighty/almighty-core#349 
Depends on https://github.com/almighty/almighty-core/pull/546

Add simple Comments to Work Item

---

src/app/work-item/work-item-list/work-item-detail/work-item-comment/work-item-comment.component.ts

Preventing default on enter key down event

---

src/app/footer/footer.component.html
src/app/header/header.component.scss
src/app/shared-component/dialog/dialog.component.html
src/app/shared-component/dialog/dialog.component.spec.ts
src/app/shared-component/dialog/dialog.component.ts
src/app/work-item/work-item-list/work-item-detail/work-item-detail.component.html
src/app/work-item/work-item-list/work-item-detail/work-item-detail.component.scss

For Dialog, Transition has been added and overlay has been set to the body. Earlier it was just showing or hiding the dialog box.
fixes  https://github.com/almighty/almighty-ui/issues/402

FIXES: #402 =>Add transition and overlay for Dialog/Modal

---

src/app/shared-component/infinitescroll/infinitescroll.directive.ts
src/app/shared-component/infinitescroll/infinitescroll.module.ts
src/app/work-item/work-item-list/work-item-detail/work-item-detail.component.spec.ts
src/app/work-item/work-item-list/work-item-detail/work-item-detail.component.ts
src/app/work-item/work-item-list/work-item-detail/work-item-link/work-item-link.component.spec.ts
src/app/work-item/work-item-list/work-item-detail/work-item-link/work-item-link.component.ts
src/app/work-item/work-item-list/work-item-list-entry/work-item-list-entry.component.ts
src/app/work-item/work-item-list/work-item-list.component.html
src/app/work-item/work-item-list/work-item-list.component.ts
src/app/work-item/work-item-list/work-item-list.module.ts
src/app/work-item/work-item-quick-add/work-item-quick-add.component.ts
src/app/work-item/work-item.service.spec.ts
src/app/work-item/work-item.service.ts

- Output events to update the list removed from quickadd.
- Output events to update the list removed from wi entry on delete.
- Using reference of the list object all over the places to update the dom.
- Added a new directive for handling infinite scroll event and page size.

Infinite scroll on work item list added

---

src/app/in-memory-data.service.ts
src/app/work-item/work-item-list/work-item-detail/work-item-detail.component.html
src/tests/work-item/work-item-list/assign.spec.js
src/tests/work-item/work-item-list/displayAndUpdateWorkItemDetails.spec.js
src/tests/work-item/work-item-list/work-item-detail.page.js

Functional tests for User assignee feature
Test covered : 
- Test searching user in the assignee drop down
- Test able to click assigne button Icon and Assignee Name
- Test to update the assigned user 
- User can read , update , remove assignee
- User can Cancel assignee 
- User can read , update , remove assignee 
- Test name and avatar are shown up in the drop down

Functional tests for User assignee feature

---

package.json
src/app/work-item/work-item-list/work-item-detail/work-item-link/work-item-link.component.scss
src/index.html

Removed style hardcoding view encapsulation effect

---

src/app/shared-component/dialog/dialog.component.html
src/app/shared-component/dialog/dialog.component.spec.ts
src/app/shared-component/dialog/dialog.component.ts
src/app/shared-component/dialog/dialog.ts
src/app/work-item/work-item-list/work-item-list-entry/work-item-list-entry.component.ts

Default selection for dialog (fixes #258)

---

src/app/board/board.component.html
src/app/board/board.component.scss
src/app/footer/footer.component.html
src/app/header/header.component.scss
src/app/home/home.component.html
src/app/work-item/work-item-list/work-item-detail/work-item-comment/work-item-comment.component.html
src/app/work-item/work-item-list/work-item-detail/work-item-comment/work-item-comment.component.scss
src/app/work-item/work-item-list/work-item-detail/work-item-detail.component.html
src/app/work-item/work-item-list/work-item-detail/work-item-detail.component.scss
src/app/work-item/work-item-list/work-item-detail/work-item-link/work-item-link.component.html
src/app/work-item/work-item-list/work-item-detail/work-item-link/work-item-link.component.scss
src/app/work-item/work-item-list/work-item-list-entry/work-item-list-entry.component.html
src/app/work-item/work-item-list/work-item-list.component.html
src/app/work-item/work-item-list/work-item-list.component.scss
src/app/work-item/work-item-quick-add/work-item-quick-add.component.html
src/app/work-item/work-item-quick-add/work-item-quick-add.component.scss
src/assets/stylesheets/custom.scss

Custom variables have been removed for more usability. Instead of that bootstrap classes has been used
Issue: #404

Remove custom variables and margin

---

src/app/app.module.ts
src/app/dashboard/dashboard-routing.module.ts
src/app/dashboard/dashboard.component.html
src/app/dashboard/dashboard.component.scss
src/app/dashboard/dashboard.component.ts
src/app/dashboard/dashboard.module.ts
src/app/header/header.component.html
src/app/header/header.component.scss
src/app/learn/learn-routing.module.ts
src/app/learn/learn.component.html
src/app/learn/learn.component.scss
src/app/learn/learn.component.ts
src/app/learn/learn.module.ts

Created HTML for submenus comes under Home section for Organisation Dashboard
Fixes: #444

Add submenu for Org Dashboard under Home Menu

---

config/webpack.dev.js
config/webpack.prod.js
package.json
src/app/app.module.ts
src/app/header/header.component.html
src/app/obsidian/obsidian-routing.module.ts
src/app/obsidian/obsidian.module.ts

re opened because of faulty rebase

Obsidian integration

---

src/app/app.component.html
src/app/app.component.scss
src/app/work-item/work-item-list/work-item-list.component.html
src/app/work-item/work-item-list/work-item-list.component.scss

re opened because of faulty rebase

moved toolbar padding to upper level

---

src/app/dashboard/dashboard.component.html
src/app/dashboard/dashboard.component.scss

HTML for Welcome block in Organisation Dashboard
Issue: #447

Create HTML for Welcome block in Organisation Dashboard

---

src/app/shared-component/icon/almicon.directive.ts
src/app/shared-component/icon/iconmap.ts

Planner item icon added (fixes #425)

---

src/app/dashboard/dashboard.component.html
src/app/dashboard/dashboard.component.scss

HTML for Recent Chats Block in Org Dashboard
related to #456

HTML for Recent Chats Block in Org Dashboard

---

src/app/work-item/work-item-list/work-item-list.component.html

remove extra padding from WI List
fixes #464

fixes: remove extra padding from WI List

---

src/app/board/board.component.scss

Remove extra padding from top in board component
Issue: #466

fixes: Remove extra padding from top in board component

---

src/app/dashboard/dashboard.component.html
src/app/dashboard/dashboard.component.scss

Add HTML for Recent Projects Block in Org Dashboard
Relates to #457

Add Recent Projects Block in Org Dashboard

---

src/app/board/board.component.ts
src/app/in-memory-data.service.ts
src/app/models/user.ts
src/app/models/work-item.ts
src/app/work-item/work-item-list/work-item-detail/work-item-detail.component.html
src/app/work-item/work-item-list/work-item-detail/work-item-detail.component.spec.ts
src/app/work-item/work-item-list/work-item-detail/work-item-detail.component.ts
src/app/work-item/work-item-list/work-item-detail/work-item-link/work-item-link.component.html
src/app/work-item/work-item-list/work-item-detail/work-item-link/work-item-link.component.spec.ts
src/app/work-item/work-item-list/work-item-detail/work-item-link/work-item-link.component.ts
src/app/work-item/work-item-list/work-item-list-entry/work-item-list-entry.component.html
src/app/work-item/work-item-list/work-item-list-entry/work-item-list-entry.component.ts
src/app/work-item/work-item-list/work-item-list.component.html
src/app/work-item/work-item-list/work-item-list.component.ts
src/app/work-item/work-item-quick-add/work-item-quick-add.component.html
src/app/work-item/work-item-quick-add/work-item-quick-add.component.spec.ts
src/app/work-item/work-item-quick-add/work-item-quick-add.component.ts
src/app/work-item/work-item.service.spec.ts
src/app/work-item/work-item.service.ts

- All services, components and templates are updated as per the new format.
- Updated the inmemory data as per the new data format.
- Updated the data in spec files for unit test as per the new format.
- fixes #442
Update Core to match API migration - https://github.com/aslakknutsen/almighty-core/tree/workitem_jsonapi

All workitem services / models migrated to json api

---

src/app/dashboard/dashboard.component.html
src/app/dashboard/dashboard.component.scss

Depends on #469  
related to #474 
Create HTML for Resource Usage Block for Org Dashboard

Create Resource Usage Block for Org Dashboard 

---

src/app/header/header.component.ts
src/app/pipes/alm-array-filter.pipe.ts
src/app/shared-component/infinitescroll/infinitescroll.directive.ts
src/app/user/user.service.ts
src/app/work-item/users.resolver.ts
src/app/work-item/work-item-list/work-item-detail/work-item-detail.component.ts
src/app/work-item/work-item-list/work-item-list-routing.module.ts
src/app/work-item/work-item-list/work-item-list.component.html
src/app/work-item/work-item-list/work-item-list.component.scss
src/app/work-item/work-item-list/work-item-list.component.ts
src/app/work-item/work-item-list/work-item-list.module.ts
src/app/work-item/work-item.service.ts

- Added filter UI to the list page
- Added resolver to fetch list of users
- Added resolver to fetch the auth user details
- Removed user service dependency from header
- Updated the algorithm of infinite scroll directive to support list
reload.

Added filter to work item list (fixes #376)

---

src/app/header/header.component.ts
src/app/login/login.component.ts
src/app/models/comment.ts
src/app/models/work-item.ts
src/app/user/user.service.ts
src/app/work-item/work-item-list/work-item-detail/work-item-detail.component.html
src/app/work-item/work-item-list/work-item-detail/work-item-detail.component.spec.ts
src/app/work-item/work-item-list/work-item-detail/work-item-detail.component.ts
src/app/work-item/work-item-list/work-item-list-entry/work-item-list-entry.component.html
src/app/work-item/work-item-list/work-item-list-entry/work-item-list-entry.component.scss
src/app/work-item/work-item-list/work-item-list-routing.module.ts
src/app/work-item/work-item-list/work-item-list.component.ts
src/app/work-item/work-item.service.spec.ts
src/app/work-item/work-item.service.ts

- fixes #386
- Added resolver to fetch user details in details page for assignee

Added assigned user avatar in the wi list

---

src/app/work-item/work-item-list/work-item-detail/work-item-link/search-data.ts

This PR is to migrate the /search API to support the new JSON API format. 
Supporting core PR - https://github.com/almighty/almighty-core/pull/566

Migrating search API to json API format

---

src/app/in-memory-data.service.ts
src/app/models/work-item.ts
src/app/work-item/work-item-list/work-item-detail/work-item-detail.component.spec.ts
src/app/work-item/work-item-list/work-item-detail/work-item-link/work-item-link.component.spec.ts
src/app/work-item/work-item-quick-add/work-item-quick-add.component.spec.ts
src/app/work-item/work-item.service.spec.ts
src/app/work-item/work-item.service.ts

- Moving creator down to relationship
- Updating creator resolver method

Updating work item model as per the API

---

src/app/in-memory-data.service.ts
src/app/models/work-item.ts
src/app/work-item/work-item-list/work-item-detail/work-item-detail.component.html
src/app/work-item/work-item-list/work-item-detail/work-item-detail.component.spec.ts
src/app/work-item/work-item-list/work-item-detail/work-item-detail.component.ts
src/app/work-item/work-item-list/work-item-detail/work-item-link/work-item-link.component.spec.ts
src/app/work-item/work-item-list/work-item-list-entry/work-item-list-entry.component.html
src/app/work-item/work-item-quick-add/work-item-quick-add.component.spec.ts
src/app/work-item/work-item.service.spec.ts
src/app/work-item/work-item.service.ts

- This commit is to support multi-assignee data model update of core.
- This commit does not have UI implementation of multi assignee.
- Updated the corresponding tests (both functional and unit) to support the updated model.
This PR is to support multi-assignee data model update in core PR - https://github.com/almighty/almighty-core/pull/571

Supporintg muilti-assignee data model

---

src/app/work-item/work-item-list/work-item-list.component.ts

- Filter user was coming null instead of the id due to some change of order in the code.
- If logged out 'filer by assigned' to me should not work so added a lame logic there. We'll need proper UX specification.

Filter user bug fixed

---

package.json
src/app/pipes/alm-moment-time.pipe.ts
src/app/work-item/work-item-list/work-item-detail/work-item-detail.component.html
src/app/work-item/work-item-list/work-item-detail/work-item-detail.component.spec.ts
src/app/work-item/work-item-list/work-item-detail/work-item-detail.module.ts

This PR requires you to run 'npm i'.
Fixes #350

Add creat time on detail page (fixes #350).

---

src/tests/work-item/work-item-list/dashboard.spec.js
src/tests/work-item/work-item-list/page-objects/common.page.js
src/tests/work-item/work-item-list/page-objects/dashboard.page.js
src/tests/work-item/work-item-list/page-objects/learn.page.js

Added Dashboard and learn page object model

Added Dashboard and learn page object model

---

src/app/work-item/work-item-list/work-item-list.component.ts
src/app/work-item/work-item.service.ts

- Filter URL param spelling fixed
- Reseting the big list on change in filter

Filter bug fixed

---

src/app/work-item/work-item-list/work-item-detail/work-item-detail.component.html
src/app/work-item/work-item-list/work-item-detail/work-item-detail.component.scss
src/assets/stylesheets/custom.scss

fixes: #514 - Align User Assignee name and create at timestamp in mobile view

fixes:514 - Align User Assignee name and create at timestamp in mobile view

---

src/app/work-item/work-item-list/work-item-detail/work-item-comment/work-item-comment.component.html
src/app/work-item/work-item-list/work-item-detail/work-item-comment/work-item-comment.component.scss

#513 : Ui issue fixed for Username in work Item Comments for mobile view

Fix: Adjust User name and create Timestamp in mobile view

---

package.json
src/app/app.module.ts
src/app/dashboard/dashboard.component.html
src/app/dashboard/dashboard.component.ts
src/app/dashboard/dashboard.module.ts
src/app/project-dialog/project-dialog.component.html
src/app/project-dialog/project-dialog.component.scss
src/app/project-dialog/project-dialog.component.ts

Create HTML for Create Project Modal
#392

HTML for Create Project Modal

---

src/app/work-item/work-item-list/work-item-detail/work-item-detail.component.html
src/app/work-item/work-item-list/work-item-detail/work-item-detail.component.scss
src/app/work-item/work-item-list/work-item-detail/work-item-detail.component.spec.ts

#351 - Display the creator's full name and Git avatar on the details page.
Note: GET identities api is a secure API. When the user is logged out, we do not display the assigned user and the creator. Is this the right behaviour?

Display the creator's full name and Git avatar (#351)

---

src/app/app.component.scss
src/app/work-item/work-item-list/work-item-list.component.scss

when user is logged out, padding bottom should be zero to container

fixes: remove padding-bottom when user is logged out

---

src/app/work-item/work-item-list/work-item-detail/work-item-comment/work-item-comment.component.html
src/app/work-item/work-item-list/work-item-detail/work-item-detail.component.html
src/app/work-item/work-item-list/work-item-detail/work-item-detail.component.ts
src/app/work-item/work-item-list/work-item-list.component.html
src/app/work-item/work-item-list/work-item-list.component.scss
src/app/work-item/work-item-list/work-item-list.component.spec.ts
src/app/work-item/work-item-list/work-item-list.component.ts

Add dialogue based creation of work items (#352)
User story - https://github.com/almighty/almighty-core/issues/501
UX - https://redhat.invisionapp.com/share/Y39KFTAE7

Add dialogue based creation of work items (#352)

---

src/app/work-item/work-item-list/work-item-list.component.html
src/app/work-item/work-item-list/work-item-list.component.scss

Display "No filters available" message for a user who has not logged in or has not filters available (#526).

Display "No filters available" message for a user who has not logged in or has not filters available (#526).

---

src/app/work-item/work-item-list/work-item-list-entry/work-item-list-entry.component.html
src/app/work-item/work-item-list/work-item-list-entry/work-item-list-entry.component.scss

Set height and width on list view assignee image to fix #525.

Set height and width on list view assignee image (#525)

---

src/app/work-item/work-item-list/work-item-detail/work-item-link/work-item-link.component.html
src/app/work-item/work-item-list/work-item-detail/work-item-link/work-item-link.component.scss
src/app/work-item/work-item-list/work-item-detail/work-item-link/work-item-link.component.ts
src/app/work-item/work-item.service.ts
src/assets/stylesheets/custom.scss

- Removed ng2-complete and using search service from work item service.
- Added filter on search items based on existing link and the self item.
- Added filter on search item based on selected link type.

Work item linking search re-worked

---

src/app/work-item/work-item-list/work-item-detail/work-item-comment/work-item-comment.component.html
src/tests/work-item/work-item-list/page-objects/work-item-detail.page.js

Added UI elements POM for comments tests, which includes ID's for few elements with the index values.
These UI elements are generic :)

Added UI elements POM for comments tests

---

src/app/app.component.scss
src/app/header/header.component.html
src/app/header/header.component.scss

fixes: Add spaces between icons and text and make even header height
#549

fixes: Add spaces between icons and text and make even header height

---

src/app/work-item/work-item-list/work-item-detail/work-item-link/work-item-link.component.html

Remove extra padding from WI link List
#551

fix: Remove extra padding from WI link List

---

src/app/pipes/alm-moment-time.pipe.ts
src/app/work-item/work-item-list/work-item-detail/work-item-detail.component.html
src/app/work-item/work-item-list/work-item-detail/work-item-detail.component.scss

-show date if workitem is created at more then 1 month ago.

Place create time left to close icon. (fixes #524).

---

src/app/pipes/alm-valid-link-types.pipe.ts
src/app/work-item/work-item-list/work-item-detail/work-item-link/work-item-link.component.html

- Re arrange the pipe inputs to keep the variable in main and constant as regular input.
- fixes #555

Updating link type list on change wi type

---

src/app/work-item/work-item-list/work-item-detail/work-item-detail.component.html
src/tests/work-item/work-item-list/page-objects/work-item-detail.page.js

- Added id for created_at time , to track the element from the html page
- Added element method in detailed view page .

Added Page object model for created at time for work item element

---

src/app/work-item/work-item-list/work-item-detail/work-item-detail.component.html
src/tests/work-item/work-item-list/page-objects/work-item-detail.page.js

- Added Id's for creator elements such and icon, username , label
- Added generic methods in detail view page  
Related to task :  https://github.com/almighty/almighty-ui/issues/564

Added page object model for creator

---

src/app/app.module.ts
src/app/work-item/work-item-list/work-item-list.component.html
src/app/work-item/work-item-list/work-item-list.module.ts

On hover Add Tooltip for Add WI Action Button
#544

Add Tooltip on  hover for Add WI Action Button

---

src/app/shared-component/dialog/dialog.component.scss

fix: Add hover colour on confirm button in delete WI modal
#571

fix: Add hover colour on confirm button in delete WI modal

---

src/app/work-item/work-item-list/work-item-list.component.html
src/app/work-item/work-item-list/work-item-list.component.scss

Precise HTML SCSS for select type for Add Work Item Overlay Page
#574

Precise HTML SCSS for select type for Add Work Item Overlay Page

---

src/app/work-item/work-item-list/work-item-list.component.html

Hiding Add work item icon for unauthorized user

---

src/app/work-item/work-item.service.ts

Duplicate entry on list due to direct detail page access is handled

---

src/app/work-item/work-item-list/work-item-detail/work-item-detail.component.scss

Allow editing of text on Firefox, when adding new work item via the dialog box (#538).
Added minimum height for the title box.

Allow editing of text on Firefox, when adding new work item via the dialog box (#538)

---

src/app/work-item/work-item-list/work-item-detail/work-item-detail-pipes/work-item-link-filters.pipe.ts
src/app/work-item/work-item-list/work-item-detail/work-item-detail.component.spec.ts
src/app/work-item/work-item-list/work-item-detail/work-item-detail.module.ts
src/app/work-item/work-item-list/work-item-detail/work-item-link/work-item-link.component.html
src/app/work-item/work-item-list/work-item-detail/work-item-link/work-item-link.component.scss
src/app/work-item/work-item-list/work-item-detail/work-item-link/work-item-link.component.ts

- fixes #583
- fixes #586
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/almighty/almighty-ui/607)

Work item link tabs fixed

---

src/app/pipes/alm-user-name.pipe.ts
src/app/work-item/work-item-list/work-item-detail/work-item-detail.component.html
src/app/work-item/work-item-list/work-item-detail/work-item-detail.component.spec.ts
src/app/work-item/work-item-list/work-item-detail/work-item-detail.module.ts

- This pipe will handle the display of user name all over the templates
- fixes #602

Username pipe implemented

---

src/app/app.module.ts

Add ObsidianModule back to the app.module 

---

src/app/shared/mock-data.service.ts
src/tests/work-item/work-item-list/page-objects/work-item-detail.page.js
src/tests/work-item/work-item-list/page-objects/work-item-list.page.js
src/tests/work-item/work-item-list/work-item-detailed-dialog.spec.js

Tests covered : 
- Creator read only test
- On creating a work item creator should reflect 
- Creator image should be visble on creating work item (verification step)
Added user0 in the mock data , because of WI to reflect some user .

Tests for creator detail view page

---

src/app/work-item/work-item-list/work-item-detail/work-item-detail.component.scss

Bug: Fix line height for WI Title in detail page
#604

Bug: Fix line height for WI Title in detail page

---

package.json

Just a simple update to the package.json due to the move to Fabric8

Update the package name and url to reflect the new location

---

src/app/work-item/work-item-list/work-item-detail/work-item-comment/work-item-comment.component.html
src/app/work-item/work-item-list/work-item-detail/work-item-comment/work-item-comment.component.scss
src/app/work-item/work-item-list/work-item-list-entry/work-item-list-entry.component.scss
src/assets/stylesheets/custom.scss

Bug: Fix User Avatar Image Size for all occurrences by making it common class
#624

Bug: Fix User Avatar Image Size for all occurrences

---

src/app/work-item/work-item.service.ts

Check with filter before adding an item to the list

---

src/app/work-item/work-item-list/work-item-detail/work-item-detail.component.html
src/app/work-item/work-item-list/work-item-detail/work-item-detail.component.ts

Find out the discussions in #594

Uses the new WI flag to prevent 2xTitle while saving, fixes #594

---

src/app/work-item/work-item-list/work-item-detail/work-item-comment/work-item-comment.component.html
src/app/work-item/work-item-list/work-item-detail/work-item-detail.component.html
src/app/work-item/work-item-list/work-item-detail/work-item-detail.component.spec.ts
src/app/work-item/work-item-list/work-item-detail/work-item-detail.module.ts
src/app/work-item/work-item-list/work-item-list-entry/work-item-list-entry.component.html
src/app/work-item/work-item-list/work-item-list.component.spec.ts

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/almighty/almighty-ui/599)

Adds title on the user images to show corresponding names, fixes #494

---

src/app/shared/mock-data/schema-mock-generator.ts
src/app/shared/mock-data/work-item-mock-generator.ts
src/tests/work-item/work-item-list/displayAndUpdateWorkItemDetails.spec.js
src/tests/work-item/work-item-list/page-objects/work-item-list.page.js
src/tests/work-item/work-item-list/work-item-timeStamp.spec.js

Added tests for time displayed on detail page 
- Added a function which create mock time
- Automated tests for mobile/ desktop to check date is displaying as expected

Added test for creation date workitems

---

.gitignore
README.adoc
gulpfile.js
package.json
src-library/components.d.ts
src-library/components.js
tsconfig.json
webpack.config.js

Planner as an NPM library package

Planner as an NPM library package

---

src/app/work-item/work-item-list/work-item-detail/work-item-link/work-item-link.component.html
src/app/work-item/work-item-list/work-item-detail/work-item-link/work-item-link.component.scss

fix UI for Work Item Linking Navigation
#512

BUG: fix UI for Work Item Linking Navigation

---

src/app/work-item/work-item-board/work-item-board.component.html
src/app/work-item/work-item-board/work-item-board.component.scss
src/app/work-item/work-item-board/work-item-board.component.ts
src/app/work-item/work-item-list/work-item-detail/work-item-detail.component.html
src/app/work-item/work-item-list/work-item-detail/work-item-detail.component.scss
src/app/work-item/work-item-list/work-item-detail/work-item-detail.component.ts
src/app/work-item/work-item-list/work-item-list.component.html
src/app/work-item/work-item-list/work-item-list.component.scss
src/app/work-item/work-item-list/work-item-list.component.ts

- Moved the details slider panel animation and css classes from list view and board view to details view.

Making wi details module independent

---

src/app/work-item/work-item-list/work-item-detail/work-item-detail.component.html

Remove Created field when adding a new work item using the dialogue box #643

Remove Created field when adding a new work item using the dialogue box (#643)

---

tsconfig.json

This should fix the build problems.

Fixed excludes for build process.

---

src/app/app.component.ts
src/app/work-item/work-item-board/work-item-board.component.html
src/app/work-item/work-item-board/work-item-board.component.scss
src/app/work-item/work-item-board/work-item-board.module.ts
src/app/work-item/work-item-list/work-item-list.component.html
src/app/work-item/work-item-quick-add/work-item-quick-add.component.html
src/app/work-item/work-item-quick-add/work-item-quick-add.component.scss
src/app/work-item/work-item-quick-add/work-item-quick-add.component.ts

Integrate Quick Add Work Item in Board View #582

Integrate Quick Add Work Item in Board View

---

src/app/work-item/work-item-list/work-item-detail/work-item-comment/work-item-comment.component.html

Reverse chronological ordering of comments, fixes #723

---

src/app/work-item/work-item-list/work-item-list.component.ts

Rename filter method "Assign to Me" to "Assigned to me"

---

src/app/shared/mock-data/schema-mock-generator.ts
src/tests/work-item/work-item-list/displayAndUpdateWorkItemDetails.spec.js

Adding "scenario" in workitem type mock generators
This wit is added from core so i have added mock data to match the master UI.

Adding "scenario" in workitem type mock generators

---

src/app/work-item/work-item-detail/work-item-detail.component.html
src/app/work-item/work-item-detail/work-item-detail.component.scss
src/tests/work-item/work-item-list/displayAndUpdateWorkItemDetails.spec.js
src/tests/work-item/work-item-list/page-objects/work-item-detail.page.js

Disable editing of work item type #635.
The functional tests around work item type on the work item's detail page have been commented out.
@ldimaggi , @naina-verma please review the functional tests that have been disabled (commented out).

Disable editing of work item type (#635)

---

src/app/shared/mock-data/work-item-mock-generator.ts
src/tests/work-item/work-item-list/assign.spec.js
src/tests/work-item/work-item-list/displayAndUpdateWorkItemDetails.spec.js
src/tests/work-item/work-item-list/page-objects/work-item-detail.page.js
src/tests/work-item/work-item-list/page-objects/work-item-list.page.js
src/tests/work-item/work-item-list/quickadd-workitem.spec.js
src/tests/work-item/work-item-list/unauthorizeduser.spec.js
src/tests/work-item/work-item-list/work-item-timeStamp.spec.js

Test covered 
- Verify that workitems cannot be assigned to non-existent users
- Verify that the title field must not be unique
- Verify that the description field can have its contents deleted
- Check before while adding description the field should not display “undefine/null’
- Verify the HTML tags should be treated as text while writing description/title.
- Test description/title can be in other languages also acceptable
- Verify that all fields are read-only for these users 
- Verify that data is persisted and is not truncated if text fields receive data with a length greater that 255 characters.
- Verify visual display of data with a length greater that 255 characters.
- Verify if the date/time is in future it should say “in X time “

Few negative cases covered for previous features

---

src/app/work-item/work-item.component.html
src/app/work-item/work-item.component.scss
src/app/work-item/work-item.component.ts
src/app/work-item/work-item.module.ts
src/assets/stylesheets/color-variables.scss

Fixes: https://github.com/fabric8io/fabric8-planner/issues/752
UX - https://redhat.invisionapp.com/share/FR9R8G6B9#/screens/211643008

Layout for list of iteration

---

src/app/work-item/work-item-list/work-item-list-entry/work-item-list-entry.component.scss
src/tests/work-item/work-item-list/page-objects/work-item-list.page.js

bug fix: input checkbox should only be visible at hover
#684 
Screenshot:

bug fix: input checkbox should be visible at hover

---

src/app/iteration/iteration.component.html
src/app/iteration/iteration.module.ts

Fix: https://github.com/fabric8io/fabric8-planner/issues/720

Create modal to input title description for an iteration.

---

src/app/shared/mock-data/work-item-mock-generator.ts

Added Creator in mock data
For already created WI's we need Creator to be assigned , so added that !

Added Creator in mock data

---

src/app/iteration/iteration.component.html
src/app/iteration/iteration.component.ts
src/app/iteration/iteration.module.ts
src/app/iteration/iteration.service.ts
src/app/models/iteration.model.ts

For now it fetches the list of spaces and work with the first space in the list. Once we implement the shared service or anything similar to fetch the default space this temporary code for fetching spaces will be removed.
Space and iteration need to be created from the backend or using the API to test this feature.

Fetching and listing iteration (fixes #708)

---

src/app/iteration/iteration-modal/iteration-modal.component.html
src/app/iteration/iteration-modal/iteration-modal.component.scss
src/app/iteration/iteration-modal/iteration-modal.component.ts
src/app/iteration/iteration.component.html
src/app/iteration/iteration.component.scss
src/app/iteration/iteration.component.ts
src/app/iteration/iteration.module.ts
src/app/iteration/iteration.service.ts
src/app/models/iteration.model.ts

Separating create iteration modal from main iteration component.

---

cico_build_deploy.sh
cico_run_tests.sh

- This is temporary till we have a better way to write functional tests.

Removing functional test from build process

---

src/app/iteration/iteration-modal/iteration-modal.component.html
src/app/iteration/iteration.component.html
src/tests/work-item/work-item-list/iteration.spec.js
src/tests/work-item/work-item-list/page-objects/work-item-list.page.js

Iteration page object model and few test
- Verification of elements are in place 
- Verification set the title and description
- Verify  help box / dialog title is visible

Iteration page object model and few test

---

src/app/app.component.scss
src/app/work-item/work-item.component.html
src/app/work-item/work-item.component.scss
src/assets/stylesheets/custom.scss
src/tests/work-item/work-item-list/page-objects/work-item-list.page.js

#736 
- Match UI for WI type modal
- Match classes for WI action bar as per Patternfly

match UI for WI type modal

---

src/app/work-item/work-item-list/work-item-list-entry/work-item-list-entry.component.html
src/app/work-item/work-item-list/work-item-list-entry/work-item-list-entry.component.ts

This is the visual implementation, the functional implementation will come next up, which will fix #714

Adds WI list view kebab menu item for iteration association, fixes #713

---

src/app/work-item/work-item-detail/work-item-detail.component.html
src/app/work-item/work-item-detail/work-item-detail.component.scss
src/app/work-item/work-item-detail/work-item-detail.component.ts

Added iteration association dropdown menu in WI detail view, fixes #717

---

src/app/work-item/work-item-detail/work-item-detail.component.scss

- Reduce the z-index of detail panel.
Fix: #810

fix overlapped issue of create Iteration modal and workItem detail.

---

src/app/iteration/iteration.component.html

Bug fix: Block unauthorized user from edit/start of iteration.

---

src/app/iteration/iteration.component.html
src/app/iteration/iteration.component.scss

Fix: https://github.com/fabric8io/fabric8-planner/issues/831

Truncate the iteration name (fixes #831)

---

src/app/iteration/iteration-modal/iteration-modal.component.ts

Bug fix: Remove extra 0 from start and end date of iteration.

---

src/app/iteration/iteration-modal/iteration-modal.component.html
src/app/iteration/iteration-modal/iteration-modal.component.scss
src/app/iteration/iteration-modal/iteration-modal.component.ts

Add error message in start iteration modal. (fixes #839)

---

src/app/iteration/iteration-modal/iteration-modal.component.html
src/app/iteration/iteration-modal/iteration-modal.component.scss

fix bug: datepicker distorted in firefox. (fixes #862)

---

src/app/work-item/work-item.component.html
src/app/work-item/work-item.component.scss

Change icon name for WI which includes border itself. Extra styles are removed

change icon name for add a WI and restyle the icon

---

src/app/work-item/work-item-list/work-item-list-entry/work-item-list-entry.component.scss

Remove border from selected Work Item List from List Entry
#873

fix: Remove border from selected Work Item List from List Entry

---

src/app/work-item/work-item-list/work-item-list-entry/work-item-list-entry.component.html
src/app/work-item/work-item-list/work-item-list-entry/work-item-list-entry.component.ts

Prevent highlighting of work item, in the list view, when the kebab menu is clicked. This fixes #683.

Prevent highlighting of work item, in the list view, when the kebab menu is clicked.

---

protractor.config.js
src/tests/work-item/work-item-list/TBD/chat.spec.js
src/tests/work-item/work-item-list/TBD/code.spec.js
src/tests/work-item/work-item-list/TBD/dashboard.spec.js
src/tests/work-item/work-item-list/TBD/home.spec.js
src/tests/work-item/work-item-list/TBD/hypothesis.spec.js
src/tests/work-item/work-item-list/TBD/microservices.spec.js
src/tests/work-item/work-item-list/TBD/notifications.spec.js
src/tests/work-item/work-item-list/TBD/pipeline.spec.js
src/tests/work-item/work-item-list/TBD/settings.spec.js
src/tests/work-item/work-item-list/TBD/test.spec.js
src/tests/work-item/work-item-list/page-objects/common.page.js
src/tests/work-item/work-item-list/page-objects/work-item-list.page.js

This POC for Parallel execution of functional tests
Features : 
- This PR has capability to run functional tests in approximately 3 mins (max) 
- It is for  POC for parallel execution 
How it works 
- This PR does not trigger ./run_fuctinaltest.sh you need to run ./run_funct*.sh file manually, (testing Purpose, so that it will not affect master )
- Moved  those pages which are not implemented say "setting.spec.js , dashboard , pipleline " etc.. to TBD folder .
Will move them into other Suite (future scope)..

POC for Parallel execution of functional tests

---

src/tests/work-item/work-item-list/comments.spec.js
src/tests/work-item/work-item-list/page-objects/work-item-detail.page.js

Added initial tests for comments 
More test will be adding here !! Waiting for Userstory to complete https://github.com/fabric8io/fabric8-planner/issues/653

Added initial tests for comments 

---

src/app/iteration/iteration-modal/iteration-modal.component.html
src/app/iteration/iteration-modal/iteration-modal.component.ts

Bug fix: Block user to select date before start date from update iteration modal.

---

src/assets/stylesheets/variables.scss

Change font path reference from FontAwesome to fontawesome-webfont
#872

fix: Change font path reference from FontAwesome to fontawesome-webfont

---

src/app/auth/authentication.service.ts
src/app/iteration/iteration.service.ts
src/app/user/user.service.ts
src/app/work-item/work-item.service.ts

Any currently any 401 response redirects the user to the login page. 
We still need to find a better practice on UX and UI code as well.

Relogin functionality added

---

src/tests/work-item/work-item-list/smokeTest.spec.js

Adding couple of Smoke tests to check 
- Time in the Detail view 
- Check the WI is deleted !

Adding smoke tests for Date and updated test to delete WI

---

src/app/work-item/work-item-detail/work-item-comment/work-item-comment.component.spec.ts
src/app/work-item/work-item-detail/work-item-detail.component.spec.ts

Adds unit test for comments + some sample tests, fixes #724

---

src/app/iteration/iteration-modal/iteration-modal.component.ts

Block user to change start date of current iteration. fixes #860.

---

src/app/shared/mock-data.service.ts
src/app/shared/mock-data/work-item-mock-generator.ts
src/app/shared/mock-http.ts
src/app/work-item/work-item-detail/work-item-detail.component.ts
src/app/work-item/work-item.service.ts

mock services for search wi and create link 

---

src/app/app.component.html
src/app/app.component.ts
src/app/app.module.ts
src/app/iteration/iteration-modal/iteration-modal.component.ts
src/app/toast-notification/toast-notification.component.html
src/app/toast-notification/toast-notification.component.scss
src/app/toast-notification/toast-notification.component.ts

Add toast notification on start iteration.

---

src/app/shared/mock-data.service.ts
src/app/shared/mock-data/schema-mock-generator.ts
src/app/shared/mock-http.ts
src/app/work-item/work-item-detail/work-item-detail.component.html
src/app/work-item/work-item-detail/work-item-detail.component.scss
src/app/work-item/work-item-detail/work-item-detail.component.spec.ts
src/app/work-item/work-item-detail/work-item-detail.component.ts
src/app/work-item/work-item.service.ts
src/tests/work-item/work-item-list/page-objects/work-item-detail.page.js
src/tests/work-item/work-item-list/smokeTest.spec.js
src/tests/work-item/work-item-list/workitem-naughty-string.spec.js

View toggle feature for work item description is added. In the details page, one can toggle the description view fro Markdown to HTML.

Work item description view toggle added

---

protractor.config.js
run_functional_tests.sh

This PR is related to : https://github.com/fabric8io/fabric8-planner/issues/830
Do not merge this PR it need to evaluate , for now it has SmokeTests will be adding more in to it!
We need to distribute Test cases in parts
- Smoke
- Sanity
- Regression
So that we can reduce the time of functional tests while testing PR's on Build server

POC :: suites configuration for funtional tests 

---

src/app/work-item/work-item-quick-add/work-item-quick-add.component.html
src/app/work-item/work-item-quick-add/work-item-quick-add.component.scss

This PR is for matching the Quick Add of a Work Item to the visual design as given by UXD. The design can be found here: [Visual Design for Quick Add](https://redhat.invisionapp.com/share/DF8ZQ11R7#/196006933_A-000). Specs are given in the design document.

Match Quick Add to Visual Design

---

src/app/iteration/iteration-modal/iteration-modal.component.ts

Bug fix: Fix distorted enddate input field.

---

src/app/work-item/work-item-list/work-item-list-entry/work-item-list-entry.component.scss

fixes the removal of the divider between checkbox and icons when the row is selected

Fix phantom border removal

---

src/app/app.module.ts
src/app/iteration/iteration-modal/iteration-modal.component.ts
src/app/iteration/iteration.component.ts
src/app/iteration/iteration.service.ts
src/app/shared/mock-data.service.ts
src/app/shared/mock-data/iteration-mock-generator.ts
src/app/shared/mock-data/space-mock-generator.ts
src/app/shared/mock-http.ts
src/app/shared/mock-spaces.service.ts
src/app/work-item/common.resolver.ts
src/app/work-item/work-item.service.spec.ts
src/app/work-item/work-item.service.ts
tsconfig.json

**Fix needs to be done later** : Remove all the dependency on iteration resolver.

Spaces mock service

---

protractor.config.js
src/app/work-item/work-item-detail/work-item-link/work-item-link.component.html
src/tests/work-item/work-item-list/linkItem.spec.js
src/tests/work-item/work-item-list/page-objects/work-item-detail.page.js

Link item functional tests
- Create Link item with type Planner to planner 
- Read the created link 
- Update link child and see the link is visible 
- Delete the link from the link item type

Link item functional tests

---

src/app/iteration/iteration.component.html
src/app/iteration/iteration.component.scss
src/app/iteration/iteration.component.ts
src/app/work-item/work-item-list/work-item-list.component.html
src/app/work-item/work-item-list/work-item-list.component.scss
src/app/work-item/work-item-list/work-item-list.component.ts

Clicking an iteration will filter the work items by the selected iteration (#705)
- Selecting Backlog will display work items which are not associated with any iterations
- Selecting an iteration will display work items which are associated with that iteration
- Currently 'Assign to me' stacks on Backlog/Iteration filter

Clicking an iteration will filter the work items by the selected iteration (#705)

---

src/app/work-item/work-item-list/work-item-list.component.scss
src/app/work-item/work-item-quick-add/work-item-quick-add.component.scss

Fix WI Description Layout Scalability in Quick Add
#945

Fix WI Description Layout Scalability in Quick Add

---

src/app/models/work-item.ts
src/app/work-item/work-item-detail/work-item-detail.component.html
src/app/work-item/work-item-detail/work-item-detail.component.scss
src/tests/work-item/work-item-list/iteration.spec.js
src/tests/work-item/work-item-list/page-objects/work-item-detail.page.js

Once the backend passes correct data with the format mentioned in issue https://github.com/fabric8io/fabric8-planner/issues/889, UI will show it up.
To test this patch one can use this backend branch - https://github.com/pranavgore09/almighty-core/tree/iss-889 which has some dummy URL.

Do it button implemented. Fixes #889

---

src/app/work-item/work-item-detail/work-item-comment/work-item-comment.component.html
src/app/work-item/work-item-detail/work-item-comment/work-item-comment.component.spec.ts
src/app/work-item/work-item-detail/work-item-comment/work-item-comment.component.ts
src/app/work-item/work-item-detail/work-item-detail.component.spec.ts
src/app/work-item/work-item.service.ts

Simple implementation of comment editing for the original author of a comment.
- Comments added by the signed up user will be shown as editable text elements
- After editing, on `<Enter>` the comment is updated (`<Shift+Enter` to line-break)
- After updating takes focus off of comment. If focus wasn't reset, comment wasn't updated.

Edit comments, fixes #653

---

src/app/iteration/iteration.component.html
src/app/iteration/iteration.component.scss
src/app/iteration/iteration.component.ts
src/app/side-panel/side-panel.component.html
src/app/side-panel/side-panel.component.scss
src/app/side-panel/side-panel.component.ts
src/app/side-panel/side-panel.module.ts
src/app/work-item/work-item.component.html
src/app/work-item/work-item.component.scss
src/app/work-item/work-item.module.ts
src/assets/stylesheets/custom.scss

Rewrite Iterations with header and scroll bar
- Add Iterations Header and make it collapsable
- Add scrollbar to Iteration content
- Improved styling
#965

Rewrite Iterations with header and scroll bar

---

src/app/iteration/iterations.service.spec.ts

fixes #972 - add missing required field to unit test

---

src/app/iteration/iteration.component.scss
src/app/side-panel/side-panel.component.html
src/app/side-panel/side-panel.component.ts
src/app/side-panel/side-panel.module.ts
src/app/type/type.component.html
src/app/type/type.component.scss
src/app/type/type.component.ts
src/app/type/type.module.ts

Display types filter option on the side panel. Clicking on the type filter will update the work item list.
For now, we have hard coded User Story and Bug work item type.
This is a functional implementation only.

Add hard coded filter by work item type feature (#882 and #658)

---

src/app/header/header.component.html
src/app/header/header.component.ts
src/app/iteration/iteration-modal/iteration-modal.component.ts
src/app/iteration/iteration.component.ts
src/app/iteration/iteration.service.ts
src/app/iteration/iterations.service.spec.ts
src/app/shared/mock-spaces.service.ts
src/app/work-item/common.resolver.ts
src/app/work-item/work-item-detail/work-item-detail.component.ts
src/app/work-item/work-item-list/work-item-list.component.ts
src/app/work-item/work-item.component.ts
src/app/work-item/work-item.service.spec.ts
src/app/work-item/work-item.service.ts
src/tests/work-item/work-item-list/iteration.spec.js
src/tests/work-item/work-item-list/orderOfExecution.spec.js

Planner Story #650

---

src/app/iteration/iteration.component.scss

Add scroll for iterations panel on the side bar (#987)

Add scroll for iterations panel on the side bar (#987)

---

package.json
src/app/shared/mock-data/work-item-mock-generator.ts
src/app/work-item/work-item-detail/work-item-detail.component.html
src/tests/work-item/work-item-list/page-objects/work-item-detail.page.js
src/tests/work-item/work-item-list/startcoding.spec.js

- Verify start coding is visible when code base is present 
- Verify start coding is disable when creating new item
- Try clicking on start coding it should redirect

Tests for Start coding button

---

src/app/iteration/iteration-modal/iteration-modal.component.ts

Fix Bug displaying iteration name in toast notification.

---

cico_build_deploy.sh
local_docker.sh

move to the dev registry that can then be accessed from multiple clusters

move away from the private ci registry

---

src/app/header/header.component.html
src/app/header/header.component.scss
src/app/iteration/iteration.component.html
src/app/iteration/iteration.component.scss
src/app/side-panel/side-panel.component.scss
src/app/work-item/work-item-board/work-item-board.component.scss
src/app/work-item/work-item-board/work-item-board.component.ts
src/app/work-item/work-item-detail/work-item-comment/work-item-comment.component.html
src/app/work-item/work-item-detail/work-item-link/work-item-link.component.html
src/app/work-item/work-item-detail/work-item-link/work-item-link.component.scss
src/app/work-item/work-item-list/work-item-list.component.scss
src/app/work-item/work-item-quick-add/work-item-quick-add.component.html
src/app/work-item/work-item-quick-add/work-item-quick-add.component.scss
src/app/work-item/work-item.component.html
src/app/work-item/work-item.component.scss
src/assets/stylesheets/_custom.scss
src/assets/stylesheets/_layout.scss

Update the html class names as per flex layout
Redo some of the style 
NOTE: Board View is not covered in this commit

Update html class names and redo styles

---

src/app/work-item/work-item-board/work-item-board.component.html
src/app/work-item/work-item-board/work-item-board.component.scss

Update the styles as per flex layout

Fix Styles for Board View

---

src/app/dashboard/dashboard.component.scss
src/app/header/header.component.scss
src/app/learn/learn.component.html

Fix the navigation for dashboard and learn
Fix padding for content

Fix persistant navigation for Home tab

---

config/webpack.test.js
package.json
src/app/iteration/iterations.service.spec.ts
src/app/work-item/work-item.service.spec.ts

Add module dependencies to unit test providers

fix(tests): Fix unit test support in webpack.test.js

---

protractor.config.js
src/app/models/work-item.ts
src/app/shared-component/treelist/treelist.component.html
src/app/shared-component/treelist/treelist.component.scss
src/app/shared-component/treelist/treelist.component.spec.ts
src/app/shared-component/treelist/treelist.component.ts
src/app/shared-component/treelist/treelist.module.ts
src/app/shared/mock-data.service.ts
src/app/shared/mock-data/work-item-mock-generator.ts
src/app/work-item/work-item-list/work-item-list.component.ts
src/app/work-item/work-item.service.ts

Fixes the broken treelist in master.

Treelist Fix

---

src/app/work-item/work-item-detail/work-item-detail.module.ts
src/app/work-item/work-item.module.ts
tsconfig.json

Also removes pipes that are already declared in the WidgetsModule

fix(module): fix work-item modules to include necessary dependencies

---

package.json
src/app/work-item/work-item-list/work-item-list-entry/work-item-list-entry.component.html
src/app/work-item/work-item-list/work-item-list-entry/work-item-list-entry.component.scss
src/app/work-item/work-item-list/work-item-list-entry/work-item-list-entry.component.ts
src/app/work-item/work-item-list/work-item-list.component.html
src/app/work-item/work-item-list/work-item-list.component.ts

Integrated new treelist-item with treelist. Overrode styles best I could (for now), but may be tweaked a bit.

Added treelist-item

---

src/app/work-item/work-item.component.scss
src/app/work-item/work-item.module.ts

Also includes a fix for removing the space service dependency which was unnecessary

fix(styles): Work item children flex display modified

---

src/app/shared/mock-data.service.ts

Removed a line from code which creates duplicate iterations

fix(tests): Mock iteration add

---

src/app/iteration/iteration.component.html
src/app/iteration/iteration.component.scss
src/app/side-panel/side-panel.component.html
src/app/side-panel/side-panel.component.scss
src/tests/work-item/work-item-list/page-objects/work-item-list.page.js

This PR is to update the side panel UI to match the designs from UX.
As part of this work, I noticed that the kabob styling is off, but the fix affects the entire UI (not just those in the side panel). I have left that fix for a future PR.

Side panel uxd

---

package.json
src/app/app.module.ts
src/app/header/header.component.html
src/app/header/header.component.ts
src/app/iteration/iteration-modal/iteration-modal.component.ts
src/app/iteration/iteration.component.ts
src/app/iteration/iteration.service.ts
src/app/iteration/iterations.service.spec.ts
src/app/type/type.component.ts
src/app/work-item/common.resolver.ts
src/app/work-item/work-item-list/work-item-list.component.ts
src/app/work-item/work-item.component.ts
src/app/work-item/work-item.service.ts

Reverts fabric8io/fabric8-planner#1043

Revert "fix(spaces): use spaceChanged"

---

protractor.config.js
src/tests/work-item/work-item-list/assign.spec.js
src/tests/work-item/work-item-list/comments.spec.js
src/tests/work-item/work-item-list/displayAndUpdateWorkItemDetails.spec.js
src/tests/work-item/work-item-list/page-objects/work-item-detail.page.js
src/tests/work-item/work-item-list/page-objects/work-item-list.page.js
src/tests/work-item/work-item-list/quickadd-workitem.spec.js
src/tests/work-item/work-item-list/smokeTest.spec.js
src/tests/work-item/work-item-list/testHelpers.js
src/tests/work-item/work-item-list/testHelpersTestTemplate.spec.js
src/tests/work-item/work-item-list/unauthorizeduser.spec.js
src/tests/work-item/work-item-list/work-item-detailed-dialog.spec.js
src/tests/work-item/work-item-list/work-item-list.spec.js
src/tests/work-item/work-item-list/work-item-timeStamp.spec.js

This PR is related to tests running with chrome browser not PhantomJs
Do not merge now , waiting for chrome browser job on CI!

Fix ui tests with chome browser

---

src/app/work-item/work-item-list/work-item-list.component.html
src/app/work-item/work-item-list/work-item-list.component.scss

- position quick add to the bottom when there is no wi
- remove unused css from the component 
Closes #1044

fix(quick-add-wi): position quick add to the bottom when there is no wi

---

src/app/work-item/work-item.component.html
src/app/work-item/work-item.component.scss

Update filter panel placement as per Visuals
Closes #1046

refactor(filter-panel): update filter panel placement

---

src/app/iteration/iteration.component.html
src/app/iteration/iteration.component.scss
src/app/iteration/iteration.component.ts
src/app/side-panel/side-panel.component.html
src/app/type/type.component.html
src/app/type/type.component.ts

fix side bar scroll behaviour as per wireframe
Closes: #987

refactor(side-panel-scroll): fix side bar scroll behaviour

---

src/app/work-item/work-item-list/work-item-list.component.scss
src/app/work-item/work-item.component.scss
src/assets/stylesheets/_custom.scss
src/assets/stylesheets/_layout.scss
src/assets/stylesheets/_overrides-for-patternfly.scss

Fixes the layout issues with work item component and adds a .view-content class.

work item component Layout style fixes

---

README.adoc

update README doc with inmemory mode

docs(readme.doc):  add inmemory mode

---

src/app/work-item/work-item.component.scss

fix padding in filter panel toolbar
Closes #1061

fix(filter-panel): fix padding in filter panel

---

src/app/app.module.ts
src/app/iteration/iteration.component.html
src/app/iteration/iteration.module.ts
src/app/type/type.module.ts
src/app/work-item/work-item-board/work-item-board.component.html
src/app/work-item/work-item-detail/work-item-comment/work-item-comment.component.spec.ts
src/app/work-item/work-item-detail/work-item-detail.component.html
src/app/work-item/work-item-detail/work-item-detail.component.spec.ts
src/app/work-item/work-item-detail/work-item-detail.module.ts
src/app/work-item/work-item-detail/work-item-link/work-item-link.component.html
src/app/work-item/work-item-iteration-association-modal/work-item-iteration-association-modal.component.html
src/app/work-item/work-item-list/work-item-list-entry/work-item-list-entry.component.html
src/app/work-item/work-item.component.html
src/app/work-item/work-item.module.ts

Modified dropdowns to use ng2-bootstrap for compatibility with ngx-widgets.
FYI, I noticed a couple test failures in master. The tests passed prior to rebasing my branch.

Dropdown to use ng2-bootstrap

---

src/tests/app.component.spec.js

This  ' *?/work-item/list '   has been removed form the code . Now, redirect URL is localhost:8088

fix(tests): Change redirect URL for test

---

src/app/work-item/work-item-board/planner-board.module.ts
src/app/work-item/work-item-board/work-item-board.component.html

Uncomment the quick add component.

fix(board): uncomment quick add in board view.

---

Dockerfile.builder
Dockerfile.deploy

I may have started the docker files but I'm no longer in charge of'em.

Remove me as maintainer from docker files

---

src/app/work-item/work-item-list/work-item-list-entry/work-item-list-entry.component.html

fix(test): delete work item test

---

src/app/models/filter.model.ts
src/app/shared/filter.service.ts
src/app/toolbar-panel/toolbar-panel.component.ts
src/app/toolbar-panel/toolbar-panel.module.ts

feat(filterService): write a service to fetch list of filters from backend

---

protractor.config.js
src/app/shared/mock-data/work-item-mock-generator.ts
src/tests/work-item/work-item-list/displayAndUpdateWorkItemDetails.spec.js

https://github.com/fabric8io/fabric8-planner/issues/1112  
And this has a minor fix of Icon name!
[19:23:39] I/testLogger - 
[19:23:39] I/launcher - 0 instance(s) of WebDriver still running
[19:23:39] I/launcher - chrome #01-0 passed
[19:23:39] I/launcher - chrome #01-2 passed
[19:23:39] I/launcher - chrome #01-3 passed
[19:23:39] I/launcher - chrome #01-5 passed
[19:23:39] I/launcher - chrome #01-6 passed
[19:23:39] I/launcher - chrome #01-7 passed
[19:23:39] I/launcher - chrome #01-8 passed
[19:23:39] I/launcher - chrome #01-1 passed
[19:23:39] I/launcher - chrome #01-11 passed
[19:23:39] I/launcher - chrome #01-10 passed
[19:23:39] I/launcher - chrome #01-13 passed
[19:23:39] I/launcher - chrome #01-9 passed
[19:23:39] I/launcher - chrome #01-12 passed
[19:23:39] I/launcher - chrome …

fix(tests): Mock fix for description placeholder

---

src/app/work-item/work-item-detail/work-item-comment/work-item-comment.component.html
src/app/work-item/work-item-detail/work-item-comment/work-item-comment.component.scss
src/app/work-item/work-item-detail/work-item-comment/work-item-comment.component.ts
src/app/work-item/work-item-detail/work-item-detail.component.scss
src/app/work-item/work-item-detail/work-item-link/work-item-link.component.html
src/app/work-item/work-item-detail/work-item-link/work-item-link.component.scss
src/assets/stylesheets/_custom.scss
src/assets/stylesheets/_layout.scss

update comments ui
Visual Design:  https://redhat.invisionapp.com/share/Q6AAQVO8X
Closes: #1063

refactor(comments): update comments ui

---

package.json

Fixes a problem reported by @debloper on hipchat

fix(fonts): stop fonts loading from wrong path

---

package.json
src/app/app.component.ts
src/app/app.module.ts
src/app/header/header.component.ts
src/app/iteration/iteration.service.ts
src/app/work-item/common.resolver.ts
src/app/work-item/work-item-detail/work-item-comment/work-item-comment.component.spec.ts
src/app/work-item/work-item-detail/work-item-comment/work-item-comment.component.ts
src/app/work-item/work-item-detail/work-item-detail.component.spec.ts
src/app/work-item/work-item-list/work-item-list.component.spec.ts
src/app/work-item/work-item.service.ts

Moves url token handling into the product instead of the shared library

fix(loginclient): update to latest login-client

---

src/app/work-item/work-item-board/work-item-board.component.scss
src/assets/stylesheets/shared/_custom-mixins.scss
src/assets/stylesheets/shared/_overrides-for-patternfly.scss

fix css for board view
- toolbar results css
- multiline truncation
Closes: #1121

fix(board-view): fix styles for board view

---

src/app/work-item/work-item-detail/work-item-comment/work-item-comment.component.html
src/app/work-item/work-item-detail/work-item-comment/work-item-comment.component.scss

- fix comments css 
- remove view more comments
Closes: #1123

fix(comments): fix comments css and remove view more comments

---

config/karma.config.js
src/app/area/area.service.ts
src/app/models/area.model.ts
src/app/models/work-item.ts
src/app/shared/mock-data.service.ts
src/app/shared/mock-data/area-mock-generator.ts
src/app/shared/mock-data/work-item-mock-generator.ts
src/app/work-item/work-item-detail/work-item-comment/work-item-comment.component.spec.ts
src/app/work-item/work-item-detail/work-item-detail.component.html
src/app/work-item/work-item-detail/work-item-detail.component.scss
src/app/work-item/work-item-detail/work-item-detail.component.spec.ts
src/app/work-item/work-item-detail/work-item-detail.component.ts
src/app/work-item/work-item-detail/work-item-detail.module.ts
src/app/work-item/work-item.service.spec.ts
src/app/work-item/work-item.service.ts

feat(areas): Association of work item and an area in the work item detail page (#1014, #1012, #1013)

feat(areas): Association of work item and an area in the work item detail page (#1014)

---

package.json
src/app/work-item/work-item-board/planner-board.module.ts
src/app/work-item/work-item-board/work-item-board.component.html
src/app/work-item/work-item-board/work-item-board.component.scss
src/app/work-item/work-item-board/work-item-board.component.ts
src/app/work-item/work-item-list/planner-list.module.ts
src/app/work-item/work-item-list/work-item-list.component.spec.ts
src/app/work-item/work-item.module.ts
src/assets/stylesheets/_dragula.scss

Add Drag and drop in Board view.

---

package.json
src/app/app.module.ts
src/app/area/area.service.ts
src/app/header/header.component.ts
src/app/iteration/iteration-modal/iteration-modal.component.ts
src/app/iteration/iteration.component.ts
src/app/iteration/iteration.service.ts
src/app/iteration/iterations.service.spec.ts
src/app/shared/standalone/spaces.service.factory.ts
src/app/shared/standalone/spaces.service.ts
src/app/toolbar-panel/toolbar-panel.component.ts
src/app/type/type.component.ts
src/app/work-item/work-item-board/work-item-board.component.ts
src/app/work-item/work-item-detail-add-type-selector/work-item-detail-add-type-selector.component.ts
src/app/work-item/work-item-detail/work-item-comment/work-item-comment.component.spec.ts
src/app/work-item/work-item-detail/work-item-detail.component.spec.ts
src/app/work-item/work-item-detail/work-item-detail.component.ts
src/app/work-item/work-item-list/work-item-list.component.ts
src/app/work-item/work-item-quick-add/work-item-quick-add.component.spec.ts
src/app/work-item/work-item-quick-add/work-item-quick-add.component.ts
src/app/work-item/work-item.component.ts
src/app/work-item/work-item.service.spec.ts
src/app/work-item/work-item.service.ts

DO NOT MERGE YET.
This works for standalone fabric8-planner, but I've not got it integrated to fabric8-ui yet.

fix(spaces): use spaces service

---

src/app/app.module.ts

Planner UI does not display on launch. Added the SpacesService as a provider. 
Pending issue: The details page does not open - need to add areas service mock.

fix(inmemory): Fixes inmemory. The list displays.

---

protractor.config.js
src/tests/work-item/work-item-list/unauthorizeduser.spec.js

- Change phone to Desktop mode
- Click on Logout for unauthorized tests

fix(tests): Clean up of tests

---

src/tests/work-item/work-item-list/quickadd-workitem.spec.js

Minor change to the object model only.

Updated failing test

---

src/app/shared/mock-data/schema-mock-generator.ts
src/tests/work-item/work-item-list/quickadd-workitem.spec.js

Adding mock for area Label

---

protractor.config.js
src/tests/work-item/work-item-list/TBD/fabric8-poc.spec.js
src/tests/work-item/work-item-list/constants.js
src/tests/work-item/work-item-list/page-objects/complete-registration.page.js
src/tests/work-item/work-item-list/page-objects/fabric8-RHD-login.page.js
src/tests/work-item/work-item-list/page-objects/fabric8-main.page.js
src/tests/work-item/work-item-list/page-objects/fabric8-start.page.js
src/tests/work-item/work-item-list/page-objects/github-login.page.js

This test - when finished - and when the UI supports it - will automate the end-to-end user experience.

Initial (and incomplete) POC for testing the Fabric8 UI pages

---

protractor.config.js
src/app/work-item/work-item-detail/work-item-detail.component.html
src/tests/work-item/work-item-list/area.spec.js
src/tests/work-item/work-item-list/page-objects/work-item-detail.page.js

Adding funtional tests for Area's

Adding funtional tests for Area's

---

src/app/work-item/work-item-board/work-item-board.component.ts
src/app/work-item/work-item-list/work-item-list.component.ts

fix(list-board): Host css fix

---

src/app/work-item/work-item-detail/work-item-comment/work-item-comment.component.html
src/tests/work-item/work-item-list/comments.spec.js
src/tests/work-item/work-item-list/page-objects/work-item-detail.page.js

Update comments tests

---

src/app/work-item/work-item-board/work-item-board.component.ts
src/app/work-item/work-item-detail-add-type-selector/work-item-detail-add-type-selector.component.ts
src/app/work-item/work-item-detail/work-item-detail.component.ts
src/app/work-item/work-item-detail/work-item-link/work-item-link.component.ts
src/app/work-item/work-item-list/work-item-list-entry/work-item-list-entry.component.ts
src/app/work-item/work-item.component.ts

* Using navigateByUrl avoids url encoding problems
* Also added trimEnd to remove trailing slashes - this causes a router matching error
* Fixed up a few links as well
Fixes fabric8io/fabric8-ui#274

fix(urls): A number of URL related fixes

---

src/app/work-item/work-item-board/work-item-board.component.html

Fix(Board): Work item type icon for work item.

---

src/app/work-item/work-item-detail/work-item-detail.component.html
src/app/work-item/work-item-detail/work-item-detail.component.ts

Filter area based on type ahead search entry. Fixes #1164.

fix(areas): Filter areas based on type ahead search entry. Fixes #1164.

---

protractor.config.js
src/tests/work-item/work-item-list/board.spec.js
src/tests/work-item/work-item-list/page-objects/work-item-board.page.js
src/tests/work-item/work-item-list/page-objects/work-item-list.page.js

Board View funtional tests

---

protractor.config.js
src/app/work-item/work-item-detail/work-item-detail.component.html
src/app/work-item/work-item-iteration-association-modal/work-item-iteration-association-modal.component.html
src/tests/work-item/work-item-list/iteration.spec.js
src/tests/work-item/work-item-list/page-objects/work-item-detail.page.js
src/tests/work-item/work-item-list/page-objects/work-item-list.page.js

Test associate WI with iteration and Fix area's functional test

Test associate WI with iteration and Fix area's functional test

---

src/app/shared/mock-data/work-item-mock-generator.ts
src/tests/work-item/work-item-list/iteration.spec.js
src/tests/work-item/work-item-list/page-objects/work-item-detail.page.js
src/tests/work-item/work-item-list/page-objects/work-item-list.page.js
src/tests/work-item/work-item-list/quickadd-workitem.spec.js

Multiple changes to clean up code and to add new iteration test (and its supporting code).

Added functional test for iterations

---

src/app/shared/mock-data/schema-mock-generator.ts
src/app/work-item/work-item-detail/work-item-detail.component.html
src/tests/work-item/work-item-list/page-objects/work-item-detail.page.js

https://github.com/fabric8io/fabric8-planner/issues/1226 fix of this issue

test(mock-label): Fix mock label for creator & asign

---

src/app/work-item/work-item-detail/work-item-link/work-item-link.component.html
src/tests/work-item/work-item-list/page-objects/work-item-detail.page.js

There is change in Layout of Link item fixed in this PR

fix(link-item-tests) : Fix link item tests, due to design change

---

README.adoc
scripts/run-integration.sh

For running Planner and Platform in one go.

Adds integration runner script

---

src/app/work-item/work-item-list/work-item-list.component.html
src/app/work-item/work-item-list/work-item-list.component.scss
src/app/work-item/work-item-list/work-item-list.component.ts

This PR contain Order of Execution only by drag and drop.

feat(listview): integrate order of execution api in work item list view.

---

protractor.config.js
src/tests/work-item/work-item-list/EE/openshift-io-poc.spec.js
src/tests/work-item/work-item-list/iteration.spec.js
src/tests/work-item/work-item-list/page-objects/openshift-io-RHD-login.page.js
src/tests/work-item/work-item-list/page-objects/openshift-io-github-login.page.js
src/tests/work-item/work-item-list/page-objects/openshift-io-start.page.js
src/tests/work-item/work-item-list/page-objects/work-item-detail.page.js
src/tests/work-item/work-item-list/work-item-detailed-dialog.spec.js

After this PR, the only tests that are failing are those that run as a non-authorized user - these tests are blocked by a known login bug.
106 specs, 7 failures

Cleaning up tests that were failing on March 21

---

package.json
src/app/work-item/work-item-detail/work-item-detail.component.html
src/app/work-item/work-item-detail/work-item-detail.component.scss
src/app/work-item/work-item-detail/work-item-detail.component.ts

The Description interactions needed to be improved in order to allow users to see the full context of the Description, without scrolling. Additionally, in order to properly show the user that markdown is supported, the correct text needs to be added below the textarea.

feature(UXD): Add Markdown Supported text, update Description interactions

---

src/app/work-item/work-item-detail/work-item-detail.component.scss

fix(detail page): Save icon next to area click-able. Fixes #1234.

fix(detail page): Save icon next to area click-able. Fixes #1234.

---

src/app/app.component.ts
src/app/app.module.ts
src/app/area/area.service.ts
src/app/header/DummySpace.service.ts
src/app/header/header.component.ts
src/app/iteration/iteration-modal/iteration-modal.component.ts
src/app/iteration/iteration.component.ts
src/app/iteration/iteration.service.ts
src/app/iteration/iterations.service.spec.ts
src/app/shared/http-service.ts
src/app/shared/mock-http.ts
src/app/toolbar-panel/toolbar-panel.component.ts
src/app/work-item/work-item-board/planner-board.module.ts
src/app/work-item/work-item-board/work-item-board.component.ts
src/app/work-item/work-item-detail-add-type-selector/work-item-detail-add-type-selector.component.ts
src/app/work-item/work-item-detail/work-item-comment/work-item-comment.component.spec.ts
src/app/work-item/work-item-detail/work-item-comment/work-item-comment.component.ts
src/app/work-item/work-item-detail/work-item-detail.component.spec.ts
src/app/work-item/work-item-detail/work-item-detail.component.ts
src/app/work-item/work-item-detail/work-item-link/work-item-link.component.ts
src/app/work-item/work-item-iteration-association-modal/work-item-iteration-association-modal.component.ts
src/app/work-item/work-item-list/work-item-list-entry/work-item-list-entry.component.ts
src/app/work-item/work-item-list/work-item-list.component.spec.ts
src/app/work-item/work-item-list/work-item-list.component.ts
src/app/work-item/work-item-quick-add/work-item-quick-add.component.spec.ts
src/app/work-item/work-item-quick-add/work-item-quick-add.component.ts
src/app/work-item/work-item.component.ts
src/app/work-item/work-item.service.spec.ts
src/app/work-item/work-item.service.ts

This PR is just to convert all existing promises to observables. 
No extra logic is added here. New logics and benefits of using observables will be added soon.

Converted all promises to observable

---

src/app/work-item/work-item-detail/work-item-detail.component.html
src/app/work-item/work-item-detail/work-item-detail.component.ts

Fix disappearance of work item title in the detail panel when clicked anywhere outside the title field. (#740)

fix(detail-panel): Fix disappearance of work item title in the detail panel when clicked anywhere outside it. (#740)

---

src/app/shared/http-service.ts

fix(http calls): Fix PUT and PATCH calls (#1304 & #1288).
The edit calls were failing as the UI was making a POST call instead of PUT or PATCH.

fix(http calls): Fix PUT and PATCH calls (#1304 & #1288).

---

src/app/toolbar-panel/toolbar-panel.component.html
src/app/work-item/work-item-list/work-item-list-entry/work-item-list-entry.component.html
src/app/work-item/work-item-list/work-item-list.component.ts

fix(list): block unauthorized to reorder the workitem

---

protractor.config.js

Due to this bug https://github.com/fabric8io/fabric8-planner/issues/1296

test(board-spec-remove): remove board spec temporarily

---

src/app/work-item/work-item-list/work-item-list.component.html
src/app/work-item/work-item-list/work-item-list.component.scss

Note that this depends on this ngx-widgets PR:
https://github.com/fabric8-ui/ngx-widgets/pull/51

fix(treelist): Refactored treelist to better mimic dnd mock-ups

---

src/tests/work-item/work-item-list/EE/openshift-io-poc.spec.js
src/tests/work-item/work-item-list/page-objects/openshift-io-dashboard.page.js

- The EE tests failed due to removed line, now its working fine 
- Duplicate lines were the failure root cause

test(cleanup): Clean up EE wrt PR 1364

---

cico_build_deploy.sh
cico_build_deploy_npm.sh
cico_run_tests.sh
protractor.config.js
src/tests/work-item/work-item-list/smokeTest.spec.js

Started
[chrome #01-1] .......................
[chrome #01-1] 
[chrome #01-1] 
[chrome #01-1] 23 specs, 0 failures
[chrome #01-1] Finished in 277.813 seconds
[chrome #01-1] 
[20:22:47] I/testLogger - 
[20:22:47] I/launcher - 0 instance(s) of WebDriver still running
[20:22:47] I/launcher - chrome #01-0 passed
[20:22:47] I/launcher - chrome #01-1 passed
4444/tcp:            30553
8088/tcp:            30591
Functional tests OK

fix(test): Added smoke + minimal tests and Parallel execution.

---

cico_run_tests.sh
local_run_funtional_tests.sh
protractor.config.js
src/tests/work-item/work-item-list/smokeTest.spec.js

Script for the local tests run is added and with few smoke tests

fix(test): Add local functional tests script

---

src/app/work-item/work-item-detail/work-item-detail-pipes/work-item-link-filters.pipe.ts
src/app/work-item/work-item-detail/work-item-link/work-item-link.component.html
src/app/work-item/work-item-detail/work-item-link/work-item-link.component.scss
src/app/work-item/work-item-detail/work-item-link/work-item-link.component.ts

Match Visuals for Work Item Links:
Visuals are: https://redhat.invisionapp.com/share/2KABL3Y4Z#/screens/215463855
Closes: #1125

refactor(wi-links): update UI of work item links

---

src/app/iteration/iteration-modal/iteration-modal.component.html
src/app/iteration/iteration-modal/iteration-modal.component.scss
src/app/iteration/iteration-modal/iteration-modal.component.ts
src/app/iteration/iteration.component.html
src/app/iteration/iteration.component.scss
src/app/iteration/iteration.module.ts
src/app/iteration/iteration.service.ts
src/app/iteration/iterations.service.spec.ts
src/app/models/iteration.model.ts
src/app/shared/mock-data/iteration-mock-generator.ts
src/app/work-item/work-item-detail/work-item-detail.component.html
src/app/work-item/work-item-detail/work-item-detail.component.ts

feat(iteration): UI for create nested iteration (Fix #1316)

---

src/app/work-item/work-item-board/work-item-board.component.html
src/assets/stylesheets/_planner-mixins.scss

Use right Patternfly icon for user icon
Closes: #1322

fix(user-icon): use correct patternfly icon for user-icon

---

cico_run_tests.sh

Add line to run only smoke test against PRs

Update smoke  tests

---

src/app/work-item/work-item-list/work-item-list.component.ts

List view loads in stand alone planner (#1461).

fix(list view): Loading of list view in stand alone planner (#1461).

---

package.json

fix(versions): Sync planner and platform shared dependencies versions.

fix(versions): Sync planner and platform shared dependencies versions.

---

src/app/shared/mock-data.service.ts
src/app/shared/mock-http.ts
src/app/work-item/work-item-iteration-association-modal/work-item-iteration-association-modal.component.ts

Fixed all the mock mentioned in #1412

---

src/app/iteration/iteration.component.html
src/app/iteration/iteration.component.scss
src/app/iteration/iteration.component.ts
src/app/side-panel/side-panel.component.html
src/app/side-panel/side-panel.component.scss
src/app/side-panel/side-panel.component.ts
src/app/work-item/work-item-detail/work-item-detail.component.ts
src/app/work-item/work-item.service.ts

Several fixes:
- selected iteration (or backlog) is now highlighted.
- backlog item count is not fake anymore.
- backlog item numbers and iteration item numbers get properly updated on work item actions.
- cursor is now a pointer over the iteration entries.
- the whole cell is clickable, not only the title.

fix(iterationpanel): repaired the iteration panel.

---

src/tests/work-item/work-item-list/comments.spec.js
src/tests/work-item/work-item-list/page-objects/work-item-detail.page.js

Add POM for Delete comments
- New elements for functional tests of Delete comment has been added in this PR
- One spec is Added to check those POM are correct

fix(test): Add POM for Delete comments

---

src/app/iteration/iteration-modal/iteration-modal.component.html
src/app/iteration/iteration-modal/iteration-modal.component.ts
src/app/iteration/iteration.component.html

Fixes one point from #1523 
Changes can be seen on
- iteration panel
- iteration popup (edit & create-child & create)

Remove extra "/" before the parent path of an iteration.

---

package.json
src/tests/work-item/work-item-list/smokeTest.spec.js

Update ngx-widgets to 0.13.2
Comment out failing functiona tests in smokeTest.spec.js

fix(version): Update ngx-widgets to 0.13.2

---

src/app/models/work-item.ts
src/app/shared/mock-data/work-item-mock-generator.ts
src/app/work-item/work-item.service.ts

Enables the child lists in list view.

fix(workitemlist): fix children.

---

src/app/iteration/iteration-modal/iteration-modal.component.html
src/app/iteration/iteration-modal/iteration-modal.component.ts

Previously we didn't allow the user to choose iteration date interval while creating the new iteration. Now this PR will allow the user to select the iteration date interval while creating the new iteration.

fix(iteration): show date picker in create interation modal (fix #1341)

---

src/app/work-item/work-item-detail/work-item-detail.component.html

fix(details page): Disable save button if no valid value has been selected for an area or iteration.

fix(details page): Disable save button if no valid value has been selected for an area or iteration.

---

src/app/work-item/work-item-detail/work-item-detail.component.html
src/app/work-item/work-item-detail/work-item-detail.component.ts

fix(detail page): Allow setting of fields, other than title, when creating a new work item using the detail panel. Fixes #1565.

fix(detail page): Allow setting of fields, other than title, when creating a new work item using the detail panel. Fixes #1565.

---

src/app/toolbar-panel/toolbar-panel.component.html
src/app/toolbar-panel/toolbar-panel.component.scss
src/app/work-item/work-item-list/work-item-list-entry/work-item-list-entry.component.scss

Removed the checkboxes on the work item list. We do now allow multiple selections yet anyway.

fix(workitemlist): disabled checkboxes.

---

src/app/iteration/iteration.component.scss

Removes a square color area on the right hand side of the current iteration panel.

Fix color issue on the current iteration panel

---

src/app/toolbar-panel/toolbar-panel.component.html
src/app/toolbar-panel/toolbar-panel.component.ts
src/app/toolbar-panel/toolbar-panel.module.ts
src/app/work-item/work-item-board/planner-board.module.ts
src/app/work-item/work-item-board/work-item-board.component.html
src/app/work-item/work-item-list/planner-list.module.ts
src/app/work-item/work-item-list/work-item-list.component.html
src/app/work-item/work-item-list/work-item-list.component.ts

fix add type selector panel to cover full screen
Closes : #1313

fix(detailtypepanel): fix add type selector panel to cover full screen

---

src/app/iteration/iteration.component.html
src/app/iteration/iteration.component.scss
src/app/work-item/work-item-list/work-item-list.component.scss

fix(side panel): Wrap long iteration titles.

fix(side panel): Wrap long iteration titles.

---

src/app/work-item/work-item-detail/dynamic-form/dynamic-field.component.html
src/app/work-item/work-item-detail/dynamic-form/dynamic-field.component.ts
src/app/work-item/work-item-detail/typeahead-dropdown/typeahead-dropdown.component.scss

With this PR, we are using the typeahread dropdown also in the dynamic form area, further aligning the UI to a common behavior and look.

fix(dynamicform): use generic dropdown for dynamic forms.

---

src/app/work-item/work-item-board/planner-board.module.ts
src/app/work-item/work-item-board/work-item-board.component.html
src/app/work-item/work-item-board/work-item-board.component.scss
src/app/work-item/work-item-board/work-item-board.component.ts
src/app/work-item/work-item-iteration-association-modal/work-item-iteration-association-modal.component.ts
src/app/work-item/work-item-iteration-association-modal/work-item-iteration-association-modal.module.ts
src/app/work-item/work-item-list/planner-list.module.ts
src/app/work-item/work-item-list/work-item-list-entry/work-item-list-entry.component.html

Fix: #1623 
Fix: #1595 
Fix: #638

fix(board view): add kebob menu

---

src/assets/stylesheets/shared/_layout.scss

Remove overwritten dropdown styles to fix kebab dropdown
Closes: #1595

fix(board-kebab): Remove overwritten dropdown styles

---

README.adoc

This replaces a broken link to the codecov pages.

Fix codecov link in README

---

src/app/work-item/work-item-detail/dynamic-form/dynamic-field.component.html
src/app/work-item/work-item-detail/markdown-control/markdown-control.component.html
src/app/work-item/work-item-detail/typeahead-dropdown/typeahead-dropdown.component.html
src/app/work-item/work-item-detail/work-item-comment/work-item-comment.component.html
src/app/work-item/work-item-detail/work-item-detail.component.html
src/app/work-item/work-item-detail/work-item-link/work-item-link.component.html
src/app/work-item/work-item-quick-add/work-item-quick-add.component.html
src/app/work-item/work-item-quick-add/work-item-quick-add.component.scss
src/app/work-item/work-item-quick-add/work-item-quick-add.component.spec.ts

update buttons with the checkmark (and those dictated by designs) to be styled as primary buttons

fix(buttons): update to use btn-primary

---

package.json
src/app/shared/http-service.ts
src/app/work-item/work-item.service.ts

Searching within space is working.
Verified on local integrated setup.

Remove changes in http service (that affected other GET calls too)

---

local_run_functional_tests.sh
protractor.config.js
src/app/work-item/work-item-detail/work-item-link/work-item-link.component.html
src/tests/work-item/work-item-list/linkItem.spec.js
src/tests/work-item/work-item-list/quickadd-workitem.spec.js
src/tests/work-item/work-item-list/work-item-detailed-dialog.spec.js

Clean up of Tests (fix according to UI modifications)
There are so many issues (Not in Mock) , but in the UI i.e
- Missing ID's in code to support tests
- Few changes in Functionality , Due to Dynamic forms (We have to make pages more scrollable)

Clean up of Tests (fix according to UI modifications)

---

src/assets/stylesheets/shared/_overrides-for-patternfly.scss

update top navbar border from blue to red
**this is a priority PR**

fix(navbar): update color to red

---

src/app/work-item/work-item-quick-add/work-item-quick-add.component.html
src/app/work-item/work-item-quick-add/work-item-quick-add.component.ts

Fixes #1646 
1. Converted `span` to `button` in order to use HTML attribute `disabled`.
2. Set `disabled` attribute while WI is being saved.
3. On completion of api request, remove `disabled` attribute.
4. Works for both - Enkter-key and Mouse-click

Prevent unwanted Work Item creation on consecutive clicks on Quick Add

---

src/app/toolbar-panel/toolbar-panel.component.html
src/app/toolbar-panel/toolbar-panel.component.scss

add a label to the type dropdown to call out the work item type that you are currently viewing
fixes https://github.com/fabric8io/fabric8-planner/issues/1659

fix(board): add label to type dropdown

---

src/app/shared/mock-data/work-item-mock-generator.ts
src/app/work-item/work-item-list/work-item-list.component.html
src/app/work-item/work-item-list/work-item-list.component.scss
src/app/work-item/work-item-list/work-item-list.component.ts

Blank slate is now clickable and opens the add WI dialog

Blank slate is now clickable and opens the add WI dialog

---

protractor.config.js
src/tests/work-item/work-item-list/board.spec.js
src/tests/work-item/work-item-list/iteration.spec.js
src/tests/work-item/work-item-list/page-objects/work-item-board.page.js

Enable iterations and board view tests

Enable iterations and board view tests

---

src/app/iteration/iteration-modal/iteration-modal.component.ts
src/app/shared/mock-data.service.ts
src/app/shared/mock-http.ts

fix(mock): fixes the create iteration behaviour.

---

src/app/work-item/work-item-detail/markdown-control/markdown-control.component.html
src/app/work-item/work-item-detail/markdown-control/markdown-control.component.ts

fix(detail page): Changes description placeholder to 'Add a Description'. Fixes #1602.

fix(detail page): Changes description placeholder to 'Add a Description'. Fixes #1602.

---

src/app/iteration/iteration-modal/iteration-modal.component.html
src/tests/work-item/work-item-list/iteration.spec.js
src/tests/work-item/work-item-list/page-objects/work-item-list.page.js

Nested iterations tests
- start child iteration /Parent
- close child iteration /Parent
- Edit Child iterations/Parent

Nested iterations tests

---

src/app/work-item/work-item-detail/work-item-detail.component.ts

Fixes #1741 
Focus on input field after `timeout`.

Focus on Title when creating new WI using full add

---

src/app/work-item/work-item-detail/work-item-link/work-item-link.component.html
src/app/work-item/work-item-detail/work-item-link/work-item-link.component.scss

Fixes the link panel, making it more logical in layout and alignment. Not the best css tricks there, but works for now.

fix(linkpanel): fixed link panel alignment.

---

src/app/work-item/work-item-detail/typeahead-dropdown/typeahead-dropdown.component.ts
src/app/work-item/work-item-detail/work-item-detail.component.ts

This fixes the empty dropdowns for the new WI dialog. The issue was caused by the dropdown values changing after the dialog is shown. The typeahead dropdown did not support Input() changes. It does support this now.

Fix dropdowns in new WI

---

src/app/work-item/work-item-board/work-item-board.component.html
src/app/work-item/work-item-quick-add/work-item-quick-add.component.html
src/app/work-item/work-item-quick-add/work-item-quick-add.component.ts

The quick add on the board now adds items based on the current selected context.

fix(board): added context to quick add on board.

---

src/app/work-item/work-item-detail/markdown-control/markdown-control.component.html
src/app/work-item/work-item-detail/markdown-control/markdown-control.component.ts

Show More/Less will be made visible based on the content height.

fix(detail page): Show More/Less will be made visible based on the content height.

---

src/app/iteration/iteration.service.ts
src/app/work-item/work-item.service.ts

Removed the notifications on errors, added console messages.

fix(erroreporting): removed notifications, added console reporting.

---

src/app/iteration/iteration.component.html
src/app/work-item/work-item-board/work-item-board.component.html
src/app/work-item/work-item-list/work-item-list-entry/work-item-list-entry.component.html
src/app/work-item/work-item-list/work-item-list-entry/work-item-list-entry.component.scss

fix(lists): entry list items are now full clickable to select.

---

src/app/collaborator/collaborator.service.ts
src/app/work-item/work-item-detail/work-item-detail.component.ts
src/app/work-item/work-item.service.ts

fixes https://github.com/fabric8io/fabric8-planner/issues/1538
Instead of pulling all users for assignee list, this PR enables the UI to pull only the collaborators. 
The collborators URL is present in the space response. Here's a sample :
https://github.com/almighty/almighty-core/pull/1116#issuecomment-296457081

Use collaborators in assignees list

---

src/app/iteration/iteration.component.scss
src/app/type/type.component.scss
src/app/work-item/work-item-board/work-item-board.component.html
src/app/work-item/work-item-board/work-item-board.component.scss
src/app/work-item/work-item-detail-add-type-selector/work-item-detail-add-type-selector-widget/work-item-detail-add-type-selector-widget.component.scss
src/app/work-item/work-item-detail/typeahead-dropdown/typeahead-dropdown.component.html
src/app/work-item/work-item-detail/typeahead-dropdown/typeahead-dropdown.component.scss
src/app/work-item/work-item-detail/typeahead-dropdown/typeahead-dropdown.component.ts
src/app/work-item/work-item-detail/work-item-detail.component.html
src/app/work-item/work-item-detail/work-item-detail.component.ts
src/app/work-item/work-item-list/work-item-list.component.scss
src/assets/stylesheets/shared/_custom-mixins.scss

Update css for typeahead dropdown

fix(typeahead): Update css for typeahead dropdown

---

src/app/work-item/work-item-iteration-association-modal/work-item-iteration-association-modal.component.scss

fix css for long wi title in iteration association modal
Closes: #1749

fix(itr-association):fix css for long wi title in iteration association

---

src/app/work-item/work-item-detail/work-item-detail.component.html
src/app/work-item/work-item-detail/work-item-detail.component.scss

fix css when wi created a few seconds ago
Closes: #1775

fix(wi-time-stamp): fix css when wi created a few seconds ago

---

src/app/work-item/work-item-quick-add/work-item-quick-add.component.html
src/app/work-item/work-item-quick-add/work-item-quick-add.component.scss
src/app/work-item/work-item-quick-add/work-item-quick-add.component.ts

Fix 
- height of input fields
- height of toggled wrappers
- button widths
Closes : #1773

fix(quick-add): fix height and padding for quick add wrappers

---

src/app/shared/filter.service.ts
src/app/work-item/work-item-board/work-item-board.component.ts
src/app/work-item/work-item-detail/work-item-detail.component.ts
src/app/work-item/work-item-list/work-item-list.component.ts
src/app/work-item/work-item.service.spec.ts
src/app/work-item/work-item.service.ts

Display newly added work item, added via the detailed view, in the board view. Fixes #1496.

fix(board view): Display newly added work item, added via the detailed view, in the board view. Fixes #1496.

---

src/app/work-item/work-item-detail/work-item-detail.component.ts

Broadcast close event when the detail page closes. List and board view listen for this event.

fix(detail page): broadcast close event when the detail page closes.

---

src/app/shared/http-service.ts

This needs to be merged first - https://github.com/almighty/almighty-core/pull/1260

fix(header): Added If-None-Match header to ignore all the cache

---

src/app/work-item/work-item-board/work-item-board.component.html
src/app/work-item/work-item-board/work-item-board.component.scss
src/app/work-item/work-item-detail-add-type-selector/work-item-detail-add-type-selector-widget/work-item-detail-add-type-selector-widget.component.html
src/app/work-item/work-item-detail-add-type-selector/work-item-detail-add-type-selector-widget/work-item-detail-add-type-selector-widget.component.scss
src/app/work-item/work-item-quick-add/work-item-quick-add.component.html
src/app/work-item/work-item-quick-add/work-item-quick-add.component.scss
src/assets/stylesheets/_dragula.scss
src/assets/stylesheets/shared/_custom-variables.scss

This PR addresses various items on the Board, Quick Add, Full Add, truncation methods and variations on visual designs.
NOTE: This is required for the demo, as it addresses issues shown in the presentation.

UX Updates for Board/Create WI/Visuals

---

src/app/iteration/iteration-modal/iteration-modal.component.html
src/app/iteration/iteration-modal/iteration-modal.component.ts

fix(iteration): fix distorted dropdown when no iteration found

---

src/app/work-item/work-item.service.ts

Quick filter for a certain WIT.

fix(witfilter): filtering a cerain WI.

---

src/app/work-item/work-item-board/work-item-board.component.scss
src/app/work-item/work-item-detail/work-item-detail.component.scss
src/app/work-item/work-item-detail/work-item-detail.component.ts
src/app/work-item/work-item-list/work-item-list.component.scss

fix(detail): delete comment modal

---

protractor.config.js
src/app/iteration/iteration.component.html
src/app/shared/mock-data/work-item-mock-generator.ts
src/app/work-item/work-item-board/work-item-board.component.html
src/tests/work-item/work-item-list/board.spec.js
src/tests/work-item/work-item-list/displayAndUpdateWorkItemDetails.spec.js
src/tests/work-item/work-item-list/iteration.spec.js
src/tests/work-item/work-item-list/page-objects/work-item-board.page.js
src/tests/work-item/work-item-list/page-objects/work-item-detail.page.js
src/tests/work-item/work-item-list/page-objects/work-item-list.page.js
src/tests/work-item/work-item-list/quickadd-workitem.spec.js

Reverts fabric8io/fabric8-planner#1818

Revert "Fix tests related to Iteration , dynamic form and delete from kebab"

---

src/app/work-item/work-item-board/work-item-board.component.scss
src/app/work-item/work-item-detail/work-item-detail.component.scss
src/app/work-item/work-item-detail/work-item-detail.component.ts
src/app/work-item/work-item-list/work-item-list.component.scss

Reverts fabric8io/fabric8-planner#1819

Revert "fix(detail): delete comment modal"

---

src/app/work-item/work-item-detail/markdown-control/markdown-control.component.html
src/app/work-item/work-item-detail/markdown-control/markdown-control.component.scss
src/app/work-item/work-item-detail/typeahead-dropdown/typeahead-dropdown.component.html
src/app/work-item/work-item-detail/typeahead-dropdown/typeahead-dropdown.component.scss
src/app/work-item/work-item-detail/work-item-detail.component.html
src/app/work-item/work-item-detail/work-item-detail.component.scss
src/tests/work-item/work-item-list/smokeTest.spec.js

update the Detail Panel with new visual design - layout, links and dropdowns
Note: Needed for demo

fix(DetailPanel): Update with visual design

---

protractor.config.js
src/app/iteration/iteration.component.html
src/app/shared/mock-data/work-item-mock-generator.ts
src/app/work-item/work-item-board/work-item-board.component.html
src/tests/work-item/work-item-list/EXCLUDED/orderOfExecution.spec.js
src/tests/work-item/work-item-list/EXCLUDED/work-item-timeStamp.spec.js
src/tests/work-item/work-item-list/TBD/home.spec.js
src/tests/work-item/work-item-list/TBD/hypothesis.spec.js
src/tests/work-item/work-item-list/TBD/microservices.spec.js
src/tests/work-item/work-item-list/TBD/notifications.spec.js
src/tests/work-item/work-item-list/TBD/pipeline.spec.js
src/tests/work-item/work-item-list/TBD/settings.spec.js
src/tests/work-item/work-item-list/TBD/test.spec.js
src/tests/work-item/work-item-list/assign.spec.js
src/tests/work-item/work-item-list/board.spec.js
src/tests/work-item/work-item-list/displayAndUpdateWorkItemDetails.spec.js
src/tests/work-item/work-item-list/displayWorkItemList.spec.js
src/tests/work-item/work-item-list/iteration.spec.js
src/tests/work-item/work-item-list/page-objects/work-item-board.page.js
src/tests/work-item/work-item-list/page-objects/work-item-detail.page.js
src/tests/work-item/work-item-list/page-objects/work-item-list.page.js
src/tests/work-item/work-item-list/quickadd-workitem.spec.js
src/tests/work-item/work-item-list/test-template.spec.js
src/tests/work-item/work-item-list/testSupport.js
src/tests/work-item/work-item-list/work-item-list.spec.js

- Mock for board view 
- Dynamic forms tests disabled as its not required for summit
- delete from kebab , tests disable (feature is temporarily disabled ).
- Converted all the Mobile based cases into Desktop cases (As mobile view is completely distorted )
Well, the tests are failing due to the stack of the Bugs :
- #1851
- #1852
- #1853
- #1854
I have made the changes and commented the Spec's for now , waiting for bugs to be fixed . Am using "Bug" inside Spec file to search for the specs commented due to the Bugs !

Fix tests related to Iteration , dynamic form and delete from kebab

---

src/app/work-item/work-item-detail/work-item-detail.component.html
src/tests/work-item/work-item-list/smokeTest.spec.js

Fix for https://github.com/fabric8io/fabric8-planner/issues/1854

fix(unassigned): None renamed to Unassigned

---

src/app/work-item/work-item-board/work-item-board.component.ts

Fix: fabric8io/fabric8-ui#1209

fix(board): update iteration count on WI state change

---

protractor.config.js

This PR is for more debugging and verbose log for tests Specs.

fix(tests-verbose): Tests verbose for better troubleshooting

---

protractor.config.js
src/tests/work-item/work-item-list/assign.spec.js
src/tests/work-item/work-item-list/displayAndUpdateWorkItemDetails.spec.js

Uncommented Tests, With Reseason of failure Bugs
Hello Team,
After this PR ./local_run_functional_test.sh will start showing 15 Failed Tests. 
Those tests are failing due to Product bugs.
To track the Live bugs in the product we are not commenting the known Failures. 
Stay tuned !

fix(uncomment-buggytests):Uncommented Tests, With Reseason of failure Bugs

---

src/app/work-item/work-item-detail/work-item-detail.component.ts

Fixes the vanishing comments when a WI is saved on the detail view (ex, when the state is changed).

fix(comments): fix vanishing comments on WI save.

---

src/app/components/planner-board/planner-board.module.ts
src/app/components/planner-list/planner-list.module.ts
src/app/components/work-item-iteration-modal/work-item-iteration-modal.module.ts

This Module got deleted while flattening refactoring. PR - #1890

fix(board): add work item iteration module

---

src/app/components/work-item-detail/work-item-detail.component.ts

fix(bug): Remove 'Saving work item' text after the new work item has been created. Fixes #1915.

fix(bug): Remove 'Saving work item' text after the new work item has been created. Fixes #1915.

---

src/app/components/work-item-list-entry/work-item-list-entry.component.ts

Fixes replacement of assignee icon when Move to Backlog option is selected from the kebab menu. Fixes #1835.

fix(bug): Fixes replacement of assignee icon in list view. Fixes #1835.

---

src/app/components/planner-list/planner-list.component.ts
src/app/components/work-item-detail/work-item-detail.component.ts
src/app/components/work-item-quick-add/work-item-quick-add.component.ts
src/app/services/work-item.service.ts

When a new work item is added or edited, the list needs to be displayed based on the applied filters.

fix(list view): Fix the work item list display

---

src/app/components/work-item-detail/work-item-detail.component.html
src/app/components/work-item-list-entry/work-item-list-entry.component.html

This addresses Todd's comment.

fix(ui): add WIT name to detail view

---

src/app/components/typeahead-dropdown/typeahead-dropdown.component.ts

Fix: https://github.com/fabric8io/fabric8-planner/issues/1847

fix(typeahead): block user to associate area/iteration from detail panel

---

src/app/components/planner-list/planner-list.component.ts
src/app/mock/mock-data.service.ts
src/app/services/filter.service.ts

Fix failing functional tests. Add new work item to the top of the list.

fix(mock-data): Fix failing functional tests.

---

src/app/components/side-panel/side-panel.component.html
src/app/components/side-panel/side-panel.component.scss

fix(side-panel): remove unnecessary underline on hovering Backlog

---

src/app/components/work-item-comment/work-item-comment.component.html

Closes #1968
Please check the main issue for contexts.

fix(tooltip): add directive to append tooltip element in body, to avoid misposition

---

src/app/components/iterations-modal/iterations-modal.component.html
src/app/components/iterations-modal/iterations-modal.component.scss
src/app/components/iterations-panel/iterations-panel.component.html
src/app/components/iterations-panel/iterations-panel.component.scss
src/app/components/planner-board/planner-board.component.html
src/app/components/planner-board/planner-board.component.scss
src/app/components/planner-board/planner-board.component.ts
src/app/components/planner-list/planner-list.component.html
src/app/components/planner-list/planner-list.component.scss
src/app/components/planner-list/planner-list.component.ts
src/app/components/side-panel/side-panel.component.html
src/app/components/side-panel/side-panel.component.scss
src/app/components/side-panel/side-panel.component.ts
src/app/components/toolbar-panel/toolbar-panel.component.html
src/app/components/toolbar-panel/toolbar-panel.component.scss
src/app/components/work-item-comment/work-item-comment.component.html
src/app/components/work-item-comment/work-item-comment.component.scss
src/app/components/work-item-create/work-item-create-selector/work-item-create-selector.component.html
src/app/components/work-item-create/work-item-create-selector/work-item-create-selector.component.scss
src/app/components/work-item-detail/work-item-detail.component.html
src/app/components/work-item-detail/work-item-detail.component.scss
src/app/components/work-item-link/work-item-link.component.html
src/app/components/work-item-link/work-item-link.component.scss
src/app/components/work-item-list-entry/work-item-list-entry.component.scss
src/app/components/work-item-quick-add/work-item-quick-add.component.html
src/app/components/work-item-quick-add/work-item-quick-add.component.scss

- Revert flex changes to Patternfly grid
- Convert em/rem to px. This is the follow up work from Platfrom
- Align HTML as per guidelines http://codeguide.co/#html
***DOES NOT INCLUDE REMOVING FLEX FOR LAYOUT.  ****

fix(quick-add): remove flex for all components

---

src/app/components/work-item-quick-add/work-item-quick-add.component.scss

fix error around missing variable in quick add component

fix(component): fix missing variable

---

src/app/components/planner-board/planner-board.component.scss
src/app/components/planner-board/planner-board.component.ts
src/app/components/planner-list/planner-list.component.scss
src/app/components/planner-list/planner-list.component.ts
src/app/components/work-item-link/work-item-link.component.html

resolve merge conflicts in wi link component

fix(work-item-link): resolve merge conflicts in wi link

---

src/app/components/planner-list/planner-list.component.scss

fix the height issue of Planner to be full height, rather than 1/4 height

fix(List): fix height issue

---

src/app/components/planner-list/planner-list.component.ts
src/app/components/work-item-quick-add/work-item-quick-add.component.ts
src/app/services/filter.service.ts
src/app/services/work-item.service.ts

https://openshift.io/openshiftio/openshiftio/plan/detail/927

fix(quick-add): Add iteration, area, workitem type, and assignee context

---

src/app/components/planner-board/planner-board.module.ts
src/app/components/planner-list/planner-list.module.ts

**# Need urgent merge!**
Fix courtesy: Sudipta

fix(inmemory): Fixed broken inmemorymode planner

---

src/app/components/planner-board/planner-board.component.ts

Fix kebab menu functionality. It was not working since the change in work item number.

fix(board): Fix kebab menu for card.

---

runtime/src/tests/work-item/work-item-list/page-objects/work-item-list.page.js
runtime/src/tests/work-item/work-item-list/testHelpersTestTemplate.spec.js
runtime/src/tests/work-item/work-item-list/work-item-list.spec.js
runtime/tests/protractor.config.js

Detection of kebab menu for iterations was failing due to some recent changes; fixed it.
Also made a change to protractor_config to make tests run in a particular workspace and not in the primary space, which caused interruption.

fix(test):update tests to fix iteration kebab

---

src/app/components/work-item-link/work-item-link.component.html

Fix: https://github.com/openshiftio/openshift.io/issues/409

fix(link): link type dropdown

---

src/app/components/group-types-panel/group-types-panel.component.html
src/app/components/group-types-panel/group-types-panel.component.less
src/app/components/group-types-panel/group-types-panel.component.ts
src/app/components/group-types-panel/group-types-panel.module.ts
src/app/components/planner-list/planner-list.component.ts
src/app/components/planner-list/planner-list.module.ts
src/app/components/side-panel/side-panel.component.html
src/app/components/side-panel/side-panel.component.ts
src/app/components/side-panel/side-panel.module.ts
src/app/models/group-types.model.ts
src/app/services/group-types.service.ts

Parse json and display Portfolio and Requirement tabs on the side panel.

feature(type groups): Parse json and display Portfolio and Requirement tabs on the side panel.

---

src/app/services/group-types.service.ts

Updated mock data to include level and sublevel information under one attribute. Also removed included attribute.

fix(side-panel): Updated mock data to include level and sublevel information

---

package.json

update PatternFly dependency to 3.26.1, matching fabric8-ui

fix(patternfly): update PatternFly dependency

---

runtime/src/assets/stylesheets/_base.less
runtime/src/assets/stylesheets/shared/_layout.less
runtime/src/assets/stylesheets/shared/_overrides-for-patternfly.less
src/app/components/work-item-detail/work-item-detail.component.html
src/app/components/work-item-detail/work-item-detail.component.less
src/app/components/work-item-link/work-item-link.component.html
src/assets/stylesheets/_base.less
src/assets/stylesheets/shared/_layout.less
src/assets/stylesheets/shared/_overrides-for-patternfly.less

This PR includes fixes for
-  Detail page title block
- filter dropdown(Toolbar and WI Link Dropdown)

fix(detail-page-css): fix CSS alignments for detail page

---

runtime/src/tests/work-item/work-item-list/page-objects/work-item-list.page.js

Page-object required to automate the story to add a new button to turn an iteration active.
Ref:
https://github.com/fabric8-ui/fabric8-planner/pull/2108
https://github.com/fabric8-ui/fabric8-planner/pull/2106

test(iteration): add page object for iteration active button

---

src/app/components/planner-board/planner-board.component.html

Fix: https://openshift.io/openshiftio/openshiftio/plan/detail/f53bfddd-cb96-4cd8-b91f-2bd8e8dfc627

fix(board): fix board view

---

src/app/components/group-types-panel/group-types-panel.component.html
src/app/components/group-types-panel/group-types-panel.component.less
src/app/components/iteration-list-entry/iteration-list-entry.component.html
src/app/components/iteration-list-entry/iteration-list-entry.component.less
src/app/components/iterations-modal/iterations-modal.component.html
src/app/components/iterations-modal/iterations-modal.component.ts
src/app/components/iterations-panel/iterations-panel.component.html
src/app/components/iterations-panel/iterations-panel.component.less
src/app/components/iterations-panel/iterations-panel.component.ts
src/app/components/switch/switch.component.html
src/app/components/switch/switch.component.ts
src/app/mock/mock-data/iteration-mock-generator.ts
src/app/models/iteration.model.ts

WORK IN PROGRESS.
- UI is ready but the integration with the core is not done.

fix(iteration): updated the mock data and iteration service

---

src/app/components/iterations-panel/iterations-panel.component.ts
src/app/services/iteration.service.ts

Update the iteration tree list when an iteration has been added or edited.

fix(side-panel): Update the iteration tree list

---

src/app/components/planner-list/planner-list.component.ts
src/app/components/work-item-detail/work-item-detail.component.ts
src/app/components/work-item-new-detail/work-item-new-detail.component.ts
src/app/services/work-item.service.ts

* Stopped loading of lists on navigate to detail page (Observable handle issue fixed)
* Temporary code added to redirect to the new detail page from the old detail page

Performance upgrade and backward compatibility for new detail page

---

runtime/src/tests/work-item/work-item-list/page-objects/work-item-list.page.js
runtime/src/tests/work-item/work-item-list/typeGroup.spec.js
runtime/src/tests/work-item/work-item-list/workItemTypeGroup.spec.js

Adds functional tests for work item type groups. Functional tests checks if links are present and click-able.
https://openshift.io/openshiftio/openshiftio/plan/detail/1500

Fixes OSIO-1500 and adds static wit groups test

---

src/app/components/planner-list/planner-list.component.ts
src/app/components/work-item-iteration-modal/work-item-iteration-modal.component.ts
src/app/models/work-item.ts

Fix https://github.com/openshiftio/openshift.io/issues/951

fix(list): associate to iteration from kebab menu

---

runtime/src/tests/work-item/work-item-list/page-objects/work-item-detail.page.js
runtime/src/tests/work-item/work-item-list/smokeTest.spec.js

This PR fixes the failing edit/cancel comment smoke test. @sanbornsen Please review.

fix(test): Fix edit/cancel comment test

---

src/app/components/work-item-list-entry/work-item-list-entry.component.html

Fix https://github.com/openshiftio/openshift.io/issues/988

fix(list): Open option in kebab menu

---

runtime/src/tests/work-item/work-item-list/page-objects/work-item-detail.page.js
src/app/components/work-item-detail/work-item-detail.component.html
src/app/components/work-item-detail/work-item-detail.component.ts
src/app/components/work-item-detail/work-item-detail.module.ts
src/app/components/work-item-new-detail/work-item-new-detail.component.html
src/app/widgets/inlineinput/inlineinput.component.html
src/app/widgets/inlineinput/inlineinput.component.less

fix https://github.com/openshiftio/openshift.io/issues/960

fix(quick-preview): replace almeditable with inline input component

---

runtime/src/assets/stylesheets/shared/_typography.less
src/assets/stylesheets/shared/_typography.less

Typography file did not match with the platform so header tags styles are breaking in the planner.
Updated the typography file in this PR.

fix(style): update planner typography files.

---

src/app/components/group-types-panel/group-types-panel.component.html
src/app/components/group-types-panel/group-types-panel.component.less
src/app/components/group-types-panel/group-types-panel.component.ts
src/app/components/group-types-panel/group-types-panel.module.ts
src/app/components/iteration-list-entry/iteration-list-entry.component.html
src/app/components/iteration-list-entry/iteration-list-entry.component.less
src/app/components/iterations-panel/iterations-panel.component.html
src/app/components/iterations-panel/iterations-panel.component.less
src/app/components/iterations-panel/iterations-panel.component.ts
src/app/components/planner-board/planner-board.component.html
src/app/components/planner-board/planner-board.component.less
src/app/components/planner-board/planner-board.component.ts
src/app/components/planner-board/planner-board.module.ts
src/app/components/planner-list/planner-list.component.html
src/app/components/planner-list/planner-list.component.less
src/app/components/planner-list/planner-list.component.ts
src/app/components/planner-list/planner-list.module.ts
src/app/components/side-panel/side-panel.component.html
src/app/components/side-panel/side-panel.component.less
src/app/components/side-panel/side-panel.component.ts
src/app/components/side-panel/side-panel.module.ts
src/app/components/work-item-detail/work-item-detail.component.less
src/app/components/work-item-quick-add/work-item-quick-add.component.less
src/app/services/group-types.service.ts
src/app/widgets/planner-layout/planner-layout.component.html
src/app/widgets/planner-layout/planner-layout.component.less
src/app/widgets/planner-layout/planner-layout.component.ts
src/app/widgets/planner-layout/planner-layout.module.ts
src/assets/stylesheets/_planner-layout.less
src/assets/stylesheets/shared/_formulas.less

- Add Planner Layout in widgets
- Integrate Side Panel to List View
- Integrate Side Panel to Board View
- Add Icons to Side Panel Titles
- CSS tweaks to Side Panel

Collapsable Side Panel

---

src/app/components/labels/labels.component.html
src/app/components/labels/labels.component.ts
src/app/components/labels/labels.module.ts
src/app/components/planner-list/planner-list.component.html
src/app/components/planner-list/planner-list.component.ts
src/app/components/toolbar-panel/toolbar-panel.component.ts
src/app/components/work-item-detail/work-item-detail.component.html
src/app/components/work-item-detail/work-item-detail.component.ts
src/app/components/work-item-list-entry/work-item-list-entry.component.html
src/app/components/work-item-list-entry/work-item-list-entry.component.ts
src/app/components/work-item-new-detail/work-item-new-detail.component.html
src/app/components/work-item-new-detail/work-item-new-detail.component.ts
src/app/components/work-item-new-detail/work-item-new-detail.module.ts
src/app/services/filter.service.spec.ts
src/app/services/filter.service.ts

Fix: https://github.com/openshiftio/openshift.io/issues/329

Filter by label in all possible places

---

src/app/components/label-selector/label-selector.component.ts
src/app/components/work-item-detail/work-item-detail.component.ts
src/app/components/work-item-new-detail/work-item-new-detail.component.ts
src/app/services/work-item.service.ts

- Sort labels in alphabetical order in list, detail and quick preview.
- Show random color instead of showing the same color every time while creating the label.

fix(labels): update experience for display labels and create labels

---

src/app/components/card/card.component.html
src/app/components/card/card.component.less

Board View Fixes
- Fix wi type font size(OSIO Issue: https://openshift.io/openshiftio/openshiftio/plan/detail/1569 )
- Overwritten user assign avatar css

fix(board-view): fix css issues in board view

---

src/app/components/planner-board/planner-board.component.html
src/app/components/planner-board/planner-board.component.less
src/app/components/planner-board/planner-board.component.ts
src/app/components/planner-list/planner-list.component.html
src/app/components/planner-list/planner-list.component.less
src/app/components/planner-list/planner-list.component.ts
src/app/components/toolbar-panel/toolbar-panel.component.less
src/assets/stylesheets/_planner-layout.less

Fix List view and board view height after applying filters
https://openshift.io/openshiftio/openshiftio/plan/detail/1522

fix(wi-view-height): fix wi view height after applying filters

---

src/app/components/iterations-panel/iterations-panel.component.ts
src/app/components/planner-list/planner-list.component.ts
src/app/components/work-item-quick-add/work-item-quick-add.component.ts
src/app/services/filter.service.spec.ts
src/app/services/filter.service.ts

Fixes https://openshift.io/openshiftio/openshiftio/plan/detail/1542

Show/hide work items in the list if it matches the current applied filters after an update.

---

runtime/src/assets/stylesheets/shared/_overrides-for-patternfly.less
runtime/src/assets/stylesheets/shared/_planner-mixins.less
runtime/src/tests/work-item/work-item-list/page-objects/work-item-detail.page.js
src/app/components/card/card.component.html
src/app/components/dynamic-field/dynamic-field.component.html
src/app/components/dynamic-field/dynamic-field.component.less
src/app/components/labels/labels.component.less
src/app/components/toolbar-panel/toolbar-panel.component.less
src/app/components/typeahead-dropdown/typeahead-dropdown.component.html
src/app/components/typeahead-dropdown/typeahead-dropdown.component.less
src/app/components/work-item-comment/work-item-comment.component.html
src/app/components/work-item-comment/work-item-comment.component.less
src/app/components/work-item-create/work-item-create-selector/work-item-create-selector.component.html
src/app/components/work-item-detail/work-item-detail.component.html
src/app/components/work-item-detail/work-item-detail.component.less
src/app/components/work-item-link/work-item-link.component.html
src/app/components/work-item-link/work-item-link.component.less
src/app/components/work-item-list-entry/work-item-list-entry.component.html
src/app/components/work-item-list-entry/work-item-list-entry.component.less
src/app/components/work-item-new-detail/work-item-new-detail.component.html
src/app/components/work-item-new-detail/work-item-new-detail.component.less
src/app/components/work-item-new-detail/work-item-new-detail.component.ts
src/app/components/work-item-quick-add/work-item-quick-add.component.less
src/app/widgets/inlineinput/inlineinput.component.html
src/app/widgets/inlineinput/inlineinput.component.less
src/app/widgets/select-dropdown/select-dropdown.component.less
src/assets/stylesheets/_planner-layout.less
src/assets/stylesheets/shared/_overrides-for-patternfly.less
src/assets/stylesheets/shared/_planner-mixins.less

Fix Css for Detail Page Layout. It comprises of following components
- Detail View Header
- Total Links Component
- Assignees, Creator, Iterations Wrapper
- Labels Dropdown
Issue:
https://github.com/openshiftio/openshift.io/issues/963
https://github.com/openshiftio/openshift.io/issues/964 (Part of it has been resolved)
https://openshift.io/openshiftio/openshiftio/plan/detail/1551
https://openshift.io/openshiftio/openshiftio/plan/detail/1547

Detail view layout

---

src/app/components/iterations-panel/iterations-panel.component.html
src/app/components/iterations-panel/iterations-panel.component.ts
src/app/components/side-panel/side-panel.component.html
src/app/components/work-item-quick-add/work-item-quick-add.component.ts

Set WIT context for quick add when an active iteration is selected.
Fixes https://openshift.io/openshiftio/openshiftio/plan/detail/1575 and https://openshift.io/openshiftio/openshiftio/plan/detail/1592

fix(iteration panel): Set WIT context for quick add when an active iteration is selected.

---

src/app/components/toolbar-panel/toolbar-panel.component.ts
src/app/services/filter.service.ts
src/app/services/work-item.service.ts

Fixes https://openshift.io/openshiftio/openshiftio/plan/detail/1598 and https://openshift.io/openshiftio/openshiftio/plan/detail/1599

Add filtering of work items by state and creator

---

src/app/components/work-item-list-entry/work-item-list-entry.component.html
src/app/components/work-item-quick-add/work-item-quick-add.component.ts

Please Refer : https://openshift.io/openshiftio/openshiftio/plan/detail/1554
Fix : https://drive.google.com/file/d/0B9v_DWsBK5HoY2NtcVI5eGdyNDA/view

Issue#1554

---

src/app/components/iterations-panel/iterations-panel.component.ts

Update side panel with the edits done on child iterations. Fixes OSIO [1545](https://openshift.io/openshiftio/openshiftio/plan/detail/1545).

fix(iterations): Update side panel with the edits done on child iterations. Fixes OSIO 1545.

---

runtime/src/assets/stylesheets/shared/_planner-mixins.less
src/app/components/toolbar-panel/toolbar-panel.component.less
src/app/components/work-item-detail/work-item-detail.component.less
src/app/components/work-item-new-detail/work-item-new-detail.component.less
src/assets/stylesheets/shared/_planner-mixins.less

Fix avatar css as per VD: https://redhat.invisionapp.com/share/Z5DZN33W8#/screens/259992905_QuickPreviewReview04
OSIO Issue: https://openshift.io/openshiftio/openshiftio/plan/detail/1610

fix(avatar): fix avatar css as per VD

---

deploy/release.groovy

This is for the staging link, due to npm 5 update

fix(build): add pack step to build to create a tarball 

---

src/app/services/iteration.service.ts

Fix: https://openshift.io/openshiftio/openshiftio/plan/detail/1656

fix(iteration): remove id from create child iteration request patch

---

src/app/components/iterations-modal/iterations-modal.component.ts

Fix: https://openshift.io/openshiftio/openshiftio/plan/detail/1611

fix(iteration): iteration start date cannot be later than end date

---

src/app/components/planner-list/planner-list.component.ts

Reset work item context when a work item is deselected. Fixes [OSIO-1549](https://openshift.io/openshiftio/openshiftio/plan/detail/1549)

fix(quick add): Reset work item context when a work item is deselected.

---

runtime/src/tests/work-item/work-item-list/displayAndUpdateWorkItemDetails.spec.js
runtime/src/tests/work-item/work-item-list/page-objects/work-item-detail.page.js
runtime/src/tests/work-item/work-item-list/quickadd-workitem.spec.js
runtime/src/tests/work-item/work-item-list/workitem-naughty-string.spec.js
runtime/tests/protractor.config.js

[16:23:00] I/launcher - 0 instance(s) of WebDriver still running
[16:23:00] I/launcher - chrome #01-0 passed
[16:23:00] I/launcher - chrome #01-1 passed
[16:23:00] I/launcher - chrome #01-2 passed
[16:23:00] I/launcher - chrome #01-3 passed
[16:23:00] I/launcher - chrome #01-4 passed
[16:23:00] I/launcher - chrome #01-5 passed
[16:23:00] I/launcher - chrome #01-6 passed
[16:23:00] I/launcher - chrome #01-7 passed
[16:23:00] I/launcher - chrome #01-8 passed
[16:23:00] I/launcher - chrome #01-9 passed
[16:23:00] I/launcher - chrome #01-10 passed
[16:23:00] I/launcher - chrome #01-11 passed
[16:23:00] I/launcher - chrome #01-12 passed
[16:23:00] I/launcher - chrome #01-13 passed
[16:23:00] I/launcher - chrome #01-14 passed
[16:23:00] I/launcher - chrome #01-15 passed
[16:23:00] I/launcher - …

Update ui tests to run cleanly again

---

src/app/widgets/inlineinput/inlineinput.component.html
src/app/widgets/inlineinput/inlineinput.component.ts
src/app/widgets/inlineinput/inlineinput.module.ts

fixes [osio1655](https://openshift.io/openshiftio/openshiftio/plan/detail/1655)

Resolves: Quick-preview does not switches to another WI view after the WI title is edited

---

runtime/src/tests/work-item/work-item-list/labels.spec.js
runtime/src/tests/work-item/work-item-list/page-objects/work-item-detail.page.js
runtime/src/tests/work-item/work-item-list/smokeTest.spec.js

Update smoke tests and add label tests to smoke tests

fix(smokeTest): Add label tests

---

runtime/src/assets/stylesheets/shared/_layout.less
src/app/components/planner-board/planner-board.component.ts
src/app/components/planner-list/planner-list.component.ts
src/app/components/work-item-new-detail/work-item-new-detail.component.ts
src/assets/stylesheets/shared/_layout.less

Fix overflow issue on planner and platform

No overflow for platform

---

src/app/components/group-types-panel/group-types-panel.component.html
src/app/components/group-types-panel/group-types-panel.component.less
src/app/components/iterations-panel/iterations-panel.component.html
src/app/components/iterations-panel/iterations-panel.component.less
src/app/components/planner-board/planner-board.component.ts
src/app/components/planner-list/planner-list.component.less
src/app/components/planner-list/planner-list.component.ts
src/app/components/side-panel/side-panel.component.html

This PR consists of issues in sidepanel as per UX review
Link to the issue: https://redhat.invisionapp.com/share/NCDYS7ZY7#/screens/258475883

fix(side-panel): fix side panel alignment issues

---

src/app/components/toolbar-panel/toolbar-panel.component.ts
src/app/models/filter.model.ts
src/app/services/filter.service.spec.ts
src/app/services/filter.service.ts

Query language is yet to support filter by title.

Filter by title 

---

src/app/components/iteration-list-entry/iteration-list-entry.component.html

Instead of no date set, use 'Set start date' and 'Set end date'

fix(iterations): Update "no date set" text. Fixes 1556.

---

runtime/src/tests/work-item/work-item-list/page-objects/work-item-list.page.js

This PR fixes the warnings shown below

fix(workItem): Fix smoketest warnings

---

src/app/components/work-item-link/work-item-link.component.html

Fix - https://openshift.io/openshiftio/openshiftio/plan/detail/1727

fix(link): replace total links with links.

---

runtime/src/tests/work-item/work-item-list/page-objects/work-item-detail.page.js
runtime/src/tests/work-item/work-item-list/smokeTest.spec.js

This PR fixes a few randomly failing smoketests.

fix(test):fixed a few failing tests

---

runtime/config/webpack.dev.js
runtime/src/app/shared/auth-api.provider.ts

This PR fixes the failures shown in the screenshots below

fix(runtime): Add AUTH and SSO environment variables

---

src/app/components/iterations-panel/iterations-panel.component.less
src/app/components/planner-list/planner-list.component.less
src/app/components/work-item-list-entry/work-item-list-entry.component.html
src/app/components/work-item-list-entry/work-item-list-entry.component.less

fix(list-view): align list view to top

---

src/app/components/planner-board/planner-board.component.ts
src/app/components/planner-list/planner-list.component.html
src/app/components/planner-list/planner-list.component.ts
src/app/components/work-item-new-detail/work-item-new-detail.component.ts

remove ngdocheck() and fix nativeelement issue

fix(planner): remove ngdocheck

---

src/app/components/work-item-list-entry/work-item-list-entry.component.html
src/app/components/work-item-list-entry/work-item-list-entry.component.less

fix(list-view): add wi state in list view

---

runtime/src/tests/work-item/work-item-list/assign.spec.js
runtime/src/tests/work-item/work-item-list/page-objects/work-item-detail.page.js
runtime/src/tests/work-item/work-item-list/smokeTest.spec.js
src/app/components/assignee-selector/assignee-selector.component.html
src/app/components/assignee-selector/assignee-selector.component.less
src/app/components/assignee-selector/assignee-selector.component.ts
src/app/components/assignee-selector/assignee-selector.module.ts
src/app/components/assignee/assignee.component.html
src/app/components/assignee/assignee.component.less
src/app/components/assignee/assignee.component.ts
src/app/components/assignee/assignee.module.ts
src/app/components/labels/labels.component.ts
src/app/components/planner-list/planner-list.module.ts
src/app/components/toolbar-panel/toolbar-panel.component.html
src/app/components/work-item-detail/work-item-detail.component.html
src/app/components/work-item-detail/work-item-detail.component.less
src/app/components/work-item-detail/work-item-detail.component.ts
src/app/components/work-item-detail/work-item-detail.module.ts
src/app/components/work-item-link/work-item-link.component.html
src/app/components/work-item-list-entry/work-item-list-entry.component.html
src/app/components/work-item-list-entry/work-item-list-entry.component.less
src/app/components/work-item-new-detail/work-item-new-detail.component.html
src/app/components/work-item-new-detail/work-item-new-detail.component.less
src/app/components/work-item-new-detail/work-item-new-detail.component.ts
src/app/components/work-item-new-detail/work-item-new-detail.module.ts

- Add new UI to assignee dropdown
- Match UI with multiple selector dropdown

New UI for Assignee dropdown

---

docker-compose.f8ui.yml

fix(deploy): set proxy-pass for nginx-config required by deploy container

---

src/app/components/work-item-create/work-item-create-selector/work-item-create-selector.component.html
src/app/components/work-item-create/work-item-create-selector/work-item-create-selector.component.less
src/app/components/work-item-create/work-item-create-selector/work-item-create-selector.component.ts

**WIP**
fix top position for wi modal to close the modal
Fixes https://openshift.io/openshiftio/openshiftio/plan/detail/1666

fix(wi-modal): fix top position for wi modal to close the modal

---

src/app/components/work-item-new-detail/work-item-new-detail.component.less
src/app/widgets/inlineinput/inlineinput.component.html

Fix minor css issues in detail page
- change close icon to default
- fix description field spacing

fix(detail-page): fix detail page css issues

---

src/app/components/iterations-panel/iterations-panel.component.ts

Disable dropping of a work item on the iteration panel.

fix(iteration-panel): Disable drop on iteration panel

---

index.html

Fixes minor typos in the web page.
@debloper

gh-pages typos

---

src/app/components/toolbar-panel/toolbar-panel.component.ts

fix(toolbar): Enable filter field in toolbar

---

src/app/components/planner-list/planner-list.component.html
src/app/components/planner-list/planner-list.component.less
src/app/components/planner-list/planner-list.component.ts
src/app/components/planner-list/planner-list.module.ts

Changes:
- Hide 1st column when user is not Logged In
- Add Empty state
- Fix Detail view route Url

Add Empty state when workItems are not available

---

README.adoc

fix(doc): Add build and npm version badge to README.md

---

src/app/components/planner-list/planner-list.component.html
src/app/components/planner-list/planner-list.component.less
src/app/components/toolbar-panel/toolbar-panel.component.html
src/app/components/work-item-quick-add/work-item-quick-add.component.html
src/app/components/work-item-quick-add/work-item-quick-add.component.less
src/app/components/work-item-quick-add/work-item-quick-add.component.ts

This PR consists of
1. remove unused css
2. fix quick add at different resolutions
3. fix inline quick add css
Issue: 
Solution:

fix(quick-add): fix quick add at low different resolutions

---

src/app/services/label.service.ts

fix(label-service): Add check for null current space. Fixes https://github.com/openshiftio/openshift.io/issues/1928

fix(label-service): Add check for null current space. Fixes SEV1 issue1928

---

src/app/components/planner-list/planner-list.component.ts
src/app/components/work-item-quick-add/work-item-quick-add.component.html
src/app/components/work-item-quick-add/work-item-quick-add.component.ts
src/app/services/work-item.service.ts

This PR introduces AddandOpen Button functionality.
Adds the workItem and then redirect to detail page of newly added workItem

fix(datatable/quickadd): open detail view on AddandOpen Button

---

src/app/components/planner-list/planner-list.component.ts
src/app/components/toolbar-panel/toolbar-panel.component.html
src/app/components/toolbar-panel/toolbar-panel.component.less
src/app/components/work-item-cell/work-item-cell.component.html
src/app/components/work-item-cell/work-item-cell.component.less

This introduces the tree exploration feature
Note: 
- Show tree is by default enabled
- Title Text is Bold for Workitems matching certain criteria

Tree exploration

---

runtime/src/tests/work-item/work-item-list/iteration.spec.js
runtime/src/tests/work-item/work-item-list/page-objects/work-item-list.page.js
src/app/components/group-types-panel/group-types-panel.component.html
src/app/components/iteration-list-entry/iteration-list-entry.component.html
src/app/components/iteration-list-entry/iteration-list-entry.component.ts
src/app/components/iteration-tree/iteration-tree.component.html
src/app/components/iteration-tree/iteration-tree.component.ts
src/app/components/iterations-panel/iterations-panel.component.html
src/app/components/iterations-panel/iterations-panel.component.less
src/app/components/iterations-panel/iterations-panel.component.ts
src/app/components/planner-list/planner-list.component.ts
src/app/services/group-types.service.ts

When an iteration is selected from the iterations tree view, the corresponding entry in active iterations section must show the selected icon.
https://openshift.io/openshiftio/openshiftio/plan/detail/1838

Highlight active iteration and selected iteration (osio-1838)

---

src/app/components/assignee-selector/assignee-selector.component.ts
src/app/components/planner-list/planner-list.component.ts
src/app/components/work-item-quick-add/work-item-quick-add.component.ts

Issue No . https://github.com/openshiftio/openshift.io/issues/1993

fix(quick-add): fix focus on qa title after enter

---

src/app/components/planner-list/datatable-config.ts
src/app/components/planner-list/planner-list.component.html
src/app/components/planner-list/planner-list.component.ts
src/app/components/toolbar-panel/toolbar-panel.component.html
src/app/components/toolbar-panel/toolbar-panel.component.ts
src/app/services/work-item.service.ts

This PR introduces:
- support for flat-list when `showTree` checkbox is `unchecked`
- show non-matching siblings in tree-view

Flat list and Tree Exploration

---

gulpfile.js

fix(build): encapsulate TS transpiling to work with watch mode

---

Dockerfile

fix(container): update Dockerfile to use proper steps for planner library integration

---

gulpfile.js

fix(build): update glob paths according to new gulp.watch API

---

src/app/components/planner-list/planner-list.component.ts

This PR fixes these bugs:
1. WI are not updated when you switch from flat-list to tree-view or vice-versa
Steps to reproduce: 
- tree-view: off (switch to flat list)
- update the title of any WI (say WI id 3)
- switch to tree-view (tree-view: on)
- title of WI id 3 is not updated in tree-view
2. Assignees and Creator for WorkItems in `included` section are not resolved when WI's are loaded in `tree-view: off` i.e. flat-list

fix(tree/flat-list): bug fixes in flat-list and tree-view

---

src/app/components/planner-list/datatable-config.ts
src/app/components/planner-list/planner-list.component.ts
src/app/components/work-item-cell/work-item-cell.component.html

fix OSIO issue : https://github.com/openshiftio/openshift.io/issues/2294

fix(datatable): filter name and column name not consistent

---

Jenkinsfile

fix(CI/CD): update pipeline.ci routine in CD step

---

Jenkinsfile
deploy/release.groovy

Fixes https://github.com/fabric8-ui/fabric8-planner/issues/2460
Please see https://github.com/fabric8-ui/fabric8-planner/issues/2460#issuecomment-366917884

`buildSnapshotFabric8UI` should not be called in CD

---

gulpfile.js

fix(CI/CD): don't rebuild during release step

---

src/app/components/assignee-selector/assignee-selector.component.html
src/app/components/assignee-selector/assignee-selector.component.less
src/app/components/assignee/assignee.component.less
src/app/components/work-item-cell/work-item-cell.component.html
src/app/components/work-item-comment/work-item-comment.component.less
src/app/components/work-item-detail/work-item-detail.component.less
src/app/components/work-item-new-detail/work-item-new-detail.component.less
src/assets/stylesheets/_planner-layout.less

fix osio issue : https://github.com/openshiftio/openshift.io/issues/2287

fix(datatable): remove pointer from avatar image

---

runtime/package.json

Fixes https://github.com/fabric8-ui/fabric8-planner/issues/2450

fix(tests): Fix incorrect karma config file path

---

src/app/components/group-types-panel/group-types-panel.component.ts
src/app/components/planner-list/planner-list.component.ts
src/app/mock/mock-data.service.ts
src/app/mock/mock-data/filter-mock-generator.ts
src/app/mock/mock-data/work-item-mock-generator.ts
src/app/mock/mock-http.ts

- Update mock filter data a
- enable default url for inmemory mode
- fix creator filter
- fix area filter
- fix state filter

fix(test): Fix the filter drop down

---

deploy/release.groovy
karma.conf.js
scripts/upload_to_codecov.sh
src/app/components/side-panel/side-panel.component.ts

Current master code coverage - https://codecov.io/gh/fabric8-ui/fabric8-planner/tree/master/src/app

fix(tests): Enable codecov for unit tests code coverage

---

src/app/components_ngrx/work-item-detail/work-item-detail.component.html
src/app/components_ngrx/work-item-detail/work-item-detail.component.ts
src/app/widgets/inlineinput/inlineinput.component.ts
src/tests/specs/smoke/smokeTest.spec.ts
src/tests/ui/planner/workitem-quickpreview.ts

Issue: https://github.com/openshiftio/openshift.io/issues/2438

fix(detail): Empty field can not be saved.

---

src/app/components_ngrx/iterations-modal/iterations-modal.component.html

Closes openshiftio/openshift.io#1995

fix(iteration): allow pressing enter on iteration name to create/update iteration

---

src/app/components/typeahead-dropdown/typeahead-dropdown.component.html
src/app/components/typeahead-dropdown/typeahead-dropdown.component.less
src/app/components/typeahead-dropdown/typeahead-dropdown.component.ts
src/app/components/typeahead-dropdown/typeahead-dropdown.module.ts
src/tests/specs/smoke/smokeTest.spec.ts
src/tests/support/constants.ts
src/tests/ui/planner/workitem-quickpreview.ts

issue: https://github.com/openshiftio/openshift.io/issues/2533

fix(typeahead-dropdown): suggestion issue with typeahead dropdown

---

Jenkinsfile

This is for testing https://github.com/openshiftio/openshift.io/issues/2749

Use a development branch from pipeline library

---

src/app/actions/work-item.actions.ts
src/app/components_ngrx/iteration-list-entry/iteration-list-entry.component.html
src/app/components_ngrx/work-item-cell/work-item-cell.component.html
src/app/effects/iteration.effects.ts
src/app/reducers/work-item.reducer.ts
src/tests/specs/iteration.spec.ts
src/tests/support/constants.ts
src/tests/ui/planner/iteration.ts
src/tests/ui/planner/sidepanel.ts
src/tests/ui/planner/workitem-list-entry.ts
src/tests/ui/planner/workitem-list.ts

fixes issue : Updating Iteration name doesn't update the workitem associated iteration
https://github.com/openshiftio/openshift.io/issues/2444
**Yes**

fix(iteration/workitem): Updating Iteration name doesn't update the workitem associated iteration

---

src/app/components_ngrx/group-types-panel/group-types-panel.component.html
src/app/components_ngrx/group-types-panel/group-types-panel.component.ts
src/app/components_ngrx/iteration-list-entry/iteration-list-entry.component.html
src/app/components_ngrx/iteration-list-entry/iteration-list-entry.component.ts
src/app/components_ngrx/iteration-tree/iteration-tree.component.html
src/app/components_ngrx/iteration-tree/iteration-tree.component.ts
src/app/components_ngrx/iterations-panel/iterations-panel.component.html
src/app/components_ngrx/iterations-panel/iterations-panel.component.ts
src/app/components_ngrx/planner-list/planner-list.component.ts
src/app/components_ngrx/toolbar-panel/toolbar-panel.component.html
src/app/components_ngrx/toolbar-panel/toolbar-panel.component.less
src/app/components_ngrx/toolbar-panel/toolbar-panel.component.ts

- Do not show Work Items in State Closed. 
https://openshift.io/openshiftio/openshiftio/plan/detail/1916
Yes, #2490

Do not show Work Items in State Closed.

---

src/app/components_ngrx/iterations-modal/iterations-modal.component.ts

issue: https://github.com/openshiftio/openshift.io/issues/2506

fix(iteration): iteration date selector only allows selecting past dates

---

src/app/effects/detail-work-item.effects.ts

Fix typo worktem --> work item

---

src/app/components_ngrx/label-selector/label-selector.component.html

Closes openshiftio/openshift.io#1836

fix(labels): update the WI-label association callout to not confuse with label creation

---

cico_build_deploy.sh

Temporarily disable functional tests to tests CD on cico

Temporarily disable functional tests

---

src/app/components_ngrx/planner-list/planner-list.component.ts
src/app/components_ngrx/work-item-detail/work-item-detail.component.html

Remove unwanted white space in the footer of the list view. Changes in UX of the feature flag banner introduce this issue. 
https://openshift.io/openshiftio/openshiftio/plan/detail/2032
NA

fix(list): remove unwanted extra white space in list view

---

src/app/components/assignee-selector/assignee-selector.component.html
src/app/components/dynamic-field/dynamic-field.component.less
src/app/components/iterations-panel/iterations-panel.component.html
src/app/components/label-selector/label-selector.component.html
src/app/components/work-item-comment/work-item-comment.component.html
src/app/components/work-item-comment/work-item-comment.component.less
src/app/components/work-item-detail/work-item-detail.component.html
src/app/components/work-item-detail/work-item-detail.component.less
src/app/components/work-item-detail/work-item-detail.component.ts
src/app/components/work-item-link/work-item-link.component.html
src/app/components/work-item-link/work-item-link.component.less
src/app/components/work-item-new-detail/work-item-new-detail.component.html
src/app/components/work-item-new-detail/work-item-new-detail.component.less
src/app/components_ngrx/assignee-selector/assignee-selector.component.html
src/app/components_ngrx/iterations-panel/iterations-panel.component.html
src/app/components_ngrx/label-selector/label-selector.component.html
src/app/components_ngrx/work-item-comment/work-item-comment.component.html
src/app/components_ngrx/work-item-comment/work-item-comment.component.less
src/app/components_ngrx/work-item-detail/work-item-detail.component.html
src/app/components_ngrx/work-item-detail/work-item-detail.component.less
src/app/components_ngrx/work-item-link/work-item-link.component.html
src/app/components_ngrx/work-item-link/work-item-link.component.less
src/app/components_ngrx/work-item-preview-panel/work-item-preview-panel.component.ts
src/app/components_ngrx/work-item-quick-preview/work-item-quick-preview.component.ts
src/assets/stylesheets/shared/_overrides-for-patternfly.less

OSIO Issue: https://openshift.io/openshiftio/openshiftio/plan/detail/1913

fix(detail): fix cosmetic issues in detail and quick-preview

---

src/app/components_ngrx/assignee-selector/assignee-selector.component.html
src/app/widgets/select-dropdown/select-dropdown.component.html
src/app/widgets/select-dropdown/select-dropdown.component.less

Fix CSS for select dropdown
https://github.com/openshiftio/openshift.io/issues/3092
NA
NA
NA
@nimishamukherjee @rgarg1

fix(slect-dropdown): remove height and fix hover css for selct dropdown

---

src/app/components_ngrx/labels/labels.component.html
src/app/components_ngrx/labels/labels.component.less
src/app/components_ngrx/labels/labels.component.ts
src/app/components_ngrx/labels/labels.module.ts
src/app/components_ngrx/planner-list/planner-list.component.html
src/app/components_ngrx/work-item-detail/work-item-detail.component.html

Now Clicking on a Lable in the Tabel View filters the WorkItem List by Label.
Please Refer: https://github.com/openshiftio/openshift.io/issues/2447, https://github.com/openshiftio/openshift.io/issues/2295
Test: Done

fix(dataTable) : filter by label now working

---

src/app/components_ngrx/work-item-quick-add/work-item-quick-add.component.html
src/app/components_ngrx/work-item-quick-add/work-item-quick-add.component.less

Fix icon spacing issues in type dropdown
https://github.com/openshiftio/openshift.io/issues/3086
NA
NA
NA
@nimishamukherjee @rgarg1

fix(quick-add): fix dropdown type icon spacing

---

src/app/components/work-item-link/work-item-link.component.ts
src/app/effects/link-type.effects.ts
src/app/services/work-item.service.ts

After space template PR comes in we are getting 404 for workitemlinktypes API.
NA
Test is in this PR https://github.com/fabric8-ui/fabric8-planner/pull/2563

fix(link): fix workitemlinktypes URL

---

src/tests/specs/quickPreview.spec.ts
src/tests/specs/smoke/smokeTest.spec.ts
src/tests/specs/workItemTableTest.spec.ts
src/tests/ui/planner/index.ts
src/tests/ui/planner/sidepanel.ts
src/tests/ui/planner/toolbarHeader.ts
src/tests/ui/planner/workitem-inline-quickadd.ts
src/tests/ui/planner/workitem-quickpreview.ts

This PR adds workitem link and tree expansion test
https://github.com/fabric8-ui/fabric8-planner/issues/2562 and https://github.com/fabric8-ui/fabric8-planner/issues/2566
Yes

fix(test) : links and tree expansion tests

---

src/app/components_ngrx/planner-list/planner-list.component.html
src/app/components_ngrx/planner-list/planner-list.component.ts
src/app/components_ngrx/toolbar-panel/toolbar-panel.component.html
src/app/components_ngrx/toolbar-panel/toolbar-panel.component.ts

Fixes issues:
- Fix Hardcoded value in toolbar
- Fix typo 'Atrributes'
- Fix Distorted Alignment of columns 
https://github.com/openshiftio/openshift.io/issues/3041
https://github.com/openshiftio/openshift.io/issues/3062
https://github.com/openshiftio/openshift.io/issues/3090
ok Without test

fix(PlannerList): bug fixes

---

src/app/actions/work-item.actions.ts
src/app/components_ngrx/work-item-quick-add/work-item-quick-add.component.ts
src/app/effects/work-item.effects.ts
src/tests/specs/smoke/smokeTest.spec.ts
src/tests/ui/planner/workitem-quickadd.ts

Clicking on "Add and Open" : 
- Adds the WorkItem
- Open the detail page
https://github.com/openshiftio/openshift.io/issues/2995
Yes, [here](https://github.com/fabric8-ui/fabric8-planner/pull/2578)

fix(quickAdd): open detail page on "Add and Open"

---

src/app/components_ngrx/assignee-selector/assignee-selector.component.html

Fix disappearing assignee component when the user is not a collaborator on the space
https://github.com/openshiftio/openshift.io/issues/2948
No

fix(work-item-details): Fix disappearing assignee component (git-2948)

---

src/tests/ui/planner/workitem-quickpreview.ts

The PR re-enables the check for link option in the quick-preview of a workitem. This check was removed when linking feature was disabled for a while.
N/A
N/A
N/A
N/A

fix(test):add links to readiness check

---

Dockerfile
src/tests/specs/iteration.spec.ts
src/tests/ui/planner/iteration.ts

Chrome installation on CentOS is failing beacuse chrome stable channel is down.
This PR adds chrome beta channel which will fix the issue.

fix(CI/CD) : fix failing chrome installation

---

src/tests/page_objects/planner/planner.page.ts
src/tests/specs/iteration.spec.ts
src/tests/specs/quickPreview.spec.ts
src/tests/specs/smoke/smokeTest.spec.ts
src/tests/specs/workItemTableTest.spec.ts
src/tests/ui/planner/iteration.ts
src/tests/ui/planner/settings.ts
src/tests/ui/planner/sidepanel.ts

**To run 32 functional tests, it takes approx. 18-19min but now it is taking approx. 7min**
Before : https://ci.centos.org/job/devtools-fabric8-planner-f8planner/687/console
Now : https://ci.centos.org/job/devtools-fabric8-planner-f8planner/707/console
https://github.com/fabric8-ui/fabric8-planner/issues/2583
Yes

fix(tests) : Added beforeAll function

---

src/app/widgets/inlineinput/inlineinput.component.html
src/app/widgets/inlineinput/inlineinput.component.ts
src/tests/specs/quickPreview.spec.ts

- Added a function to convert the special character. 
- Remove innerHTML from inlineInput component.
- Fix test.
https://github.com/openshiftio/openshift.io/issues/3362
NA

fix(inline-title): parse special character before render in UI

---

Dockerfile

Use latest chrome for tests intead of beta version
N/A
N/A
N/A
@rgarg1 @Raunak1203

fix(tests): Use latest stable chrome instead of beta version

---

src/app/services/infotip.service.ts

fix(url): ssl secured URL is added for infotips

---

src/app/effects/work-item-type.effects.ts

see - openshiftio/openshift.io#3447
___

fix(workitem-type): added can-construct filter to work item type list

---

src/app/components_ngrx/custom-query-panel/custom-query-panel.component.html

As the titles are truncated, we show the complete custom query title on hover.
https://github.com/openshiftio/openshift.io/issues/3143
No

fix(custom-query): Enable tooltip for custom queries (git-3143).

---

src/app/effects/work-item-utils.ts

- Check for query params for in detail page.
https://github.com/openshiftio/openshift.io/issues/3470
___

fix(detail): update work item

---

src/app/components_ngrx/planner-list/planner-list.component.ts
src/app/effects/space.effects.ts

https://github.com/openshiftio/openshift.io/issues/3471
___

fix(list): refresh colaborator and area list.

---

src/app/services/cookie.service.ts

- fixes openshiftio/openshift.io#3472
___

fix(cookie): added version to table config cookie

---

src/app/effects/space.effects.ts

https://github.com/openshiftio/openshift.io/issues/3478
___

fix(detail): fix detail page.

---

src/app/components_ngrx/planner-list/planner-list.component.ts
src/app/services/filter.service.spec.ts
src/app/services/filter.service.ts

In the absence of back-end support ATM to filter out Completed work items in SCRUM, adding temporary hack at UI to filter out work items with specific states (Closed, Done, Removed)
https://github.com/openshiftio/openshift.io/issues/3486
___

fix(show-completed): hard coded state filter for show-completed checkbox

---

karma.conf.js
src/app/actions/area.actions.spec.ts
src/app/models/work-item-type.ts
src/app/services/filter.service.ts

This PR adds tests for area actions
___

Added tests for area actions

---

src/app/reducers/collaborator.reducer.spec.ts

Added unit tests for the collaborator reducer.
Yes

fix(test): added collaborator reducer unit tests

---

src/tests/page_objects/base.page.ts
src/tests/specs/iteration.spec.ts
src/tests/specs/quickPreview.spec.ts
src/tests/specs/smoke/smokeTest.spec.ts
src/tests/specs/workItemTableTest.spec.ts

This PR replaces browser.sleep with wait until condition
https://github.com/fabric8-ui/fabric8-planner/issues/2632
___

fix(test) : replace browser.sleep with wait until

---

src/app/reducers/area.reducer.spec.ts
src/app/reducers/area.reducer.ts

Added unit tests for area reducer
Yes

fix(test): added unit test for area reducer

---

runtime/tests/protractor.config.js
src/tests/ui/base.element.ts

This PR reduces the Default wait time from 3 minutes to 1 minute
N/A
N/A

fix(tests): Reduce default wait from 3 minutes to 1 minute

---

src/assets/stylesheets/shared/_utilities.less

This PR fixes this - https://github.com/openshiftio/openshift.io/issues/3505 issue.

fix(infotip) : Row overlapping with infotip fixed

---

src/tests/specs/detailPage.spec.ts
src/tests/specs/workItemTableTest.spec.ts
src/tests/ui/base.element.ts
src/tests/ui/planner/workitem-detailpage.ts
src/tests/ui/planner/workitem-list-entry.ts
src/tests/ui/planner/workitem-list.ts
src/tests/ui/planner/workitem-quickpreview.ts

This PR adds tests for detail page
https://github.com/fabric8-ui/fabric8-planner/issues/2624
Yes
___

fix(tests) :Added detail page tests

---

src/app/actions/custom-query.actions.ts
src/app/components/modal/modal.component.ts
src/app/components_ngrx/custom-query-panel/custom-query-panel.component.html
src/app/components_ngrx/custom-query-panel/custom-query-panel.component.less
src/app/components_ngrx/custom-query-panel/custom-query-panel.component.ts
src/app/components_ngrx/custom-query-panel/custom-query-panel.module.ts
src/app/components_ngrx/toolbar-panel/toolbar-panel.component.html
src/app/components_ngrx/toolbar-panel/toolbar-panel.component.ts
src/app/effects/custom-query.effects.ts
src/app/reducers/custom-query.reducer.ts
src/app/services/custom-query.service.ts
src/tests/page_objects/planner/planner.page.ts
src/tests/specs/smoke/smokeTest.spec.ts
src/tests/ui/planner/sidepanel.ts

This PR contain delete feature of the custom query.
https://openshift.io/openshiftio/openshiftio/plan/detail/2198
Yes

feat(customquery): added delete custom query feature

---

src/app/components_ngrx/work-item-link/work-item-link.component.ts

- A work item cannot be self linked.
https://github.com/openshiftio/openshift.io/issues/3205
No

fix(link): work item can not be self linked.

---

runtime/src/app/components/header/header.component.ts
runtime/src/app/services/spaces.service.ts
src/app/effects/space.effects.ts

Fixes the standalone to work with non-mock backends.
Part of https://openshift.io/openshiftio/openshiftio/plan/detail/2261
No, only dev env, not production used.

Fix for running standalone against prod-preview or local WIT

---

src/app/components_ngrx/toolbar-panel/toolbar-panel.component.ts

fixes openshiftio/openshift.io#3433
We subscribe for any change in filter attributes
openshiftio/openshift.io#3433
No, and not required for this PR
___

fix(filter): filter data sources are subscribed to check for the updates

---

src/app/components_ngrx/toolbar-panel/toolbar-panel.component.html

fix dropdown when filter has been removed
https://github.com/openshiftio/openshift.io/issues/3229#event-1608022548
___NA

fix(dropdown): save filter dropdown is closed when a filter is removed

---

package.json

Update rh-ngx-datatable version:
fixes the issue of overlapping rows in Safari 
ok-without-tests
___

fix(datatable): update rh-ngx-datatable version

---

src/app/components_ngrx/toolbar-panel/toolbar-panel.component.html
src/app/components_ngrx/toolbar-panel/toolbar-panel.component.less

Fix CSS for filters results
https://github.com/openshiftio/openshift.io/issues/2436
NA
NA
NA
@nimishamukherjee @sunilmalagi @rgarg1

fix(toolbar): fix filter results css

---

src/app/components_ngrx/work-item-detail/work-item-detail.component.html
src/app/components_ngrx/work-item-link/work-item-link.component.html
src/app/components_ngrx/work-item-link/work-item-link.component.ts

Add link to links in detail page.
https://github.com/openshiftio/openshift.io/issues/3620
NA

fix(link): add link to links in detail page.

---

src/tests/page_objects/base.page.ts
src/tests/page_objects/planner/planner.page.ts
src/tests/specs/detailPage.spec.ts
src/tests/specs/iteration.spec.ts
src/tests/specs/quickPreview.spec.ts
src/tests/specs/smoke/smokeTest.spec.ts
src/tests/specs/workItemTableTest.spec.ts
src/tests/support/constants.ts
src/tests/ui/base.element.ts
src/tests/ui/planner/iteration.ts
src/tests/ui/planner/workitem-list-entry.ts
src/tests/ui/planner/workitem-list.ts
src/tests/ui/planner/workitem-quickpreview.ts

This PR fixes the functional test failures because of the changes in the api tests.
___

fix(test) :fix functional tests

---

package.json
src/app/actions/comment.actions.ts
src/app/components/work-item-new-detail/work-item-new-detail.component.ts
src/app/components_ngrx/work-item-comment-wrapper/work-item-comment-wrapper.component.ts
src/app/components_ngrx/work-item-comment/work-item-comment.component.html
src/app/components_ngrx/work-item-comment/work-item-comment.component.less
src/app/components_ngrx/work-item-comment/work-item-comment.component.ts
src/app/components_ngrx/work-item-comment/work-item-comment.module.ts
src/app/effects/comment.effects.ts
src/app/models/comment.spec.ts
src/app/models/comment.ts
src/app/widgets/comment-module/comment.component.html
src/app/widgets/comment-module/comment.component.less
src/app/widgets/comment-module/comment.component.ts
src/app/widgets/comment-module/comment.module.ts
src/app/widgets/comment-module/comment.spec.ts
src/tests/ui/planner/workitem-quickpreview.ts

This PR adds threaded comment feature.
https://openshift.io/openshiftio/openshiftio/plan/detail/1723
Added test
___
This PR depends on this service PR - https://github.com/fabric8-services/fabric8-wit/pull/2101

Threaded comments with create and update

---

src/app/services/filter.service.ts

This PR fixes https://github.com/openshiftio/openshift.io/issues/3643
___

fix(filter): Use regex to match filter field:value in query

---

src/app/actions/event.action.spec.ts
src/app/actions/event.action.ts
src/app/actions/index.actions.ts
src/app/components_ngrx/work-item-detail/work-item-detail.component.html
src/app/components_ngrx/work-item-detail/work-item-detail.module.ts
src/app/components_ngrx/work-item-event-wrapper/work-item-event-wrapper.component.html
src/app/components_ngrx/work-item-event-wrapper/work-item-event-wrapper.component.less
src/app/components_ngrx/work-item-event-wrapper/work-item-event-wrapper.component.ts
src/app/components_ngrx/work-item-event-wrapper/work-item-event-wrapper.module.ts
src/app/components_ngrx/work-item-event/work-item-event.component.html
src/app/components_ngrx/work-item-event/work-item-event.component.less
src/app/components_ngrx/work-item-event/work-item-event.component.ts
src/app/components_ngrx/work-item-event/work-item-event.module.ts
src/app/effects/event.effects.ts
src/app/effects/index.effects.ts
src/app/models/event.model.spec.ts
src/app/models/event.model.ts
src/app/models/work-item.spec.ts
src/app/models/work-item.ts
src/app/pipes/f8-time.module.ts
src/app/pipes/f8-time.pipe.ts
src/app/reducers/event.reducer.spec.ts
src/app/reducers/event.reducer.ts
src/app/reducers/index.reducer.ts
src/app/services/work-item.service.ts
src/app/states/app.state.ts
src/app/states/event.state.ts
src/app/states/index.state.ts
src/planner.module.ts

Implement Audit-Trail feature
https://openshift.io/openshiftio/openshiftio/plan/detail/1915
Added tests
___
**Note:**
Document for Audit-Trail messages: https://docs.google.com/spreadsheets/d/1fi2ZbAECorWkM3Krug7HhyXsUdF4wa76RWTPmPMhDkU/edit?ts=5b080e62#gid=423213162

feat(events): add audit trail feature

---

src/app/models/work-item.spec.ts
src/app/models/work-item.ts

- fixes openshiftio/openshift.io#3659
Fixes markdown issue for the description field
https://github.com/openshiftio/openshift.io/issues/3659
Yes
___

fix(workitem): description markdown fixed

---

src/app/components_ngrx/custom-query-panel/custom-query-panel.component.html
src/app/components_ngrx/custom-query-panel/custom-query-panel.component.less
src/app/components_ngrx/group-types-panel/group-types-panel.component.html
src/app/components_ngrx/group-types-panel/group-types-panel.component.less
src/app/components_ngrx/iteration-list-entry/iteration-list-entry.component.html
src/app/components_ngrx/iteration-list-entry/iteration-list-entry.component.less
src/app/components_ngrx/iteration-tree/iteration-tree.component.html
src/app/components_ngrx/iterations-panel/iterations-panel.component.html
src/app/components_ngrx/iterations-panel/iterations-panel.component.less
src/app/components_ngrx/planner-list/planner-list.component.html
src/app/components_ngrx/planner-list/planner-list.component.less
src/app/components_ngrx/side-panel/side-panel.component.html
src/app/components_ngrx/toolbar-panel/toolbar-panel.component.html
src/app/components_ngrx/toolbar-panel/toolbar-panel.component.less
src/app/components_ngrx/toolbar-panel/toolbar-panel.component.ts
src/assets/stylesheets/_planner-layout.less
src/assets/stylesheets/shared/_infotip.less
src/tests/ui/planner/sidepanel.ts

revamping left panel
fixing minor cosmetic bugs
subset: https://github.com/openshiftio/openshift.io/issues/3212
NA
NA
NA
@nimishamukherjee @rgarg1

fix(iteration): update design for iteration

---

src/app/components_ngrx/work-item-event-wrapper/work-item-event-wrapper.component.html
src/app/models/event.model.ts
src/app/services/work-item.service.ts

fixes  bug in Audit-Trail
Steps to reproduce bug:
1. Create a new workitem
2. Update a field ex: labels
3. There is no event logged for change in label
4. Update Another field ex: Assignee
5. Both events for Label and Assignee are logged in Timeline simultaneously
___

fix(event): remove duplicate entry from old value and new value

---

src/app/components_ngrx/iterations-modal/iterations-modal.component.ts
src/tests/ui/planner/iteration.ts

Allow the user to select Past or future start date.
https://github.com/openshiftio/openshift.io/issues/2506
No

fix(iteration): Allow user to select past and future start date.

---

src/app/components_ngrx/common-selector/common-selector.component.ts
src/app/components_ngrx/dynamic-field/dynamic-field.component.html
src/app/components_ngrx/work-item-detail/work-item-detail.component.html
src/app/widgets/inlineinput/inlineinput.component.html
src/app/widgets/inlineinput/inlineinput.component.ts
src/app/widgets/inlineinput/inlineinput.module.ts

- onBlur the fields get closed and changes are lost
- showing error message on input type mismatch
___

fix(dynamic-field): usability issues fixed with dynamic field

---

package-lock.json
package.json
runtime/package.json
runtime/src/app/components/plan-board.module.ts

Bumped patternfly-ng version to match fabric8-ui.
Also fixed a duplicate identifier 'CommonModule', which prevented the current build from succeeding.

Update patternfly-ng version

---

src/app/components_ngrx/label-selector/label-selector.component.ts

Make label search case-insensitive in the quick preview.
https://github.com/openshiftio/openshift.io/issues/3640
___

fix(label): Make label search case-insensitive.

---

src/app/components_ngrx/dynamic-field/dynamic-field.component.html
src/app/components_ngrx/dynamic-field/dynamic-field.component.less
src/app/components_ngrx/work-item-detail/work-item-detail.component.html
src/app/components_ngrx/work-item-detail/work-item-detail.component.less

This PR will fix the alignment of dynamic fileds in scrum template
https://github.com/openshiftio/openshift.io/issues/3740#event-1687919379
NA
___
@Raunak1203 @nimishamukherjee

fix(scrum-template): fix dyanmic fileds css

---

runtime/src/assets/stylesheets/shared/_utilities.less
src/app/components/work-item-quick-add/work-item-quick-add.component.less
src/app/components_ngrx/group-types-panel/group-types-panel.component.html
src/app/components_ngrx/infotip/infotip.component.less
src/app/components_ngrx/planner-list/planner-list.component.html
src/app/components_ngrx/planner-list/planner-list.component.less
src/app/components_ngrx/toolbar-panel/toolbar-panel.component.html
src/app/components_ngrx/toolbar-panel/toolbar-panel.component.less
src/app/components_ngrx/work-item-quick-add/work-item-quick-add.component.html
src/assets/stylesheets/shared/_utilities.less
src/tests/ui/planner/toolbarHeader.ts

This PR will fix the alignment of quick add, making consistent padding around the elements and fix visibility of the infotip icon 
https://openshift.io/openshiftio/openshiftio/plan/detail/2512
https://openshift.io/openshiftio/openshiftio/plan/detail/2511
___
@rgarg1 @nimishamukherjee

fix(quick-add): fix alignment of quick add

---

package-lock.json
package.json
runtime/package.json

Updating patternfly-ng package version to sync with fabric8-ui.

Update patternfly-ng version to 3.10.3

---

src/app/components_ngrx/toolbar-panel/toolbar-panel.component.ts
src/app/components_ngrx/work-item-detail/work-item-detail.component.ts
src/app/components_ngrx/work-item-detail/work-item-detail.spec.ts
src/app/effects/area.effects.ts
src/app/effects/collaborator.effects.ts
src/app/models/work-item.ts

Fixes https://github.com/openshiftio/openshift.io/issues/3642
Assignees & Creators, Areas, Labels, Iterations are sorted alphabetically in all dropdowns

fix(filter-values): filter values sorted alphabetically

---

src/app/models/comment.spec.ts
src/app/reducers/comment.reducer.spec.ts

Add unit tests for comment reducer.
Yes

fix(test): add unit tests for comment reducer

---

src/app/reducers/custom-query.reducer.ts
src/app/reducers/custom-query.spec.ts

Added unit tests for custom query reducer.
Yes

fix(test): add unit tests for custom query reducer.

---

src/app/components_ngrx/work-item-link/work-item-link.component.ts
src/app/reducers/work-item.reducer.ts
src/tests/specs/detailPage.spec.ts
src/tests/specs/smoke/smokeTest.spec.ts
src/tests/support/constants.ts
src/tests/ui/planner/workitem-quickpreview.ts

Fix delete link issue.
https://github.com/openshiftio/openshift.io/issues/3601
Yes

fix(link): Delete link issue.

---

src/app/effects/collaborator.effects.ts
src/app/services/collaborator.service.spec.ts
src/app/services/collaborator.service.ts

Add Unit Tests for Collaborator service
YES
___

fix(services): add unit-tests for collaborator services

---

src/app/models/work-item.ts
src/app/reducers/work-item.reducer.spec.ts

Added unit tests for work item reducer.
Yes

fix(test): add unit test for work item reducer

---

src/app/reducers/group-type.reducer.spec.ts

Added unit tests for group type reducer.
Yes

fix(test): add unit test for group type reducer

---

src/app/components_ngrx/work-item-detail/work-item-detail.component.html
src/app/components_ngrx/work-item-detail/work-item-detail.component.ts
src/app/components_ngrx/work-item-link/work-item-link.component.html
src/app/components_ngrx/work-item-link/work-item-link.component.ts
src/app/effects/work-item.effects.ts

Remove URL cunstruction function
https://github.com/openshiftio/openshift.io/issues/3845
NA

fix(detail): Deprecate URL construction for detail page.

---

src/app/models/board.model.spec.ts
src/app/models/board.model.ts
src/app/models/work-item.ts
src/app/services/board.service.spec.ts
src/app/services/board.service.ts
src/app/services/board.snapshot.ts

This PR has board service, model and mapper
___

Board service, model and mapper is added

---

.dockerignore

fix(tests) : updated dockerignore

---

src/app/components_ngrx/planner-list/planner-list.component.ts
src/app/components_ngrx/toolbar-panel/toolbar-panel.component.ts
src/tests/specs/workItemTableTest.spec.ts

Filter work item by state close
https://github.com/openshiftio/openshift.io/issues/3955#issuecomment-404144985
Yes

fix(list): filter work item by state close

---

cico_setup.sh
cico_test_prod.sh
src/tests/specs/agileTemplate.spec.ts
src/tests/specs/collaboratorTest.spec.ts
src/tests/specs/detailPage.spec.ts
src/tests/specs/iteration.spec.ts
src/tests/specs/quickPreview.spec.ts
src/tests/specs/smoke/smokeTest.spec.ts
src/tests/specs/workItemTableTest.spec.ts
src/tests/ui/planner/workitem-list.ts
src/tests/ui/planner/workitem-quickadd.ts
src/tests/ui/planner/workitem-quickpreview.ts

This PR fixes the tests to run against production and on prod-preview
yes
___

fix(test) : fix test to run against production and prod-preview

---

src/tests/page_objects/app.page.ts
src/tests/specs/smoke/smokeTest.spec.ts
src/tests/ui/planner/workitem-quickpreview.ts

- This PR fixes the Creator image tests for the prod-preview test account and link tests
- Added selector for Plan, Backlog, and Board Tab.
Yes
___

[WIP]fix(test) : update creator and link tests to run against prod-preview

---

cico_test_prod.sh

This PR fixes the script to run tests periodically on Production and prod-preview
___

fix(test) : fix script to run the tests on production and prod-preview

---

cico_test_prod.sh
src/tests/page_objects/app.page.ts
src/tests/specs/smoke/smokeTest.spec.ts
src/tests/ui/planner/workitem-quickpreview.ts

Fix script test

---

src/tests/specs/workItemTableTest.spec.ts

This PR fixes the failing label test due to changes in the API tests PR https://github.com/fabric8io/fabric8-test/pull/911
___

fix(test) : fix failing label test

---

src/app/components_ngrx/planner-list/planner-list.component.ts
src/tests/specs/agileTemplate.spec.ts

Do not show Closed work item in the list.
https://github.com/openshiftio/openshift.io/issues/3943
Yes

fix(list): by default remove Closed work item from list.

---

src/app/components_ngrx/planner-list/planner-list.component.ts
src/app/components_ngrx/planner-query/planner-query-routing.module.ts
src/app/components_ngrx/planner-query/planner-query.component.html
src/app/components_ngrx/planner-query/planner-query.component.ts
src/app/components_ngrx/planner-query/planner-query.module.ts
src/planner.module.ts
src/tests/specs/agileTemplate.spec.ts

For custom-query support story this PR adds a basic query module skeleton with routing.
https://openshift.io/openshiftio/Openshift_io/plan/detail/360
___

feat(query-tab): Added basic query module with routing.

---

package-lock.json
package.json
src/app/components_ngrx/planner-query/planner-query-routing.module.ts
src/app/components_ngrx/planner-query/planner-query.module.ts
src/app/shared/toggles-api.provider.ts

- This PR adds internal feature-flag on query-module. 
- To hide query feature from people outside the organisation, it was necessary to add feature-flag on query-tab in fabric8-ui, the query-tab will be visible to only internal employees so that they are aware of query feature in fabric8-planner and feature flag is added on query-module as well so that they can opt-in for the feature if they want to. 
- When the user will click on the query-tab they will be asked to opt-in for the internal features.
-  When beta level feature-flag is selected the user can access all the other features like backlog but query feature will not be available and the user will be asked …

add feature-flag on query-module

---

src/app/components_ngrx/common-selector/common-selector.component.html
src/app/components_ngrx/work-item-detail/work-item-detail.component.html
src/app/components_ngrx/work-item-detail/work-item-detail.component.less
src/app/components_ngrx/work-item-detail/work-item-detail.component.ts
src/app/effects/work-item.effects.ts
src/app/models/common.model.ts
src/app/models/work-item.ts
src/tests/specs/collaboratorTest.spec.ts
src/tests/specs/detailPage.spec.ts
src/tests/specs/smoke/smokeTest.spec.ts
src/tests/ui/planner/workitem-detailpage.ts
src/tests/ui/planner/workitem-quickpreview.ts

This PR integrates UI for change work item 
type feature in planner quick preview and 
detail page.
Parent Story - https://openshift.io/openshiftio/Openshift_io/plan/detail/43
Task - https://openshift.io/openshiftio/Openshift_io/plan/detail/65
Yes
___

feat(change-wi-type): user can change the wi type.

---

src/app/components_ngrx/planner-list/planner-list.component.less

This PR will fix two issues - 
1. Fix overflow work item title
2. Align the cell items to center
3. Fix misalignment of cells after applying config settings
https://github.com/openshiftio/openshift.io/issues/4152
https://github.com/openshiftio/openshift.io/issues/3650
NA
___
@nimishamukherjee

fix(wi-title): fix title overflow and align cell items center

---

cico_setup.sh

With this PR
- Snapshot images are pushed to quay.io instead of devshift registry
Fixes https://github.com/openshiftio/openshift.io/issues/4088

Push PR Snapshot images to quay.io instead of devshift

---

src/app/components_ngrx/work-item-cell/work-item-cell.component.html
src/app/components_ngrx/work-item-cell/work-item-cell.component.less

fixes the title column for query page
___

fix(workItemCell): fix title truncate for query page

---

src/app/components_ngrx/work-item-event/work-item-event.component.html

This PR fixes the issue with events created by non-collaborators
No reference 
No, the associated component is temporary and likely to be removed shortly.
1. Create a work item
2. Have a collaborator perform some action on that item
3. Remove the user from collaborator
4. Refresh the detail page for that item
5. You'll see the error

fix(event): non-collab user issue in event is fixed

---

src/app/components_ngrx/group-types-panel/group-types-panel.component.html
src/app/components_ngrx/work-item-quick-add/work-item-quick-add.component.html
src/app/models/group-types.model.spec.ts
src/app/models/group-types.model.ts
src/app/models/work-item-type.spec.ts
src/app/models/work-item-type.ts

This PR adds support for non-static infotips ( can be changed by the user ).
https://github.com/openshiftio/openshift.io/issues/4270
Yes
___

fix(infotip): fetch and display non-static infotips

---

src/app/components_ngrx/work-item-event/work-item-event.component.html

- fixes openshiftio/openshift.io#4296
This PR fixes some template error in the event component
openshiftio/openshift.io#4296
___

fix(event): check for attribute in templates for events

---

src/app/effects/space.effects.ts
src/app/models/space.ts
src/app/shared/http-module/auth.interceptors.ts
src/app/shared/http-module/http.service.ts

- fixes openshiftio/openshift.io#4298
Planner interceptors only work on planner requests
openshiftio/openshift.io#4298
___

fix(auth-interceptor): intercepts only planner requests

---

package-lock.json
package.json

fix(ngx-login-client): stick to 1.4.5

---

src/app/components_ngrx/work-item-quick-add/work-item-quick-add.component.html
src/app/components_ngrx/work-item-quick-add/work-item-quick-add.component.ts
src/app/components_ngrx/work-item-quick-add/work-item-quick-add.module.ts
src/app/models/permission.model.ts
src/app/models/user.ts

It disables add work-item for non-collaborators except for in Openshift_io space as currently we allow non-collaborators to add work-items in Openshift_io space and since the permissions model is not yet ready so this is a temporary fix.
https://github.com/openshiftio/openshift.io/issues/3615
___

fix(quick-add): disable add work-item for non-collaborator

---

src/app/components_ngrx/planner-query/planner-query.component.html
src/app/components_ngrx/planner-query/planner-query.component.less
src/app/components_ngrx/planner-query/planner-query.component.ts
src/app/components_ngrx/planner-query/planner-query.module.ts
src/app/components_ngrx/work-item-quick-add/work-item-quick-add.component.html
src/app/components_ngrx/work-item-quick-add/work-item-quick-add.component.less
src/app/components_ngrx/work-item-quick-add/work-item-quick-add.component.ts
src/app/components_ngrx/work-item-quick-add/work-item-quick-add.module.ts
src/app/effects/work-item.effects.ts
src/tests/specs/smoke/smokeTest.spec.ts

- Add a way to create workitem from query page
https://openshift.io/openshiftio/Openshift_io/plan/detail/531
___

feat(query): create new work item dialog

---

package-lock.json
package.json
src/app/components_ngrx/dynamic-field/dynamic-field.component.html
src/app/components_ngrx/work-item-comment/work-item-comment.component.html
src/app/components_ngrx/work-item-comment/work-item-comment.module.ts
src/app/components_ngrx/work-item-detail/work-item-detail.component.html
src/app/components_ngrx/work-item-quick-add/work-item-quick-add.component.ts
src/app/widgets/inlineinput/inlineinput.component.html
src/tests/specs/quickPreview.spec.ts
src/tests/specs/templateSpecificTests/agileTemplate.spec.ts
src/tests/ui/planner/workitem-quickpreview.ts

This PR implements close text-fields on outside click
Fixes https://github.com/openshiftio/openshift.io/issues/4049
Yes
___

fix(quick-preview): add close text-fields on outside-click

---

src/app/components_ngrx/iteration-list-entry/iteration-list-entry.component.html
src/app/components_ngrx/iteration-list-entry/iteration-list-entry.component.less

fix(iteration-panel): Update the onscreen display text when no date has been set.
https://github.com/openshiftio/openshift.io/issues/2292

fix(iteration-panel): Update the onscreen display text when no date has been set.

---

src/app/components_ngrx/planner-list/planner-list.component.ts

fixes https://github.com/openshiftio/openshift.io/issues/4025
https://github.com/openshiftio/openshift.io/issues/4025
___

fix(planner-list): preserve treeStatus value on workitem update

---

src/tests/specs/workItemTableTest.spec.ts

This PR fixes failing tests
___

fix(test) : fix failing tests

---

src/app/components_ngrx/assignee/assignee.component.spec.ts

This PR adds unit tests for assignee component
yes
___

Add unit tests for assignee component

---

package-lock.json
package.json
src/app/components_ngrx/assignee/assignee.component.spec.ts

Update prod-preview test branch

---

package-lock.json
package.json
src/app/components_ngrx/assignee/assignee.component.spec.ts

Update prod test branch

---

cico_test_prod.sh

fixes Jenkins jobs
@Raunak1203

fix(test-script): path to jenkins-env file fixed
